### ISSUE TITLE
Less intrusive plot citations

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris#132]
1. Can we move the citation out of the plot area?
2. Can we avoid having lots of citations when using subplots (e.g. lagged ensemble example). Either by making it opt-in (as suggested in #48), or making it easy to opt-out.

Fixing (1) might fix (2).

**Comment by rcomer** [comment]
Hi @rhattersley @marqh, I’m just doing a bit of housekeeping.  Do you remember what this was about?  I have a vague memory that it was a feature long since remove from Iris...

**Comment by rhattersley** [comment]
Citations require explict code. Perhaps once they didn't. Finding out for sure would require code archaeology, sorry.

Running ...
```python
import matplotlib.pyplot as plt
import iris.plot as iplt
iplt.citation('Hello world')
plt.show()
```
... gives:
<img src="https://user-images.githubusercontent.com/917914/93597992-e7b3bd80-f9b3-11ea-9f29-6580b3d50483.png" width="40%">
So citations still appear within the plot area itself.

No one else has commented on this issue in seven years though which suggests it's not a big problem. Don't keep it open on my account! 👍

**Comment by rcomer** [comment]
Thanks @rhattersley, seems I misremembered!

**Comment by rcomer** [comment]
This function is doing something very specific and, as far as I can see, only uses `matplotlib` functionality to do it.  So as a user it's not something I'd expect Iris to do for me.

It looks like there were some auto-citations for Brewer colours in the past, e.g.
https://github.com/SciTools/iris/blob/2aba9dd68fbebed47507c0388828cded063b4130/lib/iris/plot.py#L438-L439

so maybe that's why it was included.  But by itself I'm not convinced it really belongs in Iris.  Whether it's worth the work of deprecation and removal is another matter!

So that's my 2 cents - I will leave it to @bjlittle and the Peloton to make a decision.

**Comment by alastair-gemmell** [comment]
Peloton 22nd Sept - decided to close this issue as deemed no longer relevant. Feel free to reopen if you disagree :)
