### ISSUE TITLE
ImportError, GLIBC_2.7 not found

### ISSUE THREAD

**Issue by qAp** [SciTools/iris#1543]
After installing iris with
```
conda install -c scitools iris
```
, importing gives
```
In [3]: import iris
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-005053b25f37> in <module>()
----> 1 import iris

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/iris/__init__.pyc in <module>()
    102 
    103 import iris.config
--> 104 import iris.cube
    105 import iris._constraints
    106 import iris.fileformats

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/iris/cube.py in <module>()
     34 import numpy.ma as ma
     35 
---> 36 import iris.analysis
     37 from iris.analysis.cartography import wrap_lons
     38 import iris.analysis.maths

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/iris/analysis/__init__.py in <module>()
     55 import scipy.stats.mstats
     56 
---> 57 from iris.analysis._interpolator import (_LINEAR_EXTRAPOLATION_MODES,
     58                                          LinearInterpolator, LinearRegridder)
     59 from iris.analysis._area_weighted import AreaWeightedRegridder

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/iris/analysis/_interpolator.py in <module>()
     23 
     24 from iris.analysis._scipy_interpolate import _RegularGridInterpolator
---> 25 from iris.analysis.cartography import wrap_lons as wrap_circular_points
     26 from iris.coords import DimCoord, AuxCoord
     27 import iris.cube

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/iris/analysis/cartography.py in <module>()
     27 import numpy.ma as ma
     28 
---> 29 import cartopy.img_transform
     30 import cartopy.crs as ccrs
     31 import iris.analysis

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/cartopy/__init__.py in <module>()
    107 # Commonly used sub-modules. Imported here to provide end-user
    108 # convenience.
--> 109 import cartopy.crs
    110 import cartopy.feature

/nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/cartopy/crs.py in <module>()
     34 import six
     35 
---> 36 from cartopy._crs import CRS, Geocentric, Geodetic, Globe, PROJ4_RELEASE
     37 import cartopy.trace
     38 

ImportError: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /nuwa_cluster/home/jackyu/locally_installed_python_pacakges/anaconda/envs/py27/lib/python2.7/site-packages/cartopy/../../../libproj.so.0)

In [4]: 
```

Is this a 32/64 bit problem?  How can I fix this?  Thanks

**Comment by pelson** [comment]
> Is this a 32/64 bit problem? How can I fix this? Thanks

Hi @qAp. This is a problem with the way we build the conda packages. At the moment, we use travis-ci to build and upload to binstar, and it is these which you have installed. The problem with this is that travis-ci is running a pretty up-to-date libc (I think it is 2.14, from June 2011). My guess would be that you are on a RHEL6 machine, which is running libc 2.12. Unfortunately libc is not forwards compatible (at least between these two versions), and so you get the error you are seeing.

For the record, I also get the same error when installing on my enterprise desktop (RHEL6).

Other people have had similar experiences with automatically building from travis-ci (e.g. https://github.com/pandegroup/openmm/issues/513), and I don't really have a clean solution to fixing the problem. One possible option is to downgrade the travis-ci libc version, or even have conda install its own version of libc (perhaps by supporting https://github.com/conda/conda-recipes/pull/48). The continuum guys just have a VM which is pretty ancient (CentOS 5 by the looks of things), and it is all dandy (because of backwards compatibly in libc).

All in all, I'm not sure of the best route to take here. What are your thoughts?

**Comment by ocefpaf** [comment]
@pelson We had this issue when using locally built conda packages on wakari.  At the time I thought that the new "[binstar build service](http://docs.binstar.org/build_cli.html)" would be a solution beacuse the packages would get built using a VM that has a GLIBC consistent  with conda default packages.

At the time I got stuck building udunits on binstar build and gave up.  (I think the reason was the lack of dependencies that we assume for granted in modern linux distros, like autoconf.)

Anyways, I am keeping an eye on binstar build (hoping for some improvement).  If you ever try it let me know what you think.

**Comment by qAp** [comment]
@pelson Thanks for the for explanation.  If I understand correctly, https://github.com/conda/conda-recipes/pull/48 doesn't quite work yet, https://github.com/pandegroup/openmm/issues/513 works but takes effort to build the VM needed, and Continuum already has the VM to do it.   So, is it not easiest if Continuum did it?

**Comment by pelson** [comment]
> So, is it not easiest if Continuum did it?

That would be super! But that isn't something we can demand of Continuum. One option is we disable automatic uploading to binstar from travis-ci Linux, and build those manually (as we do already for linux-32) on an old-ish machine (such as my enterprise RHEL6 box). 

Whilst it is for Iris, the change will need to happen in https://github.com/SciTools/conda-recipes-scitools, so would you mind opening an issue there @qAp which references back to this?

Thanks!

**Comment by pelson** [comment]
This should now be fixed on the scitools channel. If you have any problems, please open an issue on the https://github.com/SciTools/conda-recipes-scitools repo.

Thanks!
