### ISSUE TITLE
Constrained fileformats

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1728]
Currently iris hard-codes the NetCDF saver as being the only one exempt from having to support 'append' for the given fileformat.
https://github.com/SciTools/iris/blob/94cc87df153dd2d7320f09fa51f4e197b620fca7/lib/iris/io/__init__.py#L357

Supporting the append keyword means to pass the registered fileformat a cube at a time.

When registering an additional fileformat, it should not be necessary to modify the exclusion list in `iris.io`.

**Comment by cpelley** [comment]
@jkettleb this may be of interest to you in our review.

**Comment by rhattersley** [comment]
> When registering an additional fileformat, it should not be necessary to modify the exclusion list in iris.io.

:+1:

However, another way to tackle this is to deprecate `iris.io.save()` (AKA `iris.save()`)... :+1: :grin:

**Comment by theabro** [comment]
I would like to concur regarding the 'append' functionality for netCDF. Being able to append cubes, one cube at a time, would save memory, otherwise all cubes would need to be loaded at the same time.

**Comment by pelson** [comment]
> Being able to append cubes, one cube at a time, would save memory, otherwise all cubes would need to be loaded at the same time.

Amazingly, this isn't the case. Iris has been able to stream directly to NetCDF for some time (since a fairly early version of biggus) - which means that you do not need to realise even a single full cube in memory when saving to NetCDF.

In fact, because the coordinate information would want to be shared between variables in a NetCDF file (as is the case already), one would have to *read* from the NetCDF file in order to identify whether appending a cube requires more coordinate information to be provided, or if existing information can be re-used. In short, I suspect appending to NetCDF would actually have quite a negative performance impact.

That's not to say it wouldn't be useful, just that if the motivation for this is performance, there may be better places to focus effort.


> Currently iris hard-codes the NetCDF saver as being the only one exempt from having to support 'append' for the given fileformat.

I'm guessing this is coming from the angle that some file formats just aren't append-able (such as UM Fieldsfiles) and you want to hook into the saving machinery?

> However, another way to tackle this is to deprecate ```iris.io.save()``` (AKA iris.save())

:smile: you should come and do a training course with me. The fact that iris.save is so simple is worth more than you give it credit for. There is nothing stopping one from using the save functions directly if there isn't appropriate generality in ``iris.save``. One simplification I would support though, ```iris.save``` needn't be extensible - let's hardcode it to the formats we know and reduce some of that complexity....

**Comment by cpelley** [comment]
> I'm guessing this is coming from the angle that some file formats just aren't append-able (such as UM Fieldsfiles) and you want to hook into the saving machinery?

That's correct.  I believe perhaps my original issue description might have been miss-leading.  I only bring to attention that the current mechanics do not allow for arbitrary savers to be added to iris (specifically ones which do not support appending), like you say UM Fieldsfiles.

> There is nothing stopping one from using the save functions directly if there isn't appropriate generality in iris.save

Yes I agree.

> The fact that iris.save is so simple is worth more than you give it credit for.

Apologies, I only meant this as a use case for possibly generalising the saver :)

> One simplification I would support though, iris.save needn't be extensible - let's hardcode it to the formats we know and reduce some of that complexity.

Are you proposing to deprecate `iris.io.add_saver` for now?

Sounds like we are proposing to deprecate iris save (`iris.io.save`) in the medium-long term, is that correct?

**Comment by cpelley** [comment]
> However, another way to tackle this is to deprecate iris.io.save() (AKA iris.save())

Has it been decided whether this is to be proposed for the iris v2.0 release?

**Comment by rhattersley** [comment]
> Has it been decided whether this is to be proposed for the iris v2.0 release?

I've not seen any decisions, but based on @pelson's feedback it doesn't sound like a good idea. Perhaps we might still consider reducing the open-ended nature of the function though? For example, @pelson has suggested fixing the list of formats, or we could move away from the "sloppy" argument handling with `**kwargs` and special treatment of `append`?

**Comment by cpelley** [comment]
Hi @SciTools/iris-devs, I would like to bring this issue back into view since iris v2 is on the horizon.
Currently, we extend iris handling by decorating iris.io.save  this is obviously far from ideal.

What if iris.io.save simply discriminated on the presence of the 'append' keyword argument and simply remove the check that it lives in the netcdf module.  That is, if it supports append, then pass it a cube at a time, if not then pass it a cubelist.  Is there a reason why that doesn't generalise?

Cheers
