### ISSUE TITLE
Stop using `jet` by default

### ISSUE THREAD

**Issue by QuLogic** [SciTools/iris#1780]
Matplotlib is on its way to removing `jet` as its default colour map. But `iris` supports, and is tested against, a much older version. To provide some consistency, it would be better if a default was set across versions.

I did not open a PR since I'm not certain whether `viridis` would be suitable.

**Comment by rcomer** [comment]
You've probably got this covered, but:  if Iris had its own default, would this override the cmap set in a user's custom `matplotlibrc` file?

**Comment by ajdawson** [comment]
I'm not sure I agree with this. Deferring to the plotting layer for colormap seems the logical and correct thing to do, and as @rcomer says we should respect the setting the user chooses in their matplotlibrc. If a user upgrades to matplotlib v1.5 and the colormap in iris plots changes, I think that is fine, the change is well documented on the matplotlib side.

However, I do think we should do something about the infestation of jet in the documentation gallery, but via an explicit setting in the examples rather than a default.

**Comment by QuLogic** [comment]
I'm not totally tied to changing the default itself, if it causes issues with `matplotlibrc` (I didn't know that existed and anyone used it). Really, like @ajdawson, I want those examples to look a bit better. Also, the tests will start failing on matplotlib 1.5 (not that they pass on 1.4.3 right now either.)

**Comment by pelson** [comment]
> not that they pass on 1.4.3 right now either

We need to fix it so that we are not testing against an ancient mpl version - I think picking v1.5 as a target point makes a lot of sense for testing, once the mpl release dust has settled.

**Comment by pelson** [comment]
Closing as modern mpl has this by default: Iris will be moving in the direction of modern matplotlib (though it isn't currently tested against mpl 2). I'm completely in favour of jet being moved into the sidelines.
