### ISSUE TITLE
Python3 GRIB provision

### ISSUE THREAD

**Issue by marqh** [SciTools/iris#1807]
This ticket spawned from #1774 

The aim is to agree an approach to longer term provision of GRIB support.

This should involve adoption of ecCodes from ECMWF 
https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home

and engagement with ECMWF on python version handling and other details.

**Comment by QuLogic** [comment]
Please see SciTools/conda-recipes-scitools#79 for full patch. The two remaining issues from #1774 are that tests for `int` arrays are no longer correct, and reads from Python file objects seem to be buffered. To fix the latter, ecCodes might need to provide its own open/close functions instead of using `FILE*` and/or allow overriding read/write methods (so the Python wrapper could use its own methods.)

**Comment by pelson** [comment]
eccodes is the way forwards within https://github.com/scitools/iris-grib
