### ISSUE TITLE
simple load of a netcdf leads to a writting fc_rules_cf_fc.py error

### ISSUE THREAD

**Issue by PBrockmann** [SciTools/iris#1824]
I am confused with this simple load of a netCDF file

``` python
cubes = iris.load("levitus_climatology.nc")
```

I get 

```
OSError: [Errno 13] Permission denied: '/opt/anaconda/lib/python2.7/site-packages/iris/fileformats/_pyke_rules/compiled_krb/fc_rules_cf_fc.py'
```

tested with last 1.8.1

**Comment by ajdawson** [comment]
It seems the very first time you try and use the netcdf interface it tries to recompile the pyke rules files (even though with the pre-built conda packages they include the compiled files, not sure that is correct). Subsequent uses don't need to do anything it seems.

You see the permission error because you have iris installed as root but are running for the first time as a user. All in all this looks like a bug, this shouldn't be happening. You may be able to work around this by running your example code once as root (e.g. with sudo).

I'm not sure who to flag this up to, perhaps @bjlittle or @rhattersley from a quick look at git blame... We've probably not paid attention to this because we havne't tested installing as root, but it looks like it might cause some difficulties to end users.

**Comment by rhattersley** [comment]
> this looks like a bug

Agreed. Conda packages already include the built pyke files and `python setup.py install` is how the conda package is built in the first place.

@PBrockmann - how did you install Iris?

> perhaps @bjlittle or @rhattersley

Oh definitely @bjlittle :wink:

**Comment by PBrockmann** [comment]
Simply by a conda install -c scitools iris
