### ISSUE TITLE
ENH: Publicise format specifications

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#1886]
Currently, iris does not cater for those libraries which wrap its fileformats.

**Use case:**

We are currently wrapping `iris.fileformats.ff.load_cubes` to provide additional functionality.  Doing so has meant creating new format specifications with higher priority than those currently specified in `iris.fileformats.FORMAT_AGENT`.

**Proposed change:**

Making the format specifications in `iris.io.format_picker.FormatAgent` public would make this a great deal easier.  This would allow the overriding behaviour.

A medium-long term solution is provide easy capability to somehow hook into different FormatAgent objects depending on which library is utilised and being ale to use an existing instance as a template perhaps.

**Note:**

Wrapping iris modules is the lesser of two evils chosen in order to allow us to extend functionality where there is no interest on github issues/PRs or time constraints are of weeks.

**Comment by pelson** [comment]
Hi @cpelley - thanks for raising.
If I was to sit down to try to address this issue, I'm not sure I would understand what was needed.

Do you mean https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/__init__.py#L129-L135?
Is it that you want to get these programatically?

Honestly, if you just want to override existing functionality and not add a new file format, then I'd just write a function and stop using ```iris.load``` - the machinery is all there, and it is probably fewer LOC. 

> Doing so has meant creating new format specifications with higher priority than those currently specified in iris.fileformats.FORMAT_AGENT.

On the other hand, I don't see a problem with that. You've extended the capability, and you are effectively saying that your version is superior to the built-in one, so you get the expected behaviour. There are, of course, drawbacks - the biggest being that you are modifying global state, and ```iris.load``` simply ceases to use the old, built-in, loader.

How about raising a PR with the changes you *actually* wanted to see (just a hack and slash - it doesn't need tests etc.) would allow us to see one way of solving the problem you are having.

Thanks!

**Comment by cpelley** [comment]
Thanks @pelson, yes I think you have understood the just of our requirements.  The primary issue I had was that we cannot infer the correct priorities from the the iris fileformats, since the registered format specifications are private attributes of the FormatAgent object.  We have hardcoded the priorities for our ancillary loader based on the values set in https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/__init__.py#L129-L135

> How about raising a PR with the changes you actually wanted to see...

I'll throw something together when I have time, thanks for your interest @pelson

**Comment by pp-mo** [comment]
Thanks for raising this @cpelley 
Just to clarify / can you confirm...
As far as I can see, the key problem is **only** that you can't enumerate or interrogate the contents of FORMAT_AGENT?
Thus *if you could list all the contained format specs* then I think all the key properties of each spec are _themselves_ publicly available (though mostly read-only), and you could add in another with knowledge of the existing ones

That said, I think it might also make good sense to be able to actually _remove_ existing specs, rather than just insert ones with higher priority.
Of course, we could still retain a private internally-sorted list for efficiency

**Comment by cpelley** [comment]
> As far as I can see, the key problem is only that you can't enumerate or interrogate the contents of FORMAT_AGENT

Hi @pp-mo , yes this tallies with my proposal in the ticket description ("Making the format specifications in iris.io.format_picker.FormatAgent public").
I hadn't thought to extend this idea to removing specifications, simply because there would be an additional cost to the change with little real benefit to us.  I could be missing something, but I'll come up with something and put up for PR then we can discuss it there.

Thanks for your input @pp-mo, cheers.
