### ISSUE TITLE
Loading netCDF file with long_name attribute, iris ignores variable name

### ISSUE THREAD

**Issue by ritviksahajpal** [SciTools/iris#1902]
I have a netCDF with several variables, each of which has a long_name, attribute.

When I try to load the file so:
`cubes = iris.load(nc_file, variable_name)`

This works only if variable_name is long_name and not if I use the variable name assigned to that variable.

**Comment by ajdawson** [comment]
This is by design, see the user guide section on [constrained loading](http://scitools.org.uk/iris/docs/latest/userguide/loading_iris_cubes.html#constrained-loading), in particular the section on how [name is defined](http://scitools.org.uk/iris/docs/latest/iris/iris/cube.html#iris.cube.Cube.name). Iris supports many file formats but the `var_name` attribute is specific to the netcdf interface, and therefore we use the more general concept of name to refer to cubes.

It isn't actually all that easy to load based on variable name, but if you know the value standard_name or long_name then you won't need to.

**Comment by ritviksahajpal** [comment]
Thanks! this is very helpful information.
