### ISSUE TITLE
HDF5 support

### ISSUE THREAD

**Issue by mikecharles** [SciTools/iris#1914]
Any plans for HDF5 support?

**Comment by marqh** [comment]
Hello @mikecharles 

Working with HDF5 data by hand is all right: we already have the HDF C library as a dependency and the Python H5Py module is nicely featured.
However, this requires the user to fully manage the interpretation of their metadata to build Iris Cubes before any further Iris benefits can be usefully accessed.
HDF5 is a generic container, one can put any metadata (or none); knowing what all the parts mean is not a generally soluble problem.

In order to get the kind of load behaviour we have for CF-netCDF, GRIB2 etc. we would need to talk about an appropriate metadata standard used for HDF data sets.

Are there metadata standards for HDF which you have in mind that fit in this space?

marqh

**Comment by mikecharles** [comment]
Thanks @marqh, I'm not sure about the HDF metadata standards we would use. I'm not even sure we're going to be using HDF. Here at CPC in NOAA, everything's in grib2, but I'm investigating storing my data in something with more flexibility, and iris came up at a workshop here in the D.C. area.

Thanks for the info.

**Comment by pelson** [comment]
Thanks for asking @mikecharles. I'll go ahead and close this. FWIW, it is possible to construct Iris cubes by hand, as has been done in this (reasonably complex) example: http://scitools.org.uk/iris/docs/latest/examples/General/custom_file_loading.html#custom-file-loading

Thanks!
