### ISSUE TITLE
Saving (un-) rotated winds to file

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#1955]
Does iris allow to save dimension coordinates along with auxiliary coordinates of a cube after applying `iris.analysis.cartography.rotate_winds()`? Example:

```
import iris
import numpy as np

cube = iris.cube.Cube(np.arange(12).reshape(3, 4)) 

rot_cs = iris.coord_systems.RotatedGeogCS(10.5, 154.8, ellipsoid=iris.coord_systems.GeogCS(6371229.0))
cs = iris.coord_systems.GeogCS(6371229.0)

lon = iris.coords.DimCoord(np.arange(3), 'grid_longitude', coord_system=rot_cs)
lat = iris.coords.DimCoord(np.arange(4), 'grid_latitude', coord_system=rot_cs)
cube.add_dim_coord(lon, 0)
cube.add_dim_coord(lat, 1)

cube2 = cube.copy() # v-wind = u-wind

print(cube)

u, v = iris.analysis.cartography.rotate_winds(cube, cube2, cs) 

iris.save([u, v], 'test_uv.nc')

f = iris.load('test_uv.nc')
print(f[0])
```

The 1st print gives:

```
unknown / (unknown)                 (grid_longitude: 3; grid_latitude: 4)
     Dimension coordinates:
          grid_longitude                           x                 -
          grid_latitude                            -                 x
```

The 2nd print gives:

```
transformed_unknown / (1)           (-- : 3; -- : 4)
     Auxiliary coordinates:
          projection_x_coordinate       x       x
          projection_y_coordinate       x       x
     Attributes:
          Conventions: CF-1.5
```

As you can see, the dim_coords have not been saved, and only the auxiliary (x, y) coordinates appear. Is this a bug? Can both of them be saved somehow?

Thanks,
Denis

**Comment by pp-mo** [comment]
Hi @dennissergeev 
Thanks for engaging !
I've found this no longer happens with the latest Iris version, but the reasons are a bit obscure.

It is *something* to do with the changes introduced by #1943 "Fix to automatic deriving of units when saving in netcdf format".
However, it's not obvious to me why this has changed :  The "problem" is that the old version of the saved file has units for gird_longitude an grid_latitude of 'degrees', whereas the new one has '1' (because you don't set the units in the test construction).  The version with 'degrees' is not liked and it throws away those coords on load.  Odd !
More to come...

**Comment by pp-mo** [comment]
I've looked into this now, and there are a lot of problems hiding under the hood.
The short account:
  * the grid_longitude and grid_latitude variables in this example are loaded by the latest Iris only because they ***don't*** have appropriate units ('degrees north' or simliar), and thus are not recognised as actual latitude and longitude coordinates.
   * in this odd case, they have anyway lost the coordinate system, so are not much use.
   * If you _correct_ the units, these coords are no longer loaded :  This is what happens with the file as saved from iris release 1.9.2 (before we fixed the units that lat/lon coordinates get saved with).
  * we currently have ***no*** correct way of saving this information, and no easy solution, as the CF spec itself is deficient in this respect.

It seems that iris load rules are not really comfortable with multiple grid mappings, but then in fact neither is the whole CF data model, because it associates grid_mapping (i.e. coordinate systems) with _data variables_ instead of _coordinates_.
So, in this case specifically, as there is no data variable being saved that maps to the original grid_longitude and grid_latitude variables, these get lost when loading the data, as it relates to the new rotated coords.
Effectively the _dimensions_ grid_lat/longitude still belong to the original rotated system, but without a suitable data variable to attach the grid mapping _to_, CF1.5 has no way of correctly representing that.  Instead, the only grid_mapping variable is the unrotated one, which represents the projection_x/y_coordinate system, not the grid_lat/longitude one.

The odd case where the grid_latitude and grid_longitude ***are*** loaded only occurs because in this case, with unsuitable units, they can't be seen as standard latitude + longitude coordinates, and are therefore attached as 'miscellaneous extras' to the cube.  These additional coordinates then no longer have the correct associated coordinate system (the rotated one), as it was not recorded in the file.

I am informed that CF1.7-dev may be proposing a means of properly resolving some of these cases, but at present I don't think we have any clear route to making this work the way you would expect.

**Comment by pp-mo** [comment]
Extra note:
I tried saving *both* the rotated data and the original cube to the same file.
The netcdf looks more sensible reasonable (there are two grid mappings, and each data variable maps to the correct one).
However, the rotated data cube does not read back correctly -- it still has no grid_lon/latitude coordinates.  I think the Iris load rules can currently only handle only one grid mapping, though clearly multiple ones can be saved.

**Comment by dennissergeev** [comment]
Hi @pp-mo ,
Thank you for the detailed explanation! Hopefully, CF (do you mean netCDF4?) will allow multiple mappings.

One of the workarounds, I guess, is to demote the grid_longitude and grid_latitude to `aux_coords` of the rotated cube. Then, after loading the cube again, promote them to `dim_coords`...

Cheers,
Denis

**Comment by pp-mo** [comment]
Hi @dennissergeev !

> CF (do you mean netCDF4?) 

No, sorry, I mean the "NetCDF CF conventions" : http://cfconventions.org/ .
CF stands for "climate + forecasting", and is the most common NetCDF convention for encoding meteorological data.
A convention provides a set of semantic rules, layered on top of the NetCDF storage capabilities, that define what your data "means".
Our "data model" for Iris cubes intentionally follows CF more or less as closely as it can, so this is what provides the "meaning" for us :  It governs concepts like coordinates, units, auxiliary coordinates, etc.
Things that don't "fit" into CF are therefore hard for us to handle, at least automatically !
That seems to be  the problem with this case...
 
> Hopefully, CF (do you mean netCDF4?) will allow multiple mappings.

Well, in principle it already does, but the problem is that grid mappings are attached to data variables, not coordinates, and in CF coordinates do not "belong" to data variables, but to NetCDF dimensions.
Unfortunately, how data like yours "ought" to be represented is not anywhere clearly laid out in the in CF conventions document, which simply doesn't consider this kind of multi-system representation.
Likewise, Iris currently does not handle this possibility, either for save or load.
I also think that in fact that ***any*** attempt to support this in Iris support is, at present, probably just too speculative -- it might actually be better for Iris to check for such situations and raise an error !

> One of the workarounds, I guess, is to demote the grid_longitude and grid_latitude to aux_coords of the rotated cube. Then, after loading the cube again, promote them to dim_coords...

Unfortunately, I think my attempt [above] ( https://github.com/SciTools/iris/issues/1955#issuecomment-193826671) show this won't work.
It's clear that we can produce a file with multiple grid-mappings, but it doesn't load back properly : the  'rotated' coords have no coord system (even though it is there in the file).
So, even with a hack like saving two cubes to force it to create two grid mappings, we don't have a viable solution.
For now, I think we must simply limit CF saves to data with only one coordinate system.

Certainly, some workaround should be possible, but we might need to save across two files.
*Can you explain _exactly_ what you need to achieve?*

**Comment by dennissergeev** [comment]
Hi @pp-mo ,

Thanks for clarifying this out for me. You're right that my suggestion about promoting coordinates won't work, I just tried that, and indeed coord_system is not preserved.

You mentioned that coordinate system is attached to data variables, so perhaps an option is to save one of the coordinate pairs as additional data variables?

My work flow includes some post processing of Met Office Unified Model output, including the "unstaggering" and rotation of horizontal wind fields (x-wind and y-wind) from the LAM's rotated pole coordinate system. I just wanted to do that separately, before actually using the data. For now, my workaround is just to skip the rotation in "post-processing" script and do every time that in the "analysis" scripts. I just want to optimise my work flow.
