### ISSUE TITLE
Regridding to a common non-spherical grid in curl()

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#2006]
Hi,

Wouldn't it be more logical to use the original cube in the curl components regridding in `iris.analysis.calculus.curl()`? 
I.e. instead of this:

```
    if not spherical_coords:

        # TODO Implement some mechanism for conforming to a common grid
        dj_dx = _curl_differentiate(j_cube, x_coord)
        prototype_diff = dj_dx
```

have something like this:

```
    if not spherical_coords:

        # TODO Implement some mechanism for conforming to a common grid
        dj_dx = _curl_differentiate(j_cube, x_coord)
        prototype_diff = j_cube
        dj_dx = _curl_regrid(dj_dx, prototype_diff)
```

Should I create a PR?
Thanks.

**Comment by rhattersley** [comment]
Hi @dennissergeev, thanks for the suggestion. Sorry for the lack of a response, we're pretty busy trying to get v1.10 ready.

@pelson / @pp-mo - I know you're both very busy but could either of you offer a quick opinion?

**Comment by pp-mo** [comment]
Well, the result will not be the same, because dj_dx is a differential of 'j_cube' which does not have the same shape or grid (unless it is circular) -- as explained in the docstring of 'differentiate'.

I think the point of 'prototype_diff' is just to make all the partial differentials match the grid/shape of the first one calculated (dj_dx) so we can add and subtract them.
Maybe the grid of dj_dx is not really a 'natural' one for the results, being derived exclusively from the x-differential : so e.g. if the inputs are shape (ny, nx) on the same grid then the output will be (ny, nx-1).
**Is that what you meant ?**

I think this blanket regridding also allows the function to support inputs on ***staggered*** grids, which is probably an important requirement.
However, in that case neither i_cube or j_cube grids will be ideal (as they aren't the same).  In fact 'k_cube' would be a better candidate, as it is neutral to the X and Y directions.
When we don't have a k_cube, we would still need to form some kind of compromise grid from the i and j cubes ?

The comment "TODO Implement some mechanism for conforming to a common grid" seems to  indicate that the existing approach is a bit of a guess, and could be improved on.
Maybe it would be better to impose some extra requirements on the 'matching' of shapes and grids between to 2 or 3 input cubes.
From a practical point of view, improving any of this or changing it would now be a considerable fuss due to backwards-compatibility requirements.
Perhaps we could simply add a 'grid_cube' keyword that defines the grid on which the calculation is done (and have it default to dj_dx) ?

**Comment by dennissergeev** [comment]
> Well, the result will not be the same, because dj_dx is a differential of 'j_cube' which does not have the same shape or grid (unless it is circular) -- as explained in the docstring of 'differentiate'.

I agree, but then the argument still holds for the rest of the curl components: for example, `di_dy`'s grid is centred along a different axis and different to the grid of `dj_dx`. So in my opinion, the choice of the first derivative for a prototype is not really 'physically justified'.

> I think this blanket regridding will also allow the function to support inputs on staggered grids, which is probably an important requirement.

Are you sure it's permitted? Wouldn't it lead to an error after this line: ```bad_coords = coord_comparison['resamplable']```?

> However, we could perhaps add a 'grid_cube' keyword that defines the grid on which the calculation is done (and have it default to dj_dx) ?

Yes, that would be a good addition.
Thanks.

**Comment by pp-mo** [comment]
> Are you sure it's permitted?
> Wouldn't it lead to an error after this line: bad_coords = coord_comparison['resamplable']?

Ah, you are right, I just tried it.
So I think it does need them all to have matching coords, and if necessary you must regrid them onto a common grid before calling it.

**Comment by pp-mo** [comment]
If the i,j,k cubes must have common grid then it makes sense that the result should have the same.
@pelson can you see sense in this, or am I missing something ?

Unfortunately, to fix this we need to deprecate the existing behaviour before we remove/change it.
Despite what I said before about " 'grid_cube' keyword that defines the grid", I think maybe it is too confusing for the default behaviour be so broken,
In that case, I think an iris.FUTURE option would make much more sense.
E.G. ```with iris.FUTURE.context(curl_same_grid=True): ... ```.

The change isn't that complicated, though, so you can maybe quickly put up a PR which we can get  into v1.10 :wink:  ?
Then we are ready for the more sensible behaviour to become the default in v2.0.
 (see : #1948).
