### ISSUE TITLE
Biggus version compatibility

### ISSUE THREAD

**Issue by alaniwi** [SciTools/iris#2034]
The latest Iris appears to require Biggus 0.13.0 or it will give wrong answers to some array manipulations. @matthew-mizielinski has some test code to show this.

Two things (hope it's okay to combine them in one issue):

1) the latest version on PyPI is 0.12.0 but from my experimentation with Matthew's test code this does not fix the problem, so please can you put Biggus 0.13.0 onto PyPI

2) please can you add a check that will raise an exception when trying to import iris while an incompatible Biggus version is installed

Thanks.

**Comment by marqh** [comment]
hello @alaniwi 

> 1) the latest version on PyPI is 0.12.0 but from my experimentation with Matthew's test code this does not fix the problem, so please can you put Biggus 0.13.0 onto PyPI

I'll get onto this and get an update to you

> 2) please can you add a check that will raise an exception when trying to import iris while an incompatible Biggus version is installed

I'm not sure that this is a step which we will take.  I will discuss this, but raising an exception on import is a  pretty hard failure mode with no way of affecting, so it's quite a drastic approach.

I'll get back to you on this
mark

**Comment by matthew-mizielinski** [comment]
If failing on import is too aggressive, could a warning or a unit test be
used to avoid a recurrence of such an issue?

M

**Comment by ajdawson** [comment]
Would you perhaps describe the wrong answers it gets with biggus < 0.13.0? We are clear to note in the install documentation for Iris 1.9.2 that Biggus v0.12.0 or higher is required: http://scitools.org.uk/iris/docs/latest/installing.html#build-and-runtime-requirements. You seem to indicate this is not sufficient, but I think we were unaware of any issues with v0.12.0, so describing your problem would be a good starting point.

**Comment by matthew-mizielinski** [comment]
The way this was originally identified was through a simple difference of lazy loaded cubes; when plotted the areas masked out in the source data were suddenly full of zeros when plotted. The fix for the user was fairly straightforward; force the data to be loaded before performing the difference, i.e. circumvent the use of biggus.

For plotting, this is annoying, but for calculating global means this modifies scientific results (hence why I was worried about this).

The code below demonstrates this error when working with iris v1.9.2 and biggus v0.11.0;
```
import iris, biggus, numpy as np

print iris, iris.__version__
print biggus, biggus.__version__
print np, np.__version__

#create two cubes with masked data, with different values under the mask

masked_array = np.ma.MaskedArray([[1.,1.],[1.,100000.]], mask = [[False,False],[False,True]])

cube_a = iris.cube.Cube(masked_array)
cube_b = iris.cube.Cube(masked_array)

#construct the biggus arrays for the numpy masked arrays and load them into the cubes
bg_masked_array = biggus.NumpyArrayAdapter(masked_array)
cube_a.lazy_data(bg_masked_array)
cube_b.lazy_data(bg_masked_array)

#calculate difference
cube_c = cube_a - cube_b

assert isinstance(cube_c.data, np.ma.MaskedArray), "cube_c.data is:\n "+ repr(cube_c.data)
```
The output I see when I run this is

> <module 'iris' from '..../site-packages/iris/__init__.py'> 1.9.2
> <module 'biggus' from '..../.local/lib/python2.7/site-packages/Biggus-0.11.0-py2.7.egg/biggus/__init__.pyc'> 0.11.0
> <module 'numpy' from '..../python2.7/site-packages/numpy/__init__.pyc'> 1.8.2
> Traceback (most recent call last):
>   File "biggus_issue_demo.py", line 22, in <module>
>     assert isinstance(cube_c.data, np.ma.MaskedArray), "cube_c.data is:\n "+ repr(cube_c.data)
> AssertionError: cube_c.data is:
>  array([[ 0.,  0.],
>        [ 0.,  0.]])

i.e. the masking has been lost.

I've just tested the above code against biggus versions 0.11.0, 0.12.0 and 0.13.0 and, as @alaniwi mentions, only the latter (v0.13.0) passes this "test". It is quite possible therefore that iris users will have this issue in their code **__with the recommended minimum requirements__**.  This bug can change results (consider a global mean anomaly time series of SST when values on land points are erroneously included) so I'd recommend raising the minimum requirements for biggus and informing the user community of the issue.

A more general point, which I'd recommend is considered carefully, is that some form of alert is raised when a user tries to use an inappropriate version of the library either through
a) warning at import time (i.e. something which says "Version X of library Y is below the minimum requirements for iris. Correct behaviour is not guaranteed. Please upgrade Y")
b) a unit test that will fail if all minimum requirements are not met. Then by running the test suite after installation it would be clear that there is, or could be, an issue. 
If users/system admins who install the library choose not  to ignore the warnings or test failures suggested above it is then their responsibility when code misbehaves.

Apologies for the brain dump, but I wanted to make sure there was enough useful information here

**Comment by ajdawson** [comment]
OK thanks for the description @matthew-mizielinski. We can now trace this to a bug fixed in SciTools/biggus#167 which is in biggus v0.13.0 but not v0.12.0.

Since an iris v1.10 release is around the corner we must make sure the minimum version requirement for biggus is updated (if not done already). I don't know what to do (if anything) about the existing v1.9.2 release.

**Comment by dkillick** [comment]
I've merged the Iris change that introduces the Biggus v0.13 dependency and a test that demonstrates the difference (thanks @ajdawson) and I'll upload Biggus v0.13 to PyPI tomorrow - after that I think we're good to close this issue.

**Comment by alaniwi** [comment]
So will there be a warning at import time if the Biggus version is too low, please? I understand the concerns about exception on import being a rather hard failure mode, but a warning could be helpful.

**Comment by ajdawson** [comment]
No, there will be a failing test in the test suite if the biggus version is too low. The test suite can easily be run against a built version.

**Comment by dkillick** [comment]
I think that raising a warning based on the version of any dependency (the example in this case being Biggus) sets an unwanted and unusual precedent that I do not believe we want to follow in Iris. It is expected that any given library will have a required minimum version of any given dependency, and it is expected that said minimum version of the dependency will work correctly with the library at its current version. Should it not for any reason then this behaviour is a bug and should be reported, as has happened in this issue.

What it does _not_ mean is that the library should be actively checking the versions of dependencies that it is using, certainly not at import time. This position is backed up by a number of observations:

* Most pertinently, I believe this suggestion wouldn't actually work, at least not in this case. This is backed up by the fact that we believed that we had set the appropriate version of Biggus for the current version of Iris, meaning that we did not know about the failure mode raised here until it was raised. If we did not know about it then we could not test for it, and if we could not test for it then a warning about an inappropriate version of Biggus would not have been raised.
* Following on from and hinted at in the previous, what is being suggested here amounts to a **test** that the version of the dependency is appropriate for the version of the library. If it's described as a test then it belongs in the Iris tests, which is what @ajdawson has very helpfully provided for us. This way we can programmatically test for an inappropriate version of a dependency via a known failure mode rather than saying in the code that an arbitrary version of a dependency is too old.
* Following on from the last thought of the previous, this would add workload to the library devs - each time you release you would have to remember to manually confirm and bump if necessary the version of the dependency. If this gets forgotten (as it would be a manual process) and the release went out then the release will be incorrect and the check would again probably not work as it was supposed to.
* There's also the question of scope - how many dependencies would have to be checked like this? For example, Iris has a _lot_ of dependencies, so should all dependency version be checked, or only the critical ones, or only a few? And the more dependencies are being manually checked the greater the workload becomes for the library maintainers each release.
* Often, if you are using the wrong version of a dependency, the code you are running will fail anyway (for example weird results are returned or errors are encountered) because the versions of the library and the dependency do not match.
* Very similarly to the previous point, often the code you are running simply will not run because the APIs do not match between the versions of the library and the dependency do not match. This often is manifested as an error where a particular name is not found because it does not exist in the version of the dependency that is being used.
* Sometimes it is just up to the user of the library to confirm that the user code that they have written that's based on the library is behaving appropriately, which in many ways is a request for appropriate testing of the user code in question. Of course these tests _could_ be included in the library, but there's no way the library can include tests for all possible use modes - there are just too many use modes to test. Instead the library tests should confirm that all elements of code perform appropriately as discrete entities (unit tests) and as larger integrated blocks / workflows (integration tests).
* Finally, it is becoming more and more common to receive a given library within a package that contains appropriate versions of all dependencies, which means that if the library is updated and supplied in a similarly updated package then all dependencies should also be updated. For Iris, this is achieved with the [Iris env](https://anaconda.org/scitools/iris) we provide for [Conda](http://conda.pydata.org/miniconda.html).

**Comment by marqh** [comment]
I have put up a change request #2125 which updates the requirements (in conda-requirements, minimal-conda-requirements and INSTALL)
to indicate that the Iris library requires biggus 0.14 or later.
As it turns out, this is needed for other reasons.

I think this is as much as we are going to be able to deliver as part of the v1.10 release

**Comment by QuLogic** [comment]
The required minimum was updated by #2125; I think there's nothing else left to do here.
