### ISSUE TITLE
mpl scatter extents not lining up with mpl 1.5+

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2178]
Reference https://github.com/SciTools/iris/pull/2175 and https://github.com/SciTools/test-images-scitools/pull/6

Several `matplotlib.pyplot.scatter` plots under mpl 1.5.1 have changed default extents i.e. only the minor xlim is extended further than expected.

This appears to be resolved "somewhat" by re-setting the `plt.gca().margins`.

Further investigation is required to determine the cause of the change in mpl.

**Comment by pelson** [comment]
There *has* been a behaviour change between matplotlib 1.3 and 1.5 with regards to extent calculation. It is not reasonable, IMO, for Iris to try to iron out these changes so that it appears that this isn't the case. In essence, I do not expect the same code (that uses Iris) to produce the *exact* same graphic across multiple versions of matplotlib.
