### ISSUE TITLE
conda install error - please update install instructions

### ISSUE THREAD

**Issue by susoson** [SciTools/iris#2232]
The instructions at http://scitools.org.uk/iris/docs/latest/installing.html to install iris need improvement.

I first tried installing via conda install -c scitools iris in my ioos environment  - yikes!

So I created a new environment just for iris and ran: conda install -c scitools iris

Which as you know doesn't work - https://github.com/SciTools/iris/issues/1970

Using the conda forge install seems to have gotten me almost there. 

conda install -c conda-forge iris geos shapely

No errors associated with cartopy/dependencies/versions.

But when trying to run the first example: http://scitools.org.uk/iris/docs/latest/examples/General/SOI_filtering.html

I get the following error, which leads me to believe that there is another install step required for working with examples but I don't see reference to this anywhere in the documentation.

ValueError: Sample data file(s) at '/Users/jenniferpatterson/anaconda/envs/irisenv2/lib/python2.7/site-packages/iris/sample_data/SOI_Darwin.nc' not found.
NB. This function is only for locating files in the iris sample data collection. It is not needed or appropriate for general file access.

Please update the iris documentation with better instructions for installing and working with examples, I look forward to using iris but had hoped for smoother install/setup.

**Comment by dkillick** [comment]
Hi @susoson - thanks for getting in contact with us and letting us know about the difficulties you had using the install documentation for Iris. With regard to this documentation, we deliberately kept it pretty terse as the install process when using Conda is, in most cases, as short as the documentation suggests. We also deliberately have not included any documentation on using Conda as it is unwise to duplicate documentation, especially when it is not your own (as is true here), because such duplicated documentation will just go stale and be the less useful. Instead we have included links to relevant and useful sections of the Conda documentation, which take you through the steps needed to get using Conda to the point where you could use it to install Iris as the Iris documentation demos.

The problem you're having running the examples comes from the fact that you need the Iris sample data. All the examples are based on data contained within the Iris sample data, which is available as a conda package on the SciTools channel:
```
conda install -c scitools iris_sample_data
```

This will work with Iris packages from SciTools and conda-forge. With this package installed you should be able to run the example code. It may be that the install documentation would benefit from a mention of the Iris sample data package - I will propose it as a PR and see what happens.

Hope this helps.

**Comment by susoson** [comment]
Thanks @dkillick, the conda install of iris_sample_data now has me up and running! 

Indeed conda is a beast of its own, but it doesn't make sense to me that you would have a reference to use a conda command that doesn't work. I recommend replacing the conda command as follows or mentioning the the conda issue and linking to the github issue https://github.com/SciTools/iris/issues/1970 that identifies this known conda problem and identifies potential solutions like the conda-forge install.

doesn't work:
`conda install -c scitools iris`  

does work:
`conda install -c conda-forge iris geos shapely`

Thanks again for your help, I look forward to learning more about Iris.

**Comment by ajdawson** [comment]
>So I created a new environment just for iris and ran: conda install -c scitools iris
> Which as you know doesn't work - #1970

It don't think it is correct to claim that this command doesn't work in general, because in most cases it works fine, I'm actually quite surprised it doesn't work for you. I haven't been able to reproduce a problem with this in a newly created and activated conda environment, it seems to work OK, I'm using osx 10.11 and conda 4.1.11.

I did this:

    conda create -n iris-test1 -c scitools iris
    source activate iris-test1
    python -c "import iris; print(iris.__version__)"

It also seems OK on linux64, but I haven't tried Windows. It would be helpful if you could provide use with commands you are using the error traceback from *your* testing, in case it is slightly different than that in #1970. This way we are more likely to be able to fix whatever is wrong with the packaging that causes it not to work for you.

**Comment by dkillick** [comment]
Thanks @ajdawson - I just ran your quoted script from the above on Win64 (without the `source` command) and it works fine for me too. 

Looks like you might have got unlucky @susoson - but as @ajdawson says your error traceback will hopefully help us diagnose what's gone wrong for you. Glad installing the Iris sample data helped though!

**Comment by susoson** [comment]
Thanks all, I'm not sure what was wrong yesterday and it's not worth it for me to dig in my logs. All seems to be fine now and your scitools install runs fine today too both with an env setup from the command line and through the anaconda ui. Issues all resolved, thanks for the support!

**Comment by dkillick** [comment]
Glad it's working now @susoson! I guess even computers have off days sometimes...

If you don't mind I'll keep this issue open as I've got some work in the PR referenced above that is based off of your comments here.
