### ISSUE TITLE
Install conflicts in python 3.5 Anaconda env on Windows

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#2233]
Hi,

What is the correct way to install iris on Windows in a fresh Python 3.5 Anaconda environment?
When I try to run
```
conda install -c scitools iris
```
It says that it's incompatible with python 3.5. Is only 3.4 supported now?
When I try to install it from conda-forge channel, everything works fine until I try to launch Spyder or Anaconda Navigator, or use `matplotlib.pyplot` in a console - all due to the qt library error, which I reported here https://github.com/conda-forge/conda-forge.github.io/issues/257. That seems odd to me, because I'm only installing iris, and not matplotlib or qt from conda-forge.

**Comment by dkillick** [comment]
Hi @dennissergeev, thanks for raising this issue with us. The reason you can't install Iris into a fresh Py35 Conda env from the SciTools channel is that there currently aren't any Py35 builds of Iris for Windows in the main SciTools channel. There is, however, a Py35 build of Iris v1.10-dev0 available in the dev label in the SciTools channel. You should be able to install this using:
```bash
conda install -c scitools/label/dev iris
```
... but that's not working either (missing cartopy).

The bigger problem here is that we've been having some issues pushing the latest versions of Iris to the SciTools channel once these versions have been released, which is why there isn't a Py35 version of Iris available at the moment.

Your best bet if you need Win-64 Iris for Py35 at the moment is to use conda-forge, which brings us on to the second problem you mentioned. So that I'm clear on your situation, are you installing Iris from conda-forge and getting matplotlib from another channel? There is a chance that this is causing your problem. For example, if we mix installing Iris dependency libraries from the SciTools and conda-forge channels, we often see odd issues that I think come from the fact that the recipes and builds are not always compatible.

So, could you try installing Iris from conda-forge into a fresh env and see if things work then. Actually, having read @ocefpaf's comment on the other issue you linked above, he's quite right about why you're seeing that issue.

I'll try and finally update the SciTools channel to include the version of Iris you're after. However, it may well be that you still see the same Qt problem even then - I'm not sure where the Iris on the SciTools channel will source Qt from, if at all.

Hopefully this is of some help.

**Comment by dennissergeev** [comment]
Hi, @dkillick 
Thanks for the detailed answer. 
Sorry if I'm unclear. The problem seemed odd to me, because when iris was installed from conda-forge, neither matplotlib, nor pyqt appeared in the list of updated/newly installed packages. So they should be still in a "default" channel configuration. Why would they not work then?

Anyway, the (temporary?) solution is simply to run `conda install -c conda-forge matplotlib` after I install iris. This changes matplotlib's as well as pyqt's versions, and `pyplot` seems to work fine.

**Comment by rcomer** [comment]
Hi @dennissergeev, I’m just doing some housekeeping.  I assume your environments have moved on since opening this so will close it as it’s hopefully no longer relevant.  Obviously feel free to open a new issue if you need to.
