### ISSUE TITLE
'other' merge support

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2312]
complete refactor of merge code

**Comment by niallrobinson** [comment]
!! this sounds fun !!

@tam203 and i have been trying to knock together a tool which can force orthogonal dim coors when merging. e.g. API
`mycube = mycubelist.merge_cube(dim_coords=["latitude", "longitude", "realisation", "time"])`
If one of the cubes in the list has some time points missing, for instance, this would pad them out with masked data so that time was a valid dimension coordinate. This comes up a lot with real datasets, and is more likely to come up when loading Very Big Cubes with a dask distributed system.

We'll let you know if we come up with anything good

**Comment by marqh** [comment]
a minimal change to merge on #2369 has given us enough functionality for now, this ticket may not be required for dask work
