### ISSUE TITLE
iris.save always saves time and forecast_reference_time as 'hours since 1970-01-01 00:00:00'

### ISSUE THREAD

**Issue by naveenreddy2811** [SciTools/iris#2387]
I have below Scalar coordinates in NIMROD file
`          forecast_reference_time: 2015-12-26 00:00:00
          time: 2015-12-26 04:00:00
`
When I save it as GRIB file using `iris.save(cube, "myfile.nc")`

GRIB file has variable as below 

`    double forecast_reference_time;
      :units = "hours since 1970-01-01 00:00:00";
      :standard_name = "forecast_reference_time";
      :calendar = "standard";

    double time;
      :units = "hours since 1970-01-01 00:00:00";
      :standard_name = "time";
      :calendar = "standard";`

and values as below..

`forecast_reference_time =403080.0
time =403083.9999999963
`
Global attributes of GRIB File after save as below
`  :field_code = 58S; // short
  :nimrod_version = 2S; // short
  :num_model_levels = 1S; // short
  :source = "Best Medium-Range";
  :Conventions = "CF-1.5";`

How to convert time and forecast_reference_time as is in NIMROD file to GRIB file..

**Comment by rcomer** [comment]
Hi @naveenreddy2811, sorry to have left you without a response for so long.  I’m going to close this on the assumption that you have long since moved on and forgotten this issue.  If that’s not the case, please feel free to ask questions on our [Google Group](https://groups.google.com/g/scitools-iris), which is our dedicated place for getting help with how to use Iris.  The GitHub issues are really for requesting and planning changes in Iris, which is perhaps partly why your question was unfortunately overlooked.
