### ISSUE TITLE
Integrate DataManager with coordinates (8 man days)

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2490]

**Comment by dkillick** [comment]
A couple of gotchas to consider while integrating the DataManager.

1. Printing an `AuxCoord` realises a lazy points array. What's hard to determine is whether this is desirable behaviour or not: on the one hand, if I print a coord I want to see what its points are; but on the other hand a print operation should not affect the underlying state of the object being printed! For example: 
```python
>>> ldc = iris.coords.AuxCoord(as_lazy_data(np.array([1, 2, 3]), units='m')
>>> is_lazy_data(ldc._points)
True
>>> print ldc
AuxCoord(array([1, 2, 3]), standard_name=None, units=Unit('m'))
>>> is_lazy_data(ldc._points)
False
```
2. A `DimCoord` does not preserve a lazy points array **at all**. It seems that we have [this line](https://github.com/SciTools/iris/blob/dask/lib/iris/coords.py#L1504) to thank for this. For example:
```python
>>> dldc = iris.coords.DimCoord(as_lazy_data(np.array([1, 2, 3]), standard_name='height', units='m')
>>> is_lazy_data(dldc._points)
False
```

**Comment by pp-mo** [comment]
My views on these (for the record, already discussed offline)
> 1. Printing an AuxCoord realises a lazy points array
> ... a print operation should not affect the underlying state of the object 

I think it's acceptable.
Our whole conception of 'lazy' data is that it is transient and the "real" content of a Cube (or Coord, now) is the "real" data.  Thus, when you need the data you realise it and "the lazy" is gone, but the essential object content is _unchanged_, because that data "is" the true state of the object.
Thus, the 'lazy' aspect has to be seen as a kind-of internal concept -- even though it is not actually hidden or private.

> 2. A DimCoord does not preserve a lazy points array at all.

Given the monotonic requirement, I think this it is simply unavoidable.
We could instead load the data, make the test, throw it away + keep it lazy.
However, I'm really not in favour of that, as it is against the spirit of "touch once and it's gone" which is a nice straightforward model of the behaviour.

**Comment by dkillick** [comment]
@pp-mo some helpful views, thanks! I think we might just need to be careful about when we print coords if we need (for some reason) to maintain lazy coord data...

**Comment by dkillick** [comment]
For reference, the PR for this is #2527.

**Comment by dkillick** [comment]
This is done now that #2527 is merged!
