### ISSUE TITLE
Integrate DataManager with auxiliary coordinate factory (derived coordinates) [5 man days]

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#2495]

**Comment by dkillick** [comment]
A majority of the work detailed above is done by https://github.com/SciTools/iris/pull/2527/commits/2075f75056bb68f680fafa83d442dc582dd7effd.

**Comment by dkillick** [comment]
To update [my previous comment](https://github.com/SciTools/iris/issues/2495#issuecomment-298954745):

* we now use `coord.core_points()` to ensure we use the incoming coords' lazy points, if available.
* it looks like there was never support for lazy bounds before, however we could [add that now](https://github.com/SciTools/iris/blob/master/lib/iris/aux_factory.py#L300).
* turns out there's [more test coverage](https://github.com/SciTools/iris/tree/master/lib/iris/tests/unit/aux_factory) than I first thought, including checks for [lazy points being maintained](https://github.com/SciTools/iris/blob/dask/lib/iris/tests/unit/aux_factory/test_AuxCoordFactory.py#L65-L66).
* this was done by https://github.com/SciTools/iris/pull/2527/commits/2075f75056bb68f680fafa83d442dc582dd7effd.

**Comment by pp-mo** [comment]
I've looked over all the the files that mention factories + have changed on the dask branch.
There is no tricky usage that I can see -- the changes for dask should not cause any problems.

**Comment by dkillick** [comment]
Thanks for your input @pp-mo -- closing this in light of recent comments.
