### ISSUE TITLE
Prevent silent failures on inplace NumPy operations (3 man days' effort)

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#2575]
Newer versions of NumPy do not allow in-place math operations that change dtype. This affects Iris in-place math operations. Notably in some (ufunc) cases catch a TypeError, which is catching this error and causing the in-place operation to fail silently.

Ref #2522

**Comment by corinnebosley** [comment]
@dkillick @pp-mo So what do we intend to do about this? Make these types of operations fail loudly, cast the resulting dtype to that of the cube's data or allow the operations to change the cube data's dtype?

**Comment by corinnebosley** [comment]
I would suggest that we allow the operations to change the cube data's dtype.

My reasoning for this is that if I want to mulitply my cube's data (let's say it's integer data) by 0.5, I know damn well that 0.5 is not an integer, but I clearly want to half my data values, so I am intrinsically saying 'change my data'.

If I didn't want to change the cube's dtype, then I would not be applying a mathematical operation using a different one, and if I do then it's my own fault if the cube data's dtype changes.

**Comment by corinnebosley** [comment]
Of course, having said all this, I have no idea how difficult it will be to implement this option.

**Comment by dkillick** [comment]
@corinnebosley you hold exactly the same idealistic viewpoint to me on this. Pragmatically, however, I think we should do the opposite and follow NumPy behaviour: as NumPy no longer allows inplace operations that change type, neither should we. In fact, you can still do `int_cube = int_cube * 3.0`, which is near equivalent to `int_cube *= 3.0` (although in both cases the name actually becomes invalid :wink:).

The problem that needs addressing here is how do we distinguish between valid failures from ufuncs and incorrect failures being caused by inplace maths, which are currently incorrectly caught and fail silently?

**Comment by corinnebosley** [comment]
@dkillick I am not sure if that's the only problem that needs addressing.  A little while ago you made [this](https://github.com/SciTools/iris/pull/2458) change, which as far as I can see will cast the dtype of the result to a float in (almost?) every case.  

This would make math ops on integer cubes very difficult to achieve because of frequent failures.  Is that right?

**Comment by corinnebosley** [comment]
@dkillick I would also like you to talk me through the tests that you wrote for that PR when we are both back in the office please.  There are lots of them, and trying to understand them just by reading them is making my brain hurt.

**Comment by dkillick** [comment]
@corinnebosley the change you reference applies only to _division_. Division is an unusual mathematical case in that unless you have a numerator composed only of values that are multiples of the denominator, you have to produce a floating point result to avoid losing precision. So yes, the combination of that change and the change that's required here will mean inplace integer cube division will almost always fail. Add, subtract and multiply should be less affected, however.

**Comment by rcomer** [comment]
I've just been reading back through this and the linked issue to get my head around the problem.  There is a lot of discussion about arithmetic, but it seems that Iris is consistent with numpy when it comes to arithmetic.  The silent failure problem appears for other ufuncs such as `log`, where Iris will appear to work but have no effect:

```python
In [1]: import numpy as np                                                                                                                                    

In [2]: np.__version__                                                                                                                                        
Out[2]: '1.17.4'

In [3]: import iris                                                                                                                                           

In [4]: iris.__version__                                                                                                                                      
Out[4]: '2.4.0'

In [5]: arr = np.arange(3)                                                                                                                                    

In [6]: arr += 1.3                                                                                                                                            
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
<ipython-input-6-e239de6b8aad> in <module>
----> 1 arr += 1.3

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [7]: cube = iris.cube.Cube(arr)                                                                                                                            

In [8]: cube += 1.3                                                                                                                                           
---------------------------------------------------------------------------
ArithmeticError                           Traceback (most recent call last)
<snip>
ArithmeticError: Cannot perform inplace addition between <iris 'Cube' of unknown / (unknown) (-- : 3)> with int64 data and 1.3 with float16 data.

In [9]: np.log(arr, out=arr)                                                                                                                                  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-b64140e0975e> in <module>
----> 1 np.log(arr, out=arr)

TypeError: ufunc 'log' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [10]: iris.analysis.maths.log(cube, in_place=True)                                                                                                         
[site-packages-path]/iris/analysis/maths.py:842: RuntimeWarning: divide by zero encountered in log
  operation_function(cube.data)
Out[10]: <iris 'Cube' of unknown / (unknown) (-- : 3)>

In [11]: cube.data                                                                                                                                            
Out[11]: array([0, 1, 2])

```
If I've understood, this is because we use a `try-except` loop to check whether the function takes the `out` keyword:
https://github.com/SciTools/iris/blob/c2a834f652efab5660500098b461906cf3423388/lib/iris/analysis/maths.py#L914-L918
