### ISSUE TITLE
Discrepancy between merge and concatenate with respect to dtype of coordinates

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2591]
Iris will successfully combine cubes with coordinates whose only differing meta-data is the dtype when using merge, but not when using concatenate. The behaviour should probably be consistent between the two methods.

**Comment by corinnebosley** [comment]
Agreed.  I would say concatenate should also accept cubes with differing dtype only, rather than merge restricting its rules.

**Comment by PAGWatson** [comment]
I just spent quite a long time figuring out why two cubes would not concatenate before realising it was because the time coordinate dtypes were different, so I second the suggestion to allow concatenation of cubes where only the coordinate dtype differs, since I can't think of how that would lead to a serious error.
