### ISSUE TITLE
Decide on the pre-release candidate name

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris#2594]
As this is a pre-release version, I would plump for 'Iris v2.0a' (the alpha version) as described here:
https://www.python.org/dev/peps/pep-0440/#pre-releases

However, this may be a little misleading.  We may need to make it more obvious that this is not the final release candidate or even the final v2 release.

On this basis, it may be more appropriate to call it 'Iris v2.0dev'

**Comment by corinnebosley** [comment]
@bjlittle I have just had a look a bit further down the page, and found that for developmental releases you can actually much both of the above options together, so we could call it 'Iris v2.0a.dev'.

What do you think about that?

**Comment by pp-mo** [comment]
Our internal Scientific Software Stack solution makes the repo tag a significant thing.
We definitely want to ***only*** use version strings that conda properly understands, in terms of how it views the sequencing of releases.
So, recently we have limited ourselves to release-candidate version strings, to ensure it is treated correctly, i.e. X.Y.nnn < X.Y+1.0rc1 < X.Y+1.0rc2 < X.Y+2.0
( We "could" use a release tag different from the `iris.__version__` string, but I think that would be unnecessarily confusing. )

(
Aside? :
In the past we used two styles, as PEP440 and SemVer don't agree
E.G. we had
 * "v1.7.3-rc.1" (SemVer style), *but then*
 * "v1.7.4rc1" (PEP440 style)
Since 1.7.4 we have stuck to PEP440.
)

**Comment by bjlittle** [comment]
I've done some digging on this and found the following useful https://github.com/conda/conda/pull/1601 PR.

But I also found that you can easily get to the `conda` version ordering, which is very handy:
```python
>>> from conda.version import VersionOrder
>>> VersionOrder('2.0.0rc0') < VersionOrder('2.0.0')
True
```
So given `PEP440` **and** `conda`, let's establish some truths ...

----

For a `PEP440` [development release](https://www.python.org/dev/peps/pep-0440/#developmental-releases) it states the use of a `.devN`. Let's see what that means in `conda`:
```python
# conda understands normalization rules ...
>>> VersionOrder('2.0.dev') == VersionOrder('2.0.dev0')
True
```
I'd advocate that we are **always** explicit i.e. use `.dev0` instead of `.dev`

```python
>>> VersionOrder('2.0.dev0') == VersionOrder('2.0.0dev0')
True
```

The use of `2.0.0dev0` isn't `PEP440`, but it's interesting that to `conda` there is the addition of an implicit `micro` version (as in `major.minor.micro`).

I'd advocate that we use `2.0.dev0` for the `master` branch. So after a release, the `master` would increment to `2.1.dev0`, and after another release onto increment to `2.2.dev0` etc. This implies that the `micro` version on `master` is always `0`, which is true.

The `master` branch is not concerned with increments of the `micro` version, that is managed on the release branches i.e. `v1.13.x` or `v2.0.x` etc

----

For a release branch, say `v2.0.x`, we are releasing `2.0.0` and all its associated `micro` increments for bug fixes. This would mean that `master` has been incremented to `2.1.dev0`

When `2.0.0` is released, on the release branch `v2.0.x` the version increments to `2.0.dev1`. And when `2.0.1` is released the version increments to `2.0.dev2`.

So we have,
```python
>>> VersionOrder('2.0.0') < VersionOrder('2.0.1')
True
>>> 
>>> VersionOrder('2.0.dev1') < VersionOrder('2.0.dev2')
True
```

It's important to note that, `conda` should **never** see `dev` versions! We only really care about *published* versions of `iris` when it comes to version ordering.

Therefore, when `2.0.1` is released, we would then have:

```python
>>> VersionOrder('2.0.0') < VersionOrder('2.0.1') < VersionOrder('2.1.dev0')
True
```

----

For a `PEP440` [pre-release](https://www.python.org/dev/peps/pep-0440/#pre-releases) it states the use of `aN`, `bN` and `rcN` for *alpha*, *beta* and *release candidate* releases.

So we have
```python
>>> VersionOrder('2.0.0a0') < VersionOrder('2.0.0b0') < VersionOrder('2.0.0rc0') < VersionOrder('2.0.0')
True
```
Note that, again
```python
# conda understands normalization rules ...
>>> VersionOrder('2.0.0a') == VersionOrder('2.0.0a0')
True
```
Again, I'd advocate that we remain explict, and in this particular case use `2.0.0a0`.

Also, note that,
```python
>>> VersionOrder('2.0.0a0') < VersionOrder('2.0.0a1') < VersionOrder('2.0.0b0') < VersionOrder('2.0.0rc0') < VersionOrder('2.0.0')
True
>>> 
```
So incrementing the pre-release alpha, beta or release candidate versions behaves as expected.

----

As @pp-mo mentioned, on `master` we currently have `2.0.0-DEV` and this currently gets normalized to `2.0.0.dev0`
```python
> python setup.py build
<snip>/dist.py:364: UserWarning: Normalizing '2.0.0-DEV' to '2.0.0.dev0'
```

Which suggests to me that we need to drop our reliance on normalization rules.

**Comment by bjlittle** [comment]
So after that long rant, with regards to this issue, I'm suggesting that we use `2.0.0a0` for the pre-release candidate. This should behave well with regards to `conda` and any further `PEP440` compliant version releases, as stated above.

**Comment by bjlittle** [comment]
Of course, note that if we do put out a pre-release alpha
```python
>>> VersionOrder('1.13.0') < VersionOrder('2.0.0a0')
True
```
Then "the next version up" alpha will always trump all previous final releases ... just wanted to make that explicit, so `2.0.0a0` will default over `1.13.*`.

**Comment by bjlittle** [comment]
Also, since my head is clearly in this space ... it make sense to me that all pre-releases are only for `major` or `minor` releases, not `micro`.

So I'd advocate that it's sensible to have `1.13.0a0` (not `1.13a0`, let's keep it explicit), and `1.14.0a0`, and `2.0.0a0` ... and **never** `1.13.1a0` nor `1.14.3a0` etc

Pre-releases are only sensible for `major.minor.0` versions.

**Comment by bjlittle** [comment]
Apologies, can't stop myself ... also, I think that we want the flexibility to cut a pre-release that's not necessarily associated with a release branch i.e. we can tag a `2.0.0a0` release without having an existing `v2.0.x` release branch, so the tag is on `master` commit or indeed a commit "somewhere" else ... I haven't quite thought that completely through, but there seems to be utility in having such flexibility.

**Comment by bjlittle** [comment]
@SciTools/iris-devs I'm keen to have an agreement in principle for the above proposed management of release versions.

Once we have some consensus, I'll then formalise the proposal by updating our [`developers_guide/release.rst`](http://scitools.org.uk/iris/docs/latest/developers_guide/release.html) and [`whitepapers/change_management.rst`](http://scitools.org.uk/iris/docs/latest/whitepapers/change_management.html) appropriately. Thanks!

**Comment by QuLogic** [comment]
> The use of 2.0.0dev0 isn't PEP440, but it's interesting that to conda there is the addition of an implicit micro version (as in major.minor.micro).

It is part of PEP440 which does not prescribe a specific number of components, but does explain the expansion when comparing versions with a different number of components; see the note near the end of [this section](https://www.python.org/dev/peps/pep-0440/#final-releases).

> When 2.0.0 is released, on the release branch v2.0.x the version increments to 2.0.dev1. And when 2.0.1 is released the version increments to 2.0.dev2. This implies that the release branch v2.0.x was originally cut from the master branch when it was at 2.0.dev0.

`2.0dev1` == `2.0.0dev1` < `2.0.0`, so this does not work the way you say:
```python
>>> VersionOrder('2.0.0') < VersionOrder('2.0.dev1')
False
>>> VersionOrder('2.0.1') < VersionOrder('2.0.dev2')
False
```
The version for a release branch should be `v2.0.xdev0` where x=(last release's micro + 1).

I think I saw someone mention that `2.0.0a0` might be confusing; note that you [can spell out the full word](https://www.python.org/dev/peps/pep-0440/#pre-release-spelling) to make it `2.0.0alpha0`. Unfortunately, conda does not normalize this correctly, but at least it remains in the correct order wrt betas:

```python
>>> VersionOrder('2.0a0') < VersionOrder('2.0.0alpha0') < VersionOrder('2.0.0b0') < VersionOrder('2.0.0beta0') < VersionOrder('2.0.0c0')
True
# This is what is should be if normalized correctly:
>>> VersionOrder('2.0a0') == VersionOrder('2.0.0alpha0') < VersionOrder('2.0.0b0') == VersionOrder('2.0.0beta0') < VersionOrder('2.0.0c0') 
False
```

**Comment by QuLogic** [comment]
> Unfortunately, conda does not normalize this correctly, but at least it remains in the correct order wrt betas:

Actually, looking at the conda ticket that @bjlittle linked above, it appears that they are aware of this difference and say "be consistent in how you version things; always use alpha+beta or always use a+b, but not both".

**Comment by bjlittle** [comment]
> It's important to note that, conda should never see dev versions!

@QuLogic I did mention that `conda` shouldn't see `.devN` versions for this **very** reason. `conda` should only see *published* versions. I think it's a minor point of distraction that doesn't add to the work flow that I'm suggesting above - there should never be a `conda` recipe with a version that contains a `.devN`. I don't see that as a problem. The important point is that within `iris` **we** would infer that, for example, after `2.0.0` is released, then I'm proposing that `2.0.dev1` is the next version on the release branch - even though according to `conda` that doesn't comply with it's interpretation of ordering - but IMO we don't need to concern ourselves *how* `conda` has decided to perform that ordering simply because there should never be a `2.0.dev1` version in `conda` circulation.

**Comment by bjlittle** [comment]
@QuLogic From a tool perspective, my feeling is that `a` is better than `alpha`, `b` is better than `beta`, and `rc` is better than `c` ... I don't think that it should come as a great surprise as to their meaning, but we should ensure to clearly communicate their meaning to the user community.

**Comment by marqh** [comment]
as well as being mindful of conda ordering, we need to be mindful of RPM ordering

I think in both cases

`2.0.0 > 2.0.0a > 2.0.0rc1`  

this would put `a`, the alpha, up in preference to the `rc1`  which seems wrong to me

**Comment by bjlittle** [comment]
@marqh I don't think that there is a single, sensible form of version naming that results in the same ordering given different packaging methods i.e. `conda` vs `rpms` vs whatever ... if there is, then I'd love to know that :+1: 

With regards to `rpms`, a simple compromise may require to be taken, akin to [Python Pulp](http://docs.pulpproject.org/en/2.9/nightly/dev-guide/policies/versioning.html#rpm-package-version) module.

**Comment by bjlittle** [comment]
If we think it's sensible to only restrict ourselves to alpha, beta and release candidates on `minor` releases, then we have
```python
>>> VersionOrder('2.0a0') < VersionOrder('2.0b0') < VersionOrder('2.0rc0') < VersionOrder('2.0.0')
```
rather than
```python
>>> VersionOrder('2.0.0a0') < VersionOrder('2.0.0b0') < VersionOrder('2.0.0rc0') < VersionOrder('2.0.0')
```

**Comment by pelson** [comment]
@bjlittle - go for ```2.0.0a0``` unless there is a compelling reason for something else - it is the most similar to PEP440 whilst preserving some degree of SemVer. Ultimately though, I'm open to anything that gives a hint that we are a long way from putting a feature freeze on 2.0.

**Comment by lbdreyer** [comment]
It sounds like the plan has changed to `2.0a0` since we'd never do an alpha release/beta release/release candidate of a micro release
