### ISSUE TITLE
cube.transpose is an in-place operation

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#2615]
I think it's pretty nasty and unexpected to have cube.transpose() modify in-place
That is, especially, as it seems to mimic numpy "transpose", which is **_not_** in-place.
Plus, we just don't have many in-place operations, largely by design (I think).

Thus in #2604 ... 
 * I had a test cube and a sample result array which should match a derived coordinate.
 * I applied transpose operations to both, but the cube behaves differently to the result, when it should have been the same.

I think we should review this as it's peculiar and unexpected, and breaks the general simlilarity with numpy.
Arguably the numpy function could more clearly be named "transposed" (a la Python "sorted").
Obviously, that ship has sailed, but we *could* use that naming for a cube method.

Propose: 
 * provide copying version called "cube.transposed()" instead
 * deprecating the existing "cube.transpose" -- or simply **_remove it from Iris 2.0 ??_**

**Comment by cpelley** [comment]
+1 for cube.transpose returning a cube, however it is important to us that it does not consume any more memory for the data or coordinates i.e. the cube returned should be a view of the original cube.  This would also be in keeping with ndarray.transpose behaviour.  Not sure where transposed comes into this as numpy uses transpose.

**Comment by pelson** [comment]
Taking this out of the v2.0.0 milestone - we aren't going to hit this in time, but can very readily add this as a future flag during the v2.x series. Of course, we will need to figure out data sharing before we can do this though (again, not going to happen for v2.0.0).

**Comment by monishanatchiar** [comment]
I agree that in-place operations need to be reduced, or we should at least have an option like `in_place=False`. Currently, I have to create a copy of the iris.cube.Cube to not transpose it in-place.

**Comment by cpelley** [comment]
I appreciate numpy is not consistent itself here but 'typically' method calls are in-place and calling an operation via function call would return a copy (`numpy.ndarray.transpose` method call actually returns a view... rather than internally transposing a view on the object itself i.e. ~in-place).

i.e. anyway, so for iris what about:

## return copy
```
iris.transpose(cube, ...)
```

## in-place transpose of cube
```
cube.transpose(...)
```

> ...we should at least have an option like `in_place=False`...

Numpy makes use of the optional `out=None` parameter for this purpose and is more flexible:
e.g., see [cumsum](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html#numpy.cumsum)

I think a contract is required on the UI.  Ideally consistency, predictability AND flexibility.

Cheers

**Comment by trexfeathers** [comment]
Xref #5007
