### ISSUE TITLE
Add ability to name dimensions without forcing to write a coordinate variable to the netCDF file

### ISSUE THREAD

**Issue by jvegasbsc** [SciTools/iris#2626]
Currently, in order to be able to name a dimension and avoid it to be saved as dimX in netCDF files it is required add a dimension coordinate. This had the side-effect of also writing a coordinate variable, which sometimes is not required: here is an extract of CF-conventions  talking about some cases in which this is not necessary:

http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#discrete-axis

Maybe it will possible to add a property to the DimCoord class to control if the coordinate variable must be written?

Thanks,
Javi

**Comment by marqh** [comment]
hello @jvegasbsc 

as you observe, iris does not name dimensions, dimension names are treated as part of a netCDF encoding only.

This makes it tricky to add dimension names to individual cubes or components to enable netCDF saving.
Part of the reason for this is to ensure that there are no dimension name conflicts when multiple cubes are written to netCDF.

you can see in the netcdf code
https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/netcdf.py#L2060

that you can call teh Saver directly, rather than using iris.save

https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/netcdf.py#L753

perhaps a different way to approach this, and other encoding challenges, might be to enable an `iris.fileformats.netcdf.Saver` instance to be initialised with a ready to go
`netCDF4.Dataset`
rather than always creating a clean one
https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/netcdf.py#L799

this might add flexible configuration options for a file for this and numerous other cases

it makes for slightly more complicated user code, I think, but offers many options

what do you think?

**Comment by pelson** [comment]
Iris explicitly binds the dimension naming with a "dimension coordinate". The Iris data model doesn't have any other concept, and it is necessary to create a coordinate in order to represent it.

Honestly, I'm not sure there is anything that we want to do here. I'd need to see a compelling use case for wanting to write a CF compliant NetCDF file *without* coordinate values.
