### ISSUE TITLE
DimCoord Points and Bounds arrays no longer protected from external modification

### ISSUE THREAD

**Issue by djkirkham** [SciTools/iris#2635]
It used to be the case that when assigning points or bounds on a DimCoord, a copy was always made of the data passed in. This is no longer the case, and in fact there are tests asserting that the array data should be shared.

A lot of care is taken in the DimCoord code to ensure that the points are read only, so I assume it was a conscious design decision not to share the data (the AuxCoord data _is_ shared). Whether or not this was the right decision, I'm concerned that we've abandoned the principle without any discussion.

**Comment by pp-mo** [comment]
I did this, in the context of [unifying array storage between cube and coords](https://github.com/SciTools/iris/pull/2519).
I felt that the previous "always copy" approach was now "*simply a mistake*" since we were carefully avoiding doing that with cube data.
It made sense for me that, when we added support for lazy coords, we were accepting that coordinate data arrays are **not** always trivially small, in which case blanket copying is clearly undesirable. 
E.G. in [this comment](https://github.com/SciTools/iris/pull/2519#discussion_r114524977):
 > "... our __init__ codes, and data assignment methods, are all taking the view that a Coord or Cube "owns" it's data (aka, they don't copy it)"

We also introduced new tests to explicitly test the behaviour:
 * [iris.tests.unit.coords.CoordTestMixin.assertArraysShareData](https://github.com/SciTools/iris/blob/master/lib/iris/tests/unit/coords/__init__.py#L104)
 * uses of that in [iris.tests.unit.coords.test_DimCoord](https://github.com/SciTools/iris/blob/master/lib/iris/tests/unit/coords/test_DimCoord.py) and [test_AuxCoord.py](https://github.com/SciTools/iris/blob/master/lib/iris/tests/unit/coords/test_AuxCoord.py)

**Comment by djkirkham** [comment]
For me, the thing that distinguishes DimCoords is that they have the monotonicity constraint, so I don't think the fact that we avoid copying elsewhere is necessarily relevant.

We don't allow lazy DimCoord data, since we have to check monotonicity, and since DimCoords are always 1D I would expect that making a copy wouldn't cause much of a memory hit.

**Comment by pelson** [comment]
Was this closed by #2812 @djkirkham?

**Comment by djkirkham** [comment]
Yes.
