### ISSUE TITLE
Fix test failures where it was expecting a masked array but it's not

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#2714]
AssertionError: True != False
- [x] FAIL: test_grid_complex_spatial_differencing (iris.tests.integration.test_grib2.TestDRT3)

AttributeError: 'numpy.ndarray' object has no attribute 'mask'
- [x] ERROR: test_cube_mask (iris.tests.integration.test_ff.TestLBC)

AssertionError: 77.763431447349674 is not masked
- [x] FAIL: test_gdt90_with_bitmap (iris.tests.integration.test_grib2.TestImport)

expect masked array but get a nan array
- [x] FAIL: test_circular_grid (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____circular)
- [x] FAIL: test_non_circular (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____circular)
- [x] FAIL: test_grid_no_overlap (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____rotated_to_lat_lon)
- [x] FAIL: test_grid_partial_overlap (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____rotated_to_lat_lon)
- [x] FAIL: test_grid_subset_missing_data_aux (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____rotated_to_lat_lon)
- [x] FAIL: test_masked_field (iris.tests.test_cdm.TestMaskedData)
- [x] FAIL: test_missing_file (iris.tests.test_cdm.TestMaskedData)
- [x] FAIL: test_slicing (iris.tests.test_cdm.TestMaskedData)
- [x] FAIL: test_rle (iris.tests.test_pp_module.TestPackedPP)

**Comment by djkirkham** [comment]
The following tests are fixed by https://github.com/SciTools/iris/pull/2760:

 FAIL: test_circular_grid (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____circular)
FAIL: test_non_circular (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____circular)
FAIL: test_grid_no_overlap (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____rotated_to_lat_lon)
FAIL: test_grid_partial_overlap (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____rotated_to_lat_lon)
FAIL: test_grid_subset_missing_data_aux (iris.tests.unit.analysis.regrid.test_RectilinearRegridder.Test___call____rotated_to_lat_lon)

The remaining test

ERROR: test_cube_mask (iris.tests.integration.test_ff.TestLBC

Uses PP code and may be fixed by https://github.com/SciTools/iris/pull/2744. I will wait for that PR to be merged before investigating further.

**Comment by pp-mo** [comment]
As-of https://github.com/SciTools/iris/commit/d8acaefdf03ad7c071abd5532d14a8f726a3489d
Only  `test_cube_mask (iris.tests.integration.test_ff.TestLBC)` remains to fix here.

**Comment by djkirkham** [comment]
Closed by #2809
