### ISSUE TITLE
Question on Lanczos filter

### ISSUE THREAD

**Issue by CommonClimate** [SciTools/iris#2764]
Hi,
[this example](http://scitools.org.uk/iris/docs/v1.2/examples/graphics/SOI_filtering.html) illustrates how to use Lanczos filters, but raises two questions (not bugs - I just did not know how else to reach out):

1.  How is the window size chosen? Shouldn't it depend on the cutoff frequency in some way?
2. Is this filter zero-phase? 

Thank you

**Comment by ajdawson** [comment]
This is an example of using the rolling window rather than an exploration of filters, and here is not really the appropriate place for the detailed discussion of scientific methods.

However, I can tell you the window size does not determine the cutoff in the case of the Lanczos filter in the example. For more details on why this is the case consult the first paper referenced in the example.

**Comment by CommonClimate** [comment]
Thanks. Understood
