### ISSUE TITLE
cube.data.set_fill_value no longer works?

### ISSUE THREAD

**Issue by cpelley** [SciTools/iris#2773]
This seems too obvious not to be picked up in one of the many tests so I'm suspicious.
Can someone confirm they get the same behaviour?

```Python
>>> import iris
>>> import numpy as np
>>> cube = iris.cube.Cube(np.ma.array([1, 2, 3, 4], mask=False))
>>> cube.data.set_fill_value(10)
>>> print cube.data.fill_value
9999
```
The fill value does change to 10 when using iris v1.13

**Comment by cpelley** [comment]
I'll put this on the v2.0 milestone as if confirmed, this seems pretty serious to me.

**Comment by pp-mo** [comment]
I *think* in Iris "2.0a0", the only correct way to do this was in fact "cube.fill_value = ..."

Since Dask is now supporting masked arrays after all,
we are moving on from the whole masking-by-NaNs approach.
(https://github.com/dask/dask/pull/2301)

So we now have work-in-progress to *UNdo* a lot of the changes between Iris 1.13 and 2.0a0.
https://github.com/SciTools/iris/projects/18
https://github.com/SciTools/iris/tree/dask_mask_array

It's a long way along, and the result should be a "proper" Iris 2.0rc, hopefully within a few weeks.
As a very brief summary:
changes retained:
 * lazy/real data will be handled with common code in a "DataManager" object
 * cube and coord handling of lazy+real data will still be rationalised
lost:
 * interconversion and confusion of NaNs and masking will not occur
 * cube.fill_value will be removed, and all the special fill-value handling it implied

**Comment by cpelley** [comment]
Thanks for your comment @pp-mo.  Does this mean that the behaviour in the example above will match that from iris v1.13 in iris 2.0rc?

Cheers

**Comment by pp-mo** [comment]
> the behaviour in the example above will match that from iris v1.13 in iris 2.0rc

More-or-less, yes, that is the intention.  

However we are also reviewing other aspects of the existing loading, which will change behaviour.

The current intention is to simplify handling of fill-values generally, so things will change.
For example, some of the current intentions (not all yet finalised) are ... :
  * masked data from UM files will not have a numpy fill-value derived from the field BMDI ...
    * ... as handling of fill-value in calculations is so flaky anyway
  * iris.save of masked data will not use numpy fill-values ***at all***, as they are often wrong ...
    * ... instead format-specific default values will be used
    * ... **or** you may supply an explicit fill_value keyword to the save call
  * netcdf saves will only attach a _FillValue attribute when masked data has a non-default fill-value
    (which will now be less common)

**Comment by cpelley** [comment]
Thanks for the reply @pp-mo and really interesting about the other ways in which behaviour with fill value will change.  Sounds like a lot of good stuff!  I'll have a think about this.

I'll close this ticket.

Thanks again.  Appreciate your input.

**Comment by pp-mo** [comment]
P.S. I missed a **really key point** here...

In the "new regime" we *will* still have a cube._data_manager, and "cube.data" will be a *view*.
Thus, in principle, the "cube.data.set_fill_value" should not work.
However, but I found that it *does* still work,  because of a truly awful numpy bug !!

For example ...
```
>>> a = np.ma.masked_array([1,2])
>>> a.fill_value
999999
>>> b = a.copy()
>>> b.set_fill_value(777)
>>> b.fill_value
777
>>> a.fill_value
777
>>> 
```

So, even an array ***copy*** does not have a distinct fill-value, which seems to me to be a plain horrible bug,  which I think goes back at least as far as numpy 1.9.

Though ghastly, it "solves" your compatibility problem, at least until this is fixed in numpy (!)

**Comment by cpelley** [comment]
> In the "new regime" we will still have a cube._data_manager, and "cube.data" will be a view.
Thus, in principle, the "cube.data.set_fill_value" should not work.

Thanks for your comment @pp-mo.  Ah OK.  Is it obvious that this should **not** work because it is a view?

In your example you copy the array so yes I agree that specific example demonstrates a bug, but that's different to the cube.data case no? (you say it's a view)

Is there an issue open on the github numpy on this bug?

**Comment by pelson** [comment]
@pp-mo - you need to ensure this is reported on the numpy issue tracker. You might also be interested in taking a shot at fixing it (after opening the issue!).

**Comment by djkirkham** [comment]
In the latest code `DataManager.data` returns the actual array, not a view, so this issue can be closed. I've put up a PR with new tests to prevent it happening again though (https://github.com/SciTools/iris/pull/2842).

**Comment by cpelley** [comment]
Thanks everyone for your engagement on this ticket, appreciated.

**Comment by pp-mo** [comment]
> need to ensure this is reported on the numpy issue tracker. 

already reported as an issue, here : https://github.com/numpy/numpy/issues/7329
