### ISSUE TITLE
Unable to concatenate cubes when the units of the time coordinate differ

### ISSUE THREAD

**Issue by ehogan** [SciTools/iris#2923]
Hello,

I've just discovered that Iris raises:
```
ConcatenateError: failed to concatenate into a single cube.
  Dimension coordinates metadata differ: time != time
```
when attempting to concatenate cubes that differ only by the units of the time coordinate, e.g. `days since 1850-01-01 00:00:00`.

Would you consider this to be a bug? When the points of the time coordinate are determined by applying the units, it's clear that they are contiguous, so shouldn't the cube concatenate in this case?

(We are dealing with this issue within our code, so there's no rush for a response, I just thought I'd start the conversation) :)

**Comment by dkillick** [comment]
Hi @ehogan, thanks for raising this. This is deliberate, reasoned behaviour (I should know; I implemented it!), which is done because the coordinate metadata is not identical. It would be much harder to get Iris to work out that the two coordinates are actually contiguous once the units have been taken into account, and would actually require converting the units of the time coordinate to ensure the concatenation could go ahead (to make sure that the underlying *values* really are contiguous, rather than being implicitly contiguous once the unit is accounted for).

That said, the solution for this is just to unify the cubes' time units, and there's a [suchly-named function](http://scitools.org.uk/iris/docs/latest/iris/iris/util.html?highlight=unify#iris.util.unify_time_units) provided in Iris for precisely this situation, which will fix this situation for you.

**Comment by ehogan** [comment]
> That said, the solution for this is just to unify the cubes' time units, and there's a suchly-named function provided in Iris for precisely this situation, which will fix this situation for you.

That's better than my solution; thanks! :D
