### ISSUE TITLE
README on PyPI not rendered

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#3055]
The new README is not being rendered on PyPI, so we're getting the mixed raw html/markdown shown instead. See https://pypi.org/project/scitools-iris/.

**Comment by ajdawson** [comment]
There are some requirements on the versions of setuptools and twine used to upload the sdist described [here](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi). Perhaps that is part of the problem, since it looks like the required metadata `long_description_content_type` is present in `setup.py`.
