### ISSUE TITLE
PP save fails with bounded `model_level_number` coordinate

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris#3083]
If you save to PP with a `model_level_number` coordinate present that includes bounds, the PP saver code fails. This can be easily reproduced by collapsing the `model_level_number` coordinate in a cube:

```python
cube = iris.load_cube(iris.sample_data_path('uk_hires.pp'), 'air_potential_temperature')
no_vertical = cube.collapsed('model_level_number', iris.analysis.MEAN)
print(no_vertical.coord('model_level_number').bounds)
[[ 1 19]]

iris.save(no_vertical, 'test.pp')
ValueError                                Traceback (most recent call last)
...
/.../iris/lib/iris/fileformats/pp_save_rules.py in _vertical_rules(cube, pp)
    656     # Single depth level (non cross-section).
    657     if (mln_coord is not None and
--> 658             not mln_coord.bounds and
    659             depth_coord is not None and
    660             not depth_coord.bounds):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The problem code is [this logical test](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp_save_rules.py#L657-L660) in the PP save rules. Looks like the bounds test is not set up to correctly handle arrays.

**Comment by pp-mo** [comment]
I just looked into this.
Obviously it is a bug, simply because `if(coord.bounds)` is not a safe thing to do, given the slightly peculiar behaviour of arrays in boolean tests.

On the other hand, if we fix that bug, that ***won't*** make it possible to save this data with its vertical coordinate information :   The *intent* of this code (which is inherited unchanged from the old text-base save rules, in #2795 ), is to check  "if mln_coord is not None and mln_coord.bounds is None".
So if the model-level-number coord is bounded,  the rule won't trigger, and it won't save any other level info (sigma or level-pressure) either.

The point is, in UM file formats (PP/FF) ***there is no defined way*** to encode data that represents a statistic over a set of levels -- unlike over time periods. 
We could perhaps stretch a point and save the upper+lower vertical bounds of the sigma and level-pressure, but leave mln = 0.  But even that is not actually allowed for in the F3 document : there is no standard way of encoding what this data actually is.

So the bottom line is, if you want to save this you need to 'pretend' that it is something else.
In this case, it will mean setting mln-bounds to None anyway, I think.

**Comment by pp-mo** [comment]
Given that the fix won't address the original reported problem, I don't think this is a priority for the bugfix release, and I'm going to skip it for now (remove from 2.2.1 release milestone).
