### ISSUE TITLE
Installin Iris via Pycharm

### ISSUE THREAD

**Issue by steffenb9191** [SciTools/iris#3091]
I am new to Python and I would like to install Iris via Pycharm packages in Python 3.6
and Pycharm tells me to install Pyke, which isn't possible via Pycharm. It was possible via Terminal,
but the Pycharm Interpreter can't find it.

pip install scitools-iris

ModuleNotFoundError: No module named 'pyke'

pip install pyke

Collecting pyke

  Could not find a version that satisfies the requirement pyke (from versions: )
No matching distribution found for pyke

Thanks for any help

**Comment by dkillick** [comment]
Hi @steffenb9191, thanks for getting in touch! 

It's more common these days to use [conda](https://conda.io/docs/) for installing Python libraries, particularly when getting dependencies right is tricky! You can also use conda to set up multiple Python environments, similar to virtualenv, so that you do not end up with a Python install containing lots and lots of libraries. The other benefit of using conda is that it integrates very well with Pycharm.

You can download miniconda (a lightweight installer containing basically just the conda application) here: https://conda.io/miniconda.html. Then you can install Iris from [conda-forge](https://conda-forge.org/) into an environment called "iris-env" with the following terminal command:
```bash
conda create -n iris-env -c conda-forge iris
```
This will work in Windows, macOS and Linux.

Alternatively, you can follow [this Pycharm guide](https://www.jetbrains.com/help/idea/conda-support-creating-conda-virtual-environment.html) for creating a new conda env. What it omits is how you install packages into the new env you create... I think the following will get you Iris installed using the Pycharm GUI, once you've set up your new conda env: 

* in the settings dialog you should see the list of packages in the conda env you just created. At the bottom of the list area is a '+' button - click that to open the Available Packages dialog
* then click the 'Manage Resources' button at the bottom of the dialog.
* In there, click it's '+' button and add a new repository URL of `https://conda.anaconda.org/conda-forge`. 
* Click OK, then search for Iris. You want to install the top option (despite what the description says, that **will** install this Iris - think Pycharm has got confused in its labelling - turns out that 'Iris' is a really popular name for Python packages!).

Hope this helps. Sorry it doesn't directly answer your question about pip, but I've not used pip so much recently as conda is much easier!

**Comment by steffenb9191** [comment]
Thank you for replying so fast. Sorry for not mentioning it earlier, I am already using Anaconda and the Project Interpreter is from conda.

**Comment by jamesp** [comment]
Closing for now, @steffenb9191 please let us know if you're still facing issues installing iris
