### ISSUE TITLE
Iris not working with Dask 0.18.2

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#3125]
Iris master does not work with dask 0.18.2 (but does seem to work with 0.18.1)

I suspect this is why some of the travis tests are failing.

When loading a netcdf file, it fills in the mask. 
With Dask 0.18.2
```
>>> cube = iris.load_cube('my_cube.nc')
>>> cube[0,0].data
array([[9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36,
        9.96921e+36, 9.96921e+36],
       [9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36,
        9.96921e+36, 9.96921e+36],
       [9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36,
        9.96921e+36, 9.96921e+36],
       ...,
       [9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36,
        9.96921e+36, 9.96921e+36],
       [9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36,
        9.96921e+36, 9.96921e+36],
       [9.96921e+36, 9.96921e+36, 9.96921e+36, ..., 9.96921e+36,
        9.96921e+36, 9.96921e+36]], dtype=float32)
```

But with dask 0.18.1 this is:
```
>>> cube = iris.load_cube('my_cube.nc')
>>> cube[0,0].data
masked_array(
  data=[[--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        ...,
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --]],
  mask=[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],
  fill_value=9.96921e+36,
  dtype=float32)
```

**Comment by pp-mo** [comment]
Trying to address this  -- for the 2d_coords branch --  in #3127 

Note that this is also seems to be uncovering a few other glitches that have crept in, presumable just since the tests starting failing.  Some of that may be relevant to master ?

**Comment by pp-mo** [comment]
Think I found it : see https://github.com/dask/dask/issues/3848

**Comment by pp-mo** [comment]
> It seems like quantum mechanics, just observing the object, forces it into a certain state!

This is not dask behaviour, it is intentional Iris-specific behviour.
In Iris, touching a cube's data replaces the lazy array with a real one, i.e. it caches the actual data when it is fetched once, which dask never does.
We say that it 'realises' the cube : 
quote "In Iris, when actual data values are needed from a lazy data array, it is ‘realised’ : this means that all the actual values are read in from the file, and a ‘real’ (i.e. numpy) array replaces the lazy array within the Iris object.", from [userguide section "Real and Lazy Data"](https://scitools.org.uk/iris/docs/latest/userguide/real_and_lazy_data.html)

The question in your case is more "why does this preserve the mask" ?
I guess it is because the original cube lazy content (i.e. the loader dask array) loads correctly with the mask, but some derived (still lazy) version is hitting that dask-18.2-specific bug which loses the mask.
And by "derived", I mean it could be as simple as a straight copy of the cube, as it the dask copy operation that has the bug.

To fix it will be a different Iris, or a different Dask (!)
  * currently fixed in Iris master by [pinning dask to 0.18.1](https://github.com/SciTools/iris/commit/163e95854321e5ee82767693d17bd9e6e6adc869), but that fix is not yet in any release (and in fact will probably be gone again by the time of next release)
  * since also [fixed in dask](https://github.com/dask/dask/pull/3852) : that is now available in dask 0.19

**Comment by bascrezee** [comment]
Many thanks for the clear explanation. Upgrading dask indeed fixed the issue for my example.

**Comment by dkillick** [comment]
Given that [Iris now works with dask 0.19.2](https://github.com/SciTools/iris/pull/3185), I think we can safely close this issue!
