### ISSUE TITLE
Add relative tolerance to 2d contiguity checking

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#3142]
So far we have only added absolute tolerance contiguity checking

https://github.com/SciTools/iris/compare/2d_coords#diff-fae2e3bb7827f6df8671256d1c779951R146

**Comment by pp-mo** [comment]
A problem because the code as-is assumes the values are in a 'sensible' range, so we can just use atol=0.01 or somesuch.
But the plot code will not *always* be dealing with angles at all (radians or degrees).  So for example, if your coord points were in values of e.g. 100 million, this tolerance would be too small + lead to failures ...

A _general_ approach is hard to achieve, because we only have a few sample coord values to work with, and we don't know the sensible range of possibilities they 'come from'.
We can use the range of the values we are given, and/or the maximum absolute value.
In some cases we may also have values near to 0, so some absolute tolerance level will be needed.

A straw-man proposal : 
```
dmax = np.max(np.abs(data))
dtype = data.dtype
size_rtols = {d: 10 ** (np.ceil(1 + np.log10(2.0 ** (-8 * d))))
                    for d in (2, 4, 8)}  # !! you may well ask !!
rtol = size_rtols[data.dtype.itemsize]
atol = rtol * dmax
```

**Comment by pp-mo** [comment]
Now in #3135
