### ISSUE TITLE
Don't pin Proj4

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3154]
Remove the pin "proj4<5", introduced in #3150

Background:
#3150 fixed problems emerging with cartopy and Proj4 v 5.1
Apparently triggered by new builds on conda_forge (though also anaconda?).
A new build of cartopy 0.16, though no new version.

Needs fixing properly, but probably better done in cartopy ?
Possibly, cartopy may not work properly with Proj4 >= 5.
Which said, the newest build of cartopy 0.16 may be effectively invalid
  - [as here](https://travis-ci.org/SciTools/iris/builds/422933777?utm_source=github_status&utm_medium=notification) , lists as "py27h81b52dc_1  conda-forge",

**Comment by pp-mo** [comment]
UPDATE:
despite relaxing the pin, we still have problem with this, since proj4 v6 came out + [causes a variety of problems]().

So for the future :  **we still need to remove the pin**
( but now it means fixing proj4 v6 compatibility )

**Comment by trexfeathers** [comment]
### This is now a higher priority issue for fixing

#### Why

The proj4<6 pin now prevents Conda installing Iris with Cartopy>=0.18 - compare the installed packages for the [latest Travis build](https://travis-ci.org/github/SciTools/iris/jobs/711355125#L797) against this [experimental unpinned build](https://travis-ci.org/github/bjlittle/iris/jobs/711398545#L838).

Cartopy<0.18 also requires Matplotlib<3.3. So pins begetting more pins, each of which brings extra risk of future tech debt inflation (like what has already happened here).

It is also no longer possible for a pin of this sort to work - Iris' dependencies* are now referencing the [proj package](https://anaconda.org/conda-forge/proj) - this having replaced the [proj4 package](https://anaconda.org/conda-forge/proj4) - and proj cannot be pinned back to the desired point since it 'took over' where proj4 stopped.

#### How

- [x] Thankfully the previously mentioned problems with Cartopy's tests have since been fixed 🎉🏆
- [ ] Fix [TestMappingSubRegion](https://github.com/SciTools/iris/blob/ffcfad475e0593e1e40895453cf1df154e5f6f2c/lib/iris/tests/test_mapping.py#L104) test - [proj4>=6 broke this 2 years ago](https://travis-ci.org/github/SciTools/iris/jobs/422933781#L6721) and [proj still breaks it now](https://travis-ci.org/github/bjlittle/iris/jobs/711398545#L6977).
Might just be that the plot size has changed?
- [ ] Investigate [other test failures seen in the recent experimental unpinned build](https://travis-ci.org/github/bjlittle/iris/jobs/711398545#L6714) - may or may not be related to PROJ.
Could possibly also be Matplotlib>=3.3?

---

\* The current dependency tree has proj being brought in via the [gdal recipe](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/meta.yaml) ([cartopy recently changed to include gdal in its recipe's host requirements](https://github.com/conda-forge/cartopy-feedstock/commit/ec659aafe518a5125bda5e1500de1734a43ab5ad), so no longer has any recipe references to proj).

**Comment by trexfeathers** [comment]
Closed by #3762
