### ISSUE TITLE
Missing iris._lazy_data module for Iris 1.13.0 Conda installation

### ISSUE THREAD

**Issue by hai-peng-wang** [SciTools/iris#3166]
Hi there,

When we install iris=1.13.0 from conda-forge channel, it seems that the module "_lazy_data.py" is always missing. The error is as follows:
```
from iris._lazy_data import as_lazy_data
E   ImportError: No module named _lazy_data
```
Is this due to the channel conda-forge? Any solution for set a conda environment using Iris?

Thanks for your help in advance.

Cheers
Haipeng

**Comment by ajdawson** [comment]
The `iris._lazy_data` module was only introduced in iris v2.0.0, it does not exist in v1.13.0. Iris v2.1.0 is the latest released version and is available on conda-forge.

**Comment by valeriupredoi** [comment]
This is a valid question in light of use of `iris-grib=0.12.0==py27_0` with iris=1.13
```
Traceback (most recent call last):
  File "iris_import_test.py", line 2, in <module>
    import iris_grib
  File "/home/users/valeriu/miniconda2Dec2018/envs/cdds_new/lib/python2.7/site-packages/iris_grib/__init__.py", line 39, in <module>
    from iris._lazy_data import as_lazy_data
ImportError: No module named _lazy_data
```

**Comment by ajdawson** [comment]
It sounds like an issue on the iris-grib repository and/or the iris-grib conda-forge recipe is what is required then, if what you are saying is iris-grib==0.12.0 actually requires iris>=2.

**Comment by valeriupredoi** [comment]
@ajdawson you are correct - the problem is that I built the conda environment from a plain text recipe and even though the environment has built correctly, this doesn't actually remove the possibility that `conda env create` would have told me that I can't install `iris=1.13` **and** `iris-grib=0.12` in one env. In any case, I have just created a minimal environment with a yaml environment file:
```
---
name: cdds_free
channels:
  - conda-forge

dependencies:
  - iris=1.13
  - iris-grib=0.12
```
and the env builds no problemo but it's not functional (coz of iris-grib needing `_lazy_data`) so someone should raise this with either the iris-grib guys and/or conda :beer:

**Comment by valeriupredoi** [comment]
I can create an issue on the iris-grib gitHub page :grin:

**Comment by valeriupredoi** [comment]
done: https://github.com/SciTools/iris-grib/issues/144
