### ISSUE TITLE
iris.pandas.as_series() started throwing error

### ISSUE THREAD

**Issue by luke-wemc** [SciTools/iris#3216]
As of yesterday, when I try and convert a 1d cube to pandas series using `iris.pandas.as_series()`, I suddenly started getting the following error:

`'real_datetime' object has no attribute 'nanosecond'`

This was working fine until yesterday, I'm guessing it broke when I updated some packages.

Does anyone have a quick workaround for this? Somehow changing the nanoseconds in the cube to 0 possibly? I'm getting desperate here!

**Comment by dkillick** [comment]
As a very quick guess, I reckon this is due to the latest `cftime` version (specifically I think at v1.0.2), which introduced nanosecond time accuracy. This is [causing problems with Iris master](https://github.com/SciTools/iris/pull/3215) as well. 

If you run `conda install cftime=1.0.1` does the problem go away?

**Comment by dkillick** [comment]
In fact, here's [exactly that error](https://travis-ci.org/SciTools/iris/jobs/448959263#L6954) being reported by the Iris tests on Travis. This went away once the Iris build was pinned to not use `cftime` v1.0.2.1, so hopefully doing the same will fix this problem for you too!

**Comment by luke-wemc** [comment]
Thanks for the quick reply! This worked in the end:

conda install -c conda-forge cftime=1.0.1

Phew!
