### ISSUE TITLE
The problem with _lazy_data

### ISSUE THREAD

**Issue by mateusz1981** [SciTools/iris#3242]
I installed 2.2.0 version 
Why try to import iris I got
```
import iris
Traceback (most recent call last):

  File "<ipython-input-15-005053b25f37>", line 1, in <module>
    import iris

  File "C:\ProgramData\Anaconda3\lib\site-packages\iris\__init__.py", line 110, in <module>
    import iris.cube

  File "C:\ProgramData\Anaconda3\lib\site-packages\iris\cube.py", line 45, in <module>
    import iris._lazy_data as _lazy

AttributeError: module 'iris' has no attribute '_lazy_data'
```

**Comment by pp-mo** [comment]
The release is tested as-is, so I think this may be an import path problem.

There ought to be a file "C:\ProgramData\Anaconda3\lib\site-packages\iris\_lazy_datapy".
Is it not there ?

Alternatively, maybe your installation is getting "cross-talk" with an alternate older installation with Iris version 1, as `iris._lazy_data` is a concept new in Iris 2.
However, I don't quite get how in that case it is finding the "right" cube.py.
It may be worth looking at your user-local-site-packages for an old ".pth" that needs removing.
Under Windows that is a location something like `%APPDATA%\Python\PythonXY\site-packages`, [apparently](https://docs.python.org/3/library/site.html#site.USER_SITE).

In fact, I wonder if this could be a problem specific to Python/conda under Windows.
Unfortunately we don't know much about that here, as our internal systems permissions don't support it.
Perhaps someone else can help ?

**Comment by mateusz1981** [comment]
In the catalog C:\ProgramData\Anaconda3\Lib\site-packages\iris there is a file __lazy_data.py but there is not iris_lasy_data.pl
From paths I got
`print(sys.path)`
['', 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\spyder\\utils\\site', 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages', 'C:\\ProgramData\\Anaconda3\\pkgs', 'C:\\ProgramData\\Anaconda3\\python36.zip', 'C:\\ProgramData\\Anaconda3\\DLLs', 'C:\\ProgramData\\Anaconda3\\lib', 'C:\\ProgramData\\Anaconda3', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Sphinx-1.5.6-py3.6.egg', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\IPython\\extensions', 'C:\\Users\\mali\\.ipython', 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages']

I am not expirienced pythonused thus do not see anything strange

**Comment by dkillick** [comment]
I unexpectedly encountered exactly the same thing on MacOS earlier, and I haven't since been able to reproduce it. I don't think therefore that this is a Windows error.

The two unusual things about the env where it occurred were:

* the env didn't contain cartopy (I don't at all know how that happened, so I don't think this is the problem)
* the env was cluttered, containing loads of packages that had been updated

I think that the problem might be coming from the second unusual thing about the env, as I could not reproduce this problem with newly created envs, even when they had contents that were otherwise nearly identical to the problem env.

@mateusz1981 if you create a clean env containing Iris and use that do you still see this problem? The following commands should also work on Windows (I don't have a Windows machine I can test this on) to create a clean env and test importing Iris:

```bash
conda create -n iris_test -c conda-forge iris
source activate iris_test
python
import iris
```

**Comment by mateusz1981** [comment]
As far as I understand! When I execute the code you gave me, after deleting the previous installation of `iris` (as it caused some problems) it works in the `anaconda `prompt but not in the `spyder`.

**Comment by pp-mo** [comment]
I don't know spyder well, but in both Eclipse (with PyDev plugin) and PyCharm, it is necessary to explicitly create a new "python interpreter" to reference the new environment, **_and_** to update the interpreter setting for the 'project' your run code is in : otherwise it will still be running with the old environment
(or possibly revert to  a 'default')

Both Eclipse and PyCharm also need you to go through all this again, any time your env changes (e.g. new packages installed), because they don't track dynamic changes.
Spyder may be different though ...

HTH @mateusz1981
