### ISSUE TITLE
cube extraction gives None or Too many indices

### ISSUE THREAD

**Issue by geografin** [SciTools/iris#3243]
Hello! I try to subset a cube:
UNKNOWN LOCAL PARAM 182.128 (time: 24; latitude: 721; longitude: 1440)
     Dimension coordinates:
          time                               x             -               -
          latitude                           -             x               -
          longitude                          -             -               x
to one point.
But, subset=cube.extract(iris.Constraint(latitude=181.75,longitude=55.75)) gives NoneType 
and subset=cube.extract(iris.Constraint(latitude=181.75) gives error Too many indices.

I don't understand the problem. Coordinates exist. Why extracting doesn't work?
Thank you for any idea. I can't attach ecmwf files, but I can say that these are several files with different forecast times and two parameters. I make one cube with one parameter, all lats and longs and 24 times and then I try to extract.

**Comment by rcomer** [comment]
Hi @Jasen57, this issue tracker is really for reporting bugs in Iris or requesting new features.  The recommended places to get help are the dedicated [Google Group](https://groups.google.com/forum/?hl=en-GB#!forum/scitools-iris) or on [Stack Overflow](https://stackoverflow.com) with the `python-iris` tag.

Since we're here though, I suspect your first example is returning `None` because you don't have a latitude and longitude point that exactly matches what you're after.  You can try adding bounds to your coordinates, and then you will get any matches where the bounds span the desired numbers:

```python
cube.coord('latitude').guess_bounds()
cube.coord('longitude').guess_bounds()
subset = cube.extract(iris.Constraint(latitude=181.75,longitude=55.75))
```

**Comment by rcomer** [comment]
Looks like this was re-raised on [Stack Overflow](https://stackoverflow.com/questions/53796134/iris-cube-extract-gives-none-or-too-many-indices), so I'll close this one.
