### ISSUE TITLE
Can weighted_aggregator take dask arrays as the weight field (instead of a numpy array)?

### ISSUE THREAD

**Issue by ledm** [SciTools/iris#3337]
Just asking a quick question, can a weighted_aggregator take dask arrays as the weight field (instead of a numpy array)?

I've recently switched the weights in a weighted mean calculation from a numpy array to a dask array. This is creating an error:

```
File "[...]/iris/cube.py", line 3277, in collapsed
    weights = kwargs["weights"].view()
TypeError: view() missing 1 required positional argument: 'dtype'
```

(The dask array was created using the dask.array.stack on a iris.cube.core_data.)

**Comment by ledm** [comment]
As a corollary to this question, I'm trying to collapse a cube along a single dimension (`time`, in this case). Is there a way to provide a weights field along only that dimension? 

ie, the cube is sized: `(time: 24; depth: 33; latitude: 180; longitude: 360)`
and the collapsed cube would be: `(depth: 33; latitude: 180; longitude: 360)`.

Is there a way to provide only the `time` weights as an array of shape `(24,)`, instead of tiling this small array up to the the size of the cube: `(24, 33, 180, 360)`.

The full sized array is causing memory issues.

**Comment by ajdawson** [comment]
For the `iris.analysis.cartography.area_weights` function we broadcast the 2D weights to the full shape of the cube using `iris.util.broadcast_to_shape` which is internally using `numpy.lib.stride_tricks.as_strided` to create an n-d view of the 2d weights. The result of this is the memory overhead for matching the full shape of the cube is very small, its just a little more than the 2d weights regardless of how many other dimensions exist.

It may be that we could shift the burden of working out how to reuse a weights array of lower dimension than the cube to the site of use (i.e. the weights could match the dimension(s) being collapsed instead of the full shape). Worth investigating perhaps.
