### ISSUE TITLE
Resolve iris-grib test failures

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3447]
See #3446, in particular this [comment](https://github.com/SciTools/iris/pull/3446/files#r331299450).

Results in the following errors=10, failures=5 for `iris-grib` tests, see this associated [travis-ci log](https://travis-ci.org/bjlittle/iris/builds/593293384).

**Comment by pp-mo** [comment]
A couple of related issues that this ought to close :
  * #3375 
  * #3070

**Comment by bjlittle** [comment]
This is also related:
- https://github.com/SciTools/iris/pull/2608

**Comment by lbdreyer** [comment]
FYI:
When getting iris_grib (and python-eccodes) to correctly install in the travis job, you can use the [installation in the iris-grib repo](https://github.com/SciTools/iris-grib/blob/master/.travis.yml#L39-L48) as a reference. But note that [python-eccodes is now available from conda-forge](https://github.com/regro-cf-autotick-bot/python-eccodes-feedstock/blob/0b723587c91a83dba217c9e3b17b44f2783657e5/recipe/meta.yaml), so we should install it from there rather than a pip install as is done in iris-grib

**Comment by bjlittle** [comment]
When installing from conda-forge note the approach used in [travis-ci](https://github.com/SciTools/iris/blob/master/.travis.yml#L103-L108), which ensures that installing `iris-grib` doesn't install `iris` as it's dependency - which could replace the development version of `iris` being tested.

**Comment by lbdreyer** [comment]
#3469 has addressed most of the test failures, skipping the three that cannot be fixed in iris. 

I have raised an new PR to target the work of moving these tests to iris-grib where the necessary fixes can be applied
