### ISSUE TITLE
What's New Compilation Procedure/Automation

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#3451]
It is currently not possible to compile a What's New based on the documentation and script alone - further knowledge is also required. Changes needed:

- [ ] Add two other types of contribution to the [developer's guide](https://scitools.org.uk/iris/docs/latest/developers_guide/documenting/whats_new_contributions.html#writing-a-contribution) and to [aggregate_directory.py](https://github.com/SciTools/iris/blob/master/docs/iris/src/whatsnew/aggregate_directory.py):
  - Dependency updates
  - Breaking changes (only expected for major releases)
- [ ] Developer's guide: provide guidance on the manual work needed after the aggregate script has run:
  - Adding showcases
  - Building a local html to check all formatting, spelling and link functionality
- [ ] Address the horizontal lines added by the aggregate script:
  - Find a way to cope without them (they have been added due to difficulties with [reST](http://docutils.sourceforge.net/rst.html))
  - OR document in the developer's guide that they need to be manually removed
- [ ] Developer's guide: document the step where [index.html](https://github.com/SciTools/iris/blob/master/docs/iris/src/_templates/index.html) is changed so that the What's New link points to the newly created file.
- [ ] Notes on removing the contribution folder when done?

See also #2104 for notes on documentation clarity

**Comment by bjlittle** [comment]
Can we make this actionable? Willing to lead the charge @trexfeathers ?

**Comment by trexfeathers** [comment]
Happy to lead on this when I next have development time :-)

**Comment by tkknight** [comment]
#3769 primed to improve the what's new process and documentation.

In answer to the original post:

- Add two other types of contribution to the developer's guide and to aggregate_directory.py:
  - Dependency updates
  - Breaking changes (only expected for major releases)

**#3769.  An updated set of categories have been documented and past whatsnew pages updated.**

- Developer's guide: provide guidance on the manual work needed after the aggregate script has run:
  - Adding showcases
  - Building a local html to check all formatting, spelling and link functionality

**#3769.  Documentation on how to add an entry to the whatsnew.  The **make html** checks all formatting.  Spelling is not checked at present, however there is a sphinx extension (https://github.com/sphinx-contrib/spelling) to do this but as there are many technical references it will highlight many spelling issues.  Needs to be tested before being considered**

-  Address the horizontal lines added by the aggregate script:
 -  Find a way to cope without them (they have been added due to difficulties with reST)
  - OR document in the developer's guide that they need to be manually removed

**#3769.  The aggregate script has been removed.**  

-  Developer's guide: document the step where index.html is changed so that the What's New link points to the newly created -file.

**#3769.  This has been added to the whatsnew guide**

- Notes on removing the contribution folder when done?

**#3769.  Contribution folder is no longer used**
