### ISSUE TITLE
Include CellMeasures and AncillaryVariables in repr_html

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#3467]
Raised as part of this [review comment](https://github.com/SciTools/iris/pull/3422#issuecomment-541785295) 

It appears the CellMeasure and, once #3422 is in, AncillaryVariables are not handled in the `iris.experimental.representation` content handling

**Comment by lbdreyer** [comment]
CellMeasures and AncillaryVariables should have their own headings, see: https://github.com/SciTools/iris/blob/master/lib/iris/experimental/representation.py#L101-L108

**Comment by stephenworsley** [comment]
Just to add to this, it seems that `'Invalid coordinates'` and `'Scalar cell measures'` are also not currently hadled.

**Comment by stephenworsley** [comment]
It looks like there are actually a few things that repr_html doesn't handle. Another edge case is when two coordinates share a name and this line is invoked: https://github.com/SciTools/iris/blob/0e362814bb87d4bda89f253b2342b41a1578b9bd/lib/iris/cube.py#L1793
This may or may not belong in the scope of this issue, but it is probably worth being aware of since it seems the addition of these headers may not be entirely trivial.

**Comment by bjlittle** [comment]
Closed by #3475
