### ISSUE TITLE
Proposed fixes to _discontiguity_in_bounds() 

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3480]
@stephenworsley Reference #3404

Let's have the discussion here, and see if there is any momentum.

@pp-mo and @alastair-gemmell

**Comment by cpelley** [comment]
See #3345

**Comment by bjlittle** [comment]
Peloton discussion - this passes for meshes that are contiguous, but fails to recognise some meshes that aren't contiguous.

**Comment by bjlittle** [comment]
@stephenworsley Is this important for `iris-esmf-regrid` ?

**Comment by stephenworsley** [comment]
> Peloton discussion - this passes for meshes that are contiguous, but fails to recognise some meshes that aren't contiguous.

I've had another look at my comments for this and I believe there is also another bug which would cause discontiguous coords to test as contiguous due to these lines:
https://github.com/SciTools/iris/blob/ae2b59ba3dc68fe54893f4e8f4246e5c19c1a5bf/lib/iris/coords.py#L1978-L1984
which would fail when `cell_size` was sufficiently large.
