### ISSUE TITLE
Tidy iris.experimental module

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3515]
Identify and pull through any experimental functionality from `iris.experimental` into the core of `iris`, and also retire any obsolete functionality.

---
### Acceptance Criteria
- [x] Remove `iris.experimental.concatenate` (see #3523)
- [x] Rationalise `iris.experimental.equalise_cubes` (see #3527)
  - [x] Move `iris.experimental.equalise_cubes.equalise_attributes` to `iris.util`
  - [x] Replace `iris.experimental.equalise_cubes.equalise_attributes` with an exception, e.g., see [here](https://github.com/SciTools/iris/blob/v2.2.1/lib/iris/experimental/concatenate.py#L43-L48)
- [x] Review outstanding `iris.experimental` functionality
 - NB: Must include identify all that are used operationally, (def includes areaweighted regridding). as they must not be deprecated.

**Comment by bjlittle** [comment]
Ping @abooton

**Comment by trexfeathers** [comment]
# Review of all [`iris.experimental`](https://github.com/SciTools/iris/tree/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental) functionality

## [`ugrid`](https://github.com/SciTools/iris/tree/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/ugrid)

🪑 Stay `experimental`.

We're just starting to get user traction in this highly unfamiliar space. We also have our outstanding list of significant changes - #4438 - that are important to finish and could lead to quite dramatic changes. This module should remain in `experimental` for now.

## [`animate`](https://github.com/SciTools/iris/blob/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/animate.py)

🎓 Graduate from `experimental`.

https://github.com/SciTools/iris/pull/496#issuecomment-22654683 indicates an intent to hold in `experimental` pending user feedback. There hasn't been much feedback since, and the Git-blaming the file shows that the code has been static.

However I know at least three recent cases where the functionality has been a potential solution for users:

- @jonnyhtw - #4771
- @mcrimaldi - #4965
- @cgsandford / @rcomer - internal UK Met Office communications

... so I see this as a low overhead convenience with some value and minimal controversy. I will put up a PR graduating it out of `experimental`.

## [`raster`](https://github.com/SciTools/iris/blob/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/raster.py)

🔥 Already deprecated.

## [`regrid`](https://github.com/SciTools/iris/blob/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/regrid.py)

🔥 Already deprecated.

## [`regrid_conservative`](https://github.com/SciTools/iris/blob/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/regrid_conservative.py)

🔥 Already deprecated.

## [`representation`](https://github.com/SciTools/iris/blob/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/representation.py)

🪑 Stay `experimental`.

Due for replacement - #4779 - the current should therefore definitely NOT graduate from `experimental`.

## [`stratify`](https://github.com/SciTools/iris/blob/f58682db58058d28119490a03c530b1ca67f2ec9/lib/iris/experimental/stratify.py)

🪑 Stay `experimental`.

A convenience for easy use of [`python-stratify`](https://github.com/SciTools/python-stratify) with `Cube`s, currently with a fairly limited scope. There's a reasonable amount of interest in `python-stratify` during user discussions, but not so much interest in this module; we're not sure if that's due to lack of awareness or lack of flexibility.

Git-blaming the file shows that the code has been static since introduction 6 years ago (#2471), perhaps not surprising due to the lack of user engagement.

So we need more user engagement! Actions for raising awareness:

- [ ] Mention in the `v3.4` what's new.
- [ ] Mention in the `python-stratify` `README`
- [ ] Increase developer awareness so that it can be mentioned during user support
