### ISSUE TITLE
Fix cube equality for ancillary variables

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#3529]
A subtask for #3422. Fixing this first should make testing for the rest of #3422 easier.

Cube equality `(__eq__)` is ignoring AVs (and maybe CellMethods) but not AuxCoords.

---
### Acceptance Criteria
 - [x] Fix cube equality
 - [x] Write tests for equality
 - [x] Raise issues for any failing tests (tests may be skipped until a further pull request)

**Comment by bjlittle** [comment]
@stephenworsley Just checking... is this also applicable to `iris.coords.CellMeasure`s?

**Comment by pp-mo** [comment]
Just about the naming of this issue ...   It seems to be mixture of `auxiliary` and `ancillary` ?
It's confusing enough already !!

**Comment by stephenworsley** [comment]
@bjlittle I believe so.

**Comment by bjlittle** [comment]
@SciTools/iris-devs Are we proposing that `iris.cube.Cube` equality includes comparing the associated `AncillaryVariable` and `CellMeasure` metadata **and** data?

Just guessing, but that sounds **mighty expensive**, particularly for large cubes 💣 

Aren't we glad that #3526 landed...

**Comment by pp-mo** [comment]
>  sounds mighty expensive

But we are doing it for coords, including possibly huge multidimensional AuxCoords,
so where's the difference ??

**Comment by bjlittle** [comment]
> so where's the difference ??

@pp-mo The *difference* is that we could also potentially be comparing between 1..N `AncillaryVariable` data payloads of the same dimensionality as the `iris.cube.Cube.data`, in addition to the `iris.cube.Cube.data`, plus perhaps a `CellMeasure`, and then as you mentioned *possibly huge multidimensional AuxCoords* 🤒

I'm just raising the concern that this just might not scale well, and be not at all practical or performant for the user. Perhaps we should consider options for the user with large data **and** large metadata, rather than offering Hobson's choice `cube` equality; where absolutely everything is always compared.

Just sayin'...

**Comment by bjlittle** [comment]
@stephenworsley BTW `Cube.__eq__` uses the `Cube.metadata` during equality, which includes `Cube.cell_methods`, see [here ](https://github.com/SciTools/iris/blob/v2.3.0rc0/lib/iris/cube.py#L3051)and [here](https://github.com/SciTools/iris/blob/v2.3.0rc0/lib/iris/cube.py#L832). HTH, so I guess you should change the description of this issue.

The functionality that's missing for `Cube` equality is only:

- `CellMeasure`, and
- `AncillaryVariable`

... as I understand it 😄

**Comment by stephenworsley** [comment]
Another thing worth fixing, it seems like if a pair of cell methods are added in a different order to two otherwise equal cubes, they are evaluated as not equal.

**Comment by stephenworsley** [comment]
I have detailed some of my thoughts on the direction we could take this in #3536.
