### ISSUE TITLE
CubeList.copy() should be a deepcopy()

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#3651]
The `CubeList` class should be given `.copy()` behaviour using `deepcopy()` in the same way that `Cube.copy()` works.

Using `deepcopy()` was a deliberate decision as this behaviour was considered less confusing for most Iris users. No such change was made for `CubeList.copy()`, so now instead there is a confusion about the behaviour difference between `Cube` and `CubeList`.

**Comment by rcomer** [comment]
Hmmm.  To make `CubeList.copy()` consistent with `Cube.copy()`, you'd be making it _inconsistent_ with `list.copy()`.  So it would likely still be surprising for someone. :worried:

I guess this never came up in early Iris because, under python2, `list` had no `copy` method.

**Comment by trexfeathers** [comment]
Yes it has since been explained to me that the situation is more complex than it appears. I'm still not clear on the details, and whether this deserves a dev discussion or should perhaps just be closed.

**Comment by pp-mo** [comment]
There is no real consistency to be expected in Python on these things. 
But if CubeList is considered to be a **_container_** class, then it should copy the way containers do : you get a new container with the same members as content (not copies of them).

CubeList is an odd thing, really, whose actual purpose is rather unclear.  
Many new uses, when first encountering it, assume that the cubes contained must have *some* special relationship, like all having the same grid, or matching X- and Y-winds for instance.  
But in fact it says nothing in particular about its contents.  It is really just a home for some special convenience behaviours, like a special printout for a list of cubes, and merge/concatenate (which really _could_ have been delivered as utility operations rather than cubelist methods anyway, IMHO).

**Comment by pp-mo** [comment]
>  a container class

Mind you, that concept has no definitive meaning.  See https://stackoverflow.com/a/11576019/2615050

**Comment by rcomer** [comment]
I may have misunderstood - was this done at #4094?

**Comment by trexfeathers** [comment]
> I may have misunderstood - was this done at #4094?

@rcomer that PR only concerned the returning of the correct type. It's still a shallow copy, unless I've misunderstood Python internals, which is always possible!

**Comment by ESadek-MO** [comment]
There doesn't seem to be much interest in this, so will close. Can reopen if desired.
