### ISSUE TITLE
Assigning new dtype to core_data works but doesn't preserve it to realized data

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#3691]
Apologies if this is fixed elsewhere, but I am struggling to assign a different `dtype` to the `Cube`'s data and keeping things lazy:

Assigning a different `dtype` to `core_data` works but that doesn't preserve it to the actual `data`:

```python
import iris
import numpy as np

c = iris.load_cube("t2.nc")
print(c.core_data().dtype)
c.core_data = c.core_data().astype(np.float16, casting='same_kind')
print(c.has_lazy_data())
print(c.core_data.dtype)
print(c.data.dtype)
iris.save(c, "t3.nc")
d = iris.load_cube("t3.nc")
print(d.data.dtype)
```

@bjlittle @pp-mo @lbdreyer  do you know how to change the dtype of a cube data member without accessing it and un-lazying the data? :beer:

**Comment by valeriupredoi** [comment]
sorted! `c.data = c.core_data().astype(np.float64, casting='same_kind')` does the trick - cheers to @schlunma :beer: - but confusing since it keeps the data lazy even though the data member is accessed...

**Comment by pp-mo** [comment]
Glad you sorted !
I was preparing to look into it.  

It is only *fetching* the `.data` that realises.  Unlike fetch, setting `.data` is "transparent" + works with either type of data.  
You could think of `.core_data()` as the "real" stored array, while `.data` and `.lazy_data()` are a kind of casting access.  It's not quite the whole truth though, because internally we use the 'DataManager' wrapper for data of any type.

**Comment by valeriupredoi** [comment]
great explanation @pp-mo much appreciated! :beer:
