### ISSUE TITLE
Unable to install using pypi

### ISSUE THREAD

**Issue by bhushanbrb** [SciTools/iris#3716]
> python3 `pip3 install scitools-iris` 

- I know I should use conda where it works perfectly fine but for submitting jobs to aws glue or lambda it needs external package ( like iris module) to be zipped. I think it will be huge size to upload using conda>site-packages> I assume it would not work on aws Glue 

so having a capability to install using pypi will help to submit jobs to AWS 

>practially impossible to have all dependencies on cloud 
> Proj and GEOS 
basically it fails at cf_units 
   ``` cf_units/_udunits2.c:623:10: fatal error: 'udunits2.h' file not found
    #include "udunits2.h"
             ^~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1```

Can some one please advise on how to package IRIS package or install using pypi so that way It can be used on aws glue

**Comment by bhushanbrb** [comment]
@DPeterK tagging in case you have any workaround or solution for this

**Comment by danieldjewell** [comment]
In https://github.com/SciTools/cf-units/blob/master/requirements.txt#L6 the  indication is that udunits2 will be installed and available - the error you're getting is indicative of udunits2 dev/header files missing (the .so library could be there, but cf-units/cython needs the header files.) 

I'm unsure what service you're using on AWS (there are so many) -- if you're able to install Linux distribution packages, I know that udunits2 is available in several debian releases: https://packages.debian.org/source/udunits (```apt/apt-get install libudunits2-0 libudunits2-dev libudunits2-data``` should work on debian systems)

That said, building cf-units requires a full build toolchain (e.g. cython/gcc/bintools/etc.). Depending on how you're using AWS, I suppose it would be possible to compile a binary wheel of cf-units and just make sure that the udunits2 library is available? (I can't recall if Cython can pull in a library like udunits2 statically ...) 

Part of the other issue is that udunits2 is a little *funky* because it relies on a set of XML files with the unit definitions -  and the default path is actually compiled into the library... see: https://github.com/Unidata/UDUNITS-2/blob/00ce1e1e35e127761bd66b7bc0e9f23709031f27/configure.ac#L75 and https://github.com/Unidata/UDUNITS-2/blob/00ce1e1e35e127761bd66b7bc0e9f23709031f27/lib/xml.c#L2135 ... 

(I don't think that was a particularly direct/clear answer ... :disappointed: ... I'm not sure there really is an easy answer here... but hopefully it's at least some things to think about :thinking:)

**Comment by bjlittle** [comment]
@bhushanbrb In my experience, due to the (many) dependencies that `iris` requires, using `pip` doesn't have complete package coverage (and never has for `iris`) i.e., you'll only get so far using `pip` to install packages from `PyPI` before you hit the wall e.g., most notably with `proj` or indeed `udunits2`, which you need to make available on your platform by *some other means*.

That said, given your use case, would it not be possible to use [conda pack](https://conda.github.io/conda-pack/) instead? This should give you a relocatable conda environment as a tarball. Just a thought...

Also, I'm keen that we reduce the dependency bloat of `iris`, and adopt a leaner `iris` core with optional feature plugins e.g., you may not require regridding, or plotting, or PP/FF file-format support. If this is the case, then you can also purge those dependencies, reduce the footprint of `iris` and perhaps avoid dependency related issues for `iris` capability that you don't actually need anyways... however, this is more of a long term aspiration, and not something that will help you in the immediate to short-term. I just think that it would be lovely for `iris` to offer this *out the box*.

**Comment by bjlittle** [comment]
This issue is kinda related to https://github.com/SciTools/iris/issues/3777 - but no solution there either, sorry :disappointed:

**Comment by bjlittle** [comment]
@bhushanbrb I'm going to close this issue. If you wish to discuss further, then please re-open this issue and we can take it from there. Many thanks!
