### ISSUE TITLE
issues using iris.experimental.regrid_conservative  for masked data

### ISSUE THREAD

**Issue by nhsavage** [SciTools/iris#3770]
When using iris.experimental.regrid_conservative for regridding source data which has a mask associated with it, the masking of the regridded data is not working as expected. I would expect that if any valid points are included in a target grid cell then vali data would be output. Instead if any of the grid point on the source grid are masked, the cell on the target grid is all missing.

This is due to the tolerance value for missing data being set to 1 - 1.e-8 with no option to change this.

https://github.com/SciTools/iris/blob/84d1330f3b033fd1c24ad5c41ef94819913195c0/lib/iris/experimental/regrid_conservative.py#L265

This contrasts with iris.analysis.AreaWeighted where mdtol is a parameter for the scheem, and the default is 1 (the logic here is also reversed - AreaWeighted uses a missing data tolerance, whereas this routine uses a coverage_tolerance.

I suggest that there should be a new argument for this routine mdtol consistent with AreaWeighted to reduce confusion and increase functionality. The remaining quesiton is whether to change the default value to be consistent with AreaWeighted

**Comment by nhsavage** [comment]
there are one or two outstanding issues with this change:
1. what should the default md_tol be? 1.e-8 would be backward compatible with the existing code, 1 would be conistent with iris.analysis.AreaWeighted (but see point below)
1. if md_tol is zero or 1, then the code doesn't work as expecting. I assume that when coverage_field is calculated, there are some rounding errors that mean it is never 0 or 1, In my tests, 1.e-13 and 1 - 1.e-13 seemed appropriate as minimum and maximum values to use for this argument but should we let the user chose values outside these ranges or should this be an error? If allowed, should we force the values to be between these ranges (on the basis that 1.e-13 is as close to 0 as makes no difference?

Also need to update docstring to add new argument and consider tests.

**Comment by pp-mo** [comment]
I'm not too keen on adopting small changes to this routine, unless you're really devoted to it, because it was really just a proof-of-concept, and has never attracted much interest or improvement effort, despite there being a lot that could/should have been improved :
  * at the least, it should probably be re-cast as a "scheme", so you can re-use the costly regrid weights calculation on another cube.
  * mdtol could easily be user settable, and I think that would be preferable.
  * arguably, "total missing data tolerance" is more workable/defensible than "maximal intolerance", given the problems of setting a default value to avoid rounding errors. as you note.  Though of course, that is not backward-compatible.  Also, I think the maximum error is bound to depend on size and complexity of the grids, so it's really hard to define a workable default value.
  * current investigations seem to show that, while it may make sense to use ESMF for calculate the regrid weights, at least until something better, it is probably more efficient to do the actual regrid using Python sparse arrays.  That is likely to drastically reduce memory footprint, in particular.

So ... we are currently re-visiting this whole area, and may well decide to replace rather than improve this,
See https://github.com/SciTools-incubator/iris-ugrid/pull/10 for the beginnings of a better solution.

**Comment by nhsavage** [comment]
that seems reasonable. I will close this ticket in that case.
