### ISSUE TITLE
Should fileformats.pp label PP files with the WGS84 ellipsoid rather than a sphere?

### ISSUE THREAD

**Issue by RogerHar** [SciTools/iris#3775]
Currently [fileformats/pp.py](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/pp.py#L1368) labels the latitude and longitude coordinates as being referenced to a sphere when a PP file is loaded (PP files themselves do not specify a coordinate reference system). I believe it would be preferable to label them with the ellipsoid specified by [WGS84](https://gisgeography.com/wgs84-world-geodetic-system/) as this is the standard used for GPS coordinates, orography datasets such as [GLOBE](https://www.ngdc.noaa.gov/mgg/topo/report/s4/s4.html) and other data used by the UM. This becomes important when data is exported e.g. to netcdf then read in to other systems.

The Met Office Unified Model assumes the earth is a sphere to simplify many calculations (e.g. of gravitational and Coriolis forces) but that doesn't mean its latitude and longitude coordinates are referenced to a sphere. Latitude referenced to a sphere (equivalent to geocentric latitude) differs from the usual latitude (geodetic latitude referenced to an earth ellipsoid) by up to 0.19 degrees -- see e.g. [this blog post](https://www.johndcook.com/blog/2011/09/17/latitude-doesnt-exactly-mean-what-i-thought/) or [Wikipedia](https://en.wikipedia.org/wiki/Latitude#Latitude_on_the_ellipsoid). Put another way, two points on the Earth with the same numerical values of latitude and longitude referenced to a sphere and an ellipsoid are up to 21 km apart -- see e.g. [Monaghan (2013)](https://doi.org/10.1175/MWR-D-12-00351.1), which also illustrates the importance of correct handling geographic coordinates and coordinate systems in the context of meteorological models.

This becomes important when data is exported to e.g. netcdf for use by other packages that respect the coordinate reference system metadata, particularly when combining or comparing with other data sources, e.g. for verification. I'm not clear what effects this change would have within Iris, however, or what other implications this would have for its users.

**Comment by marqh** [comment]
Hello @RogerHar 

thank you for bringing this up, i have also been conducting some slow time investigations into this topic, and I agree with your perspective.

I think it is more valid and more valuable to label UM data as being defined with respect to WGS84 with respect to horizontal position.

The input data from many observations, orography and so on is WGS84, as far as I am aware.

I do not believe there is anything within the Endgame dynamics that specifies anything about the explicit shape of the geoid.

So, I am all in favour of investigating the implications of altering the Iris PP load process and specifying WGS84 for spatial referencing of latitude and longitude coordinates and seeing whether this would be an appropriate change.

I expect that the code change and the associated tests are not that complicated to implement, and I would be very keen to ensure that the actual values of latitude and longitude are not transformed in any way.

I think that the implications for users require some thought and investigation.  This ticket would be a good place to get that process going.

marqh

**Comment by marqh** [comment]
We need to be careful not to overreach the applicability of WGS84, particularly with regard to the definition of vertical position.

WGS84 defines an idealised ellipsoid, which deviates significantly from measurements of local mean sea level.

This can bring in discrepancies of the order of 50m at latitudes  ~50°, a really significant issue for altitude.

I suggest that vertical datum definition be clearly marked as out of scope for this ticket, and I encourage people to be wary of using the WGS84 datum for altitude definitions.

**Comment by marqh** [comment]
Hello @RogerHar  

There are nuances around interpretation and how geocentric and geodetic latitude are used, and I would be wary about trying to impart any transformation implications on this. I'm not yet convinced that there as location shifts involved here.

It is useful for spatial considerations, such as model geometry, to explicitly decouple the 2D position in horizontal space from the altitude.  They are handled very differently and operate at quite different measurement scales.

Given these caveats, I'm not sure I agree with the detail point:
> two points on the Earth with the same numerical values of latitude and longitude referenced to a sphere and an ellipsoid are up to 21 km apart 

The links you provide provide some detail on the difference between geodetic latitude and geocentric latitude, and are valid considerations.  However, i do not believe that this difference is the same as the difference between geodetic latitude with respect to a sphere and geodetic latitude with respect to a WGS84 datum.

I think there is a significant issue when considering 3 dimensional geometries and 3 dimensional positional calculations, but in the cases we are looking at, I think that the geometries are 2 dimensional horizontal position, with altitude being layered on independently. We can think of it as 2D position being extruded up through the modelled atmosphere.
A 3D (latitude,longitude,altitude) position w.r.t. sphere is a very different place from a 3D(latitude, longitude, altitude) w.r.t. wgs84, especially in altitude. But this is not the same as a 2D position on a 2D surface, which I think better represents our problem domain.

So, sticking with 2D position on a curved surface, I think that the consequence of this is that for a given (latitude, longitude) position tuple, defined with respect to a 2 dimensional spherical datum, the equivalent (latitude, longitude) position tuple, defined with respect to the WGS84 datum is the same valued (latitude, longitude) tuple.
This is a null transform, I think.

I may well be missing aspects here, and I may be in error. There may be some well defined datum transformation between a authalic sphere datum and wgs84, but I cannot find a definitive source for one, in text or software. This contrasts with well published datum transformations between widely used datum definitions in geodesy. Modern geodesy does not appear to consider a sphere in any structured way.

This is how the Proj library, which provides coordinate specification and transformation support for Iris, is coded.
Proj sees a wgs84 datum to sphere datum as a null transform.
This contrasts with encoded datum shifts, such as between the wgs84 datum and the airy1830 datum used by ordnance survey to define OSGB.

We can demonstrate this implementation as follows:
```
>>> import pyproj
>>> # define a WGS84 crs
>>> wgs84 = pyproj.Proj('epsg:4326')
>>> # define osgb crss, for projection (27700) and for the underlying ellipsoid(4277)
>>> osgb = pyproj.Proj('epsg:27700')
>>> osgbEllipsoid = pyproj.Proj('epsg:4277')
>>> # project a sample point from wgs84 lat,lon to osgb easting,northing, to show we know what we are doing
>>> print(pyproj.transform(wgs84, osgb, 50.7236, -3.52751))
(292275.3612944764, 92666.07087017002)
>>> # calculate the lat,lon based on a datum shift from wgs84 to airy1830
>>> print(pyproj.transform(wgs84, osgbEllipsoid, 50.7236, -3.52751))
(50.723047216331274, -3.5263182947614613)
>>> # define a crs, based on an authalic sphere, defined in well known text
>>> asphere = pyproj.Proj(projparams='GEODCRS["sphere",  DATUM["sphere",    ELLIPSOID["authalic sphere",6371229,0,LENGTHUNIT["metre",1.0]]],PRIMEM["Greenwich",0],  CS[ellipsoidal,2],    AXIS["latitude",north,ORDER[1]],    AXIS["longitude",east,ORDER[2]],    ANGLEUNIT["degree",0.01745329252]]')
>>> # calculate the lat,lon based on a datum shift from wgs84 to the authalic sphere
>>> print(pyproj.transform(wgs84, asphere, 50.7236, -3.52751))
(50.7236, -3.52751)
>>> # null transform, output==input

```


Given these considerations, I think that the (latitude,longitude) position values as given by the UM can be considered correct for WGS84, as long as we are careful to ensure that we are working in 2dimensional horizontal position.

The Proj library is in essence a 2D library, functionally it operates on 2D horizontal space.  It is not encoded to deal with the complexities of 3D geometries, and the difficulties of handling vertical datum differences nor 3D space.

So, given all this, why do I still care about the CRS definition?
Firstly, I care because I think your logic is valid and accurate, and I think we should be specifying our data sets appropriately. i think that WGS84 is appropriate for referencing the latitude and longitude values output by the UM.

Secondly, CRS definitions based on a spherical datum are not common in general mapping tools/software, and many users may find it easier to import data defined w.r.t. WGS84. 

Thirdly, the implications of different datum definitions become really important when we look at geographical features and their measures.
Of crucial importance here is cell area.  For example, if one were to calculate a global parameter, based on an area weighted calculation on a modelled phenomenon, the weights for cell area are significantly different depending on the choice of geometry. Polar cells are particularly different in area value when comparing AuthalicSphere to WGS84.
So, an area weighted mean of a phenomenon will have different values, dependent on the geoid used to calculate the weights.

This aspect seems to me to have scientific importance, and is due some targeted consideration, I feel.
The issue of weighting seems to me the most high profile implication i am aware of with respect to this topic, but there are likely to be numerous others worth some consideration.

It could be a valuable activity to obtain some global data and assess the implications on results of an area weighted calculation using the different datum definitions, providing a numerical analysis of the sensitivity of that data set to the choice of datum when reporting global parameters.

I very much welcome further dialogue on this topic

many thanks
marqh
