### ISSUE TITLE
Adopt py.test 

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#3835]
## ⚙ Feature Request

There are currently a few approaches to running the `iris` tests as a developer:

1. using the bespoke `iris.tests.runner` e.g., `python -m iris.tests.runner --default-tests`
1. using the `test` command from `setuptools` e.g., `python setup.py test`
1. using `unittest` e.g., `python -m unittest discover iris`

These are all perfectly functional approaches, for now, to take to run the `iris` tests. However, there are a few problems with each approach, namely:

1. `iris.tests.runner` mechanism is bespoke and heavily relies on `nose`, which has been in [maintenance mode](https://nose.readthedocs.io/en/latest/index.html) for several years now i.e., it's dead-end technology :bomb:. Also using this mechanism is causing issues for automatically collating testing coverage statistics.
1. the use of the `test` command in `setuptools` was [deprecated](https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite) in version `41.5.0`, (latest `50.3.0`) and will be withdrawn in a future version i.e., the future is closer than you think
1. ummm `unittest` isn't `pytest`, not even close :wink: 

## Motivation

It's high time that `iris` adoped a modern, robust, sustainable, actively supported and scalable approach to testing through [pytest](https://docs.pytest.org/en/stable/contents.html) and [pytest-xdist](https://docs.pytest.org/en/3.0.1/xdist.html)... before it's too late, and this becomes a much bigger issue than it needs to be i.e., let's agree to plan to avoid this crisis... before it's a crisis.

**Comment by bjlittle** [comment]
@SciTools/iris-devs Thoughts?

**Comment by trexfeathers** [comment]
> ummm unittest isn't pytest, not even close 😉

I would have said yes for this reason alone. Everything else makes me scared to _not_ switch!

**Comment by pp-mo** [comment]
> a few approaches to running the iris tests as a developer:

All that is about the test runner, really, which is about the "total test suite definition", and the needs of CI.

For basic developer needs, I think you missed the really obvious:
  * (4) `python -m unittest discover ./lib/iris/tests/...`
  * (5) `python /path/to/specific/test.py`

For sure we should migrate to using pytest as the engine, but the **_format_** of our tests has never depended on nose, it is all pure unittest, which pytest also supports quite happily.

So I don't think we need a wholesale rewrite.  We can adopt pytest-specific methods as they seem useful,

I do also have a couple of lingering doubts about becoming pytest-specific, though :
  * (1) at one time we likewise considered adopting nose styles, because it looked cool and much neater. In retrospect, that would clearly have been a mistake !
  * (2) I'm still not sure how+whether we can preserve our existing [rules for what to test, how to name them, and where to put them](https://scitools-iris.readthedocs.io/en/latest/developers_guide/tests.html) (or new equivalent) in the pytest style.  For all the tiresome clunkiness of the existing scheme, it does allows us to group + organise things in a useful way, albeit with a bit too much effort + verbosity.

**Comment by bjlittle** [comment]
@pp-mo Yeah, I wasn't intending to enumerate every possible way to run all the tests, it was just a means to justify my motivation and more importantly get some kinda rough gauge of what everyone else thinks.

> * (4) `python -m unittest discover ./lib/iris/tests/...`

This is kinda (3) really, but let's not split hairs :wink: 

> * (5) `python /path/to/specific/test.py`

Yup, if you wanna run those isolated tests, and all shades of grey of running individual test classes within those, or test class tasks etc

**Comment by bjlittle** [comment]
>     * (2) I'm still not sure how+whether we can preserve our existing [rules for what to test, how to name them, and where to put them](https://scitools-iris.readthedocs.io/en/latest/developers_guide/tests.html) (or new equivalent) in the pytest style.  For all the tiresome clunkiness of the existing scheme, it does allows us to group + organise things in a useful way, albeit with a bit of extra effort + verbosity.

@pp-mo That a really good point. But at the end of the day I guess we can evolve those `iris` test name conventions etc as we roll forwards, and make some pragmatic decisions if we want to be more liberal (or not), and factor into the work what needs done and when... *jeez* it's almost like we're gonna plan this :open_mouth:

**Comment by bjlittle** [comment]
With `pytest` you can run `unittest` tests *as-is*, but that's a bit of a cop out (IMHO) and it kinda paints you into a corner so that you can't fully exploit all the goodness of `pytest`.

I think that the BIGGEST headache in migration from `unittest` to `pytest` will be discovering the suitable patterns to rewrite the `mock` base unit tests in `pytest` :exploding_head:

**Comment by rcomer** [comment]
I think we have test examples that would look much cleaner using pytest parametrization, e.g. [here](https://github.com/SciTools/iris/blob/b04a3ca2554a2e5b6c40fbd96f25f9124d0eea1e/lib/iris/tests/unit/analysis/maths/__init__.py#L111) two tests that are very similar and the class is subclassed for each of the four arithmetic operations.  Or [here](https://github.com/SciTools/iris/blob/b04a3ca2554a2e5b6c40fbd96f25f9124d0eea1e/lib/iris/tests/test_basic_maths.py#L679) where each test is looping through the operations.  I assume we wouldn’t want to write anything like the latter now, as if your first operation failed the others won’t get tested.

Aside - was there an intention to move or replace all the old modules in the top level [tests](https://github.com/SciTools/iris/blob/b04a3ca2554a2e5b6c40fbd96f25f9124d0eea1e/lib/iris/tests) directory when the unit/integration subdirectories were introduced?

**Comment by bjlittle** [comment]
@rcomer I think that the *home* of certain tests requires some serious rationalisation, and for me this would come under that work.

From what I recall (and this is going back some time) those are legacy tests... and it's a fine line between those and integration tests, and system test etc. In fact, the unit tests came later, and those some to have a little bit more rigour... so IMHO it all needs a bit of a rethink to restructure it in a consistent and coherent way - plus there is most likely a lot of duplicated dead wood to purge/revisit, so we should take the opportunity to do that.

**Comment by bjlittle** [comment]
I'd also advocate that #3416 is also dealt with as part of this testing re-haul.

**Comment by pp-mo** [comment]
> was there an intention to move/replace all the old modules in the top level tests directory when the unit/integration subdirectories were introduced?
> > those are legacy tests... 

Since @bjlittle asked me directly, yes we intended to retire + replace the "legacy" tests gradually over time.  
But re-writing the old ones has generally seemed too much of a thankless task, while busy getting something else done.

**Comment by rcomer** [comment]
A further benefit of `pytest` is that it discovers tests even if you forget the `__init__.py`.  See #4192.

**Comment by cpelley** [comment]
In ants, we long ago ditched nose in favour of just plane unittests.  I can fish out the commit which removed nose from the setup.py if that would help in some way?
However, some of us do choose to use pytest to **run** the unittests (independently) as it delivers much better output.  That is, we decided there wasn't an obvious benefit (for us) to make our tests dependent on pytest at the time, but each to his own on running the tests and pytest seems to do a good job of running them.
Another thing is that the pytest (or unittests) package itself will not run tests in parallel out of the box unlike nose .  Mind you, I'm sure this can be easily achieved or otherwise I believe there are off the shelf libraries that can provide this capability...

Just a perspective I thought I would share - perhaps there is a good enough reason for writing pytest tests for iris, I don't know.  I have always favoured using the standard library myself without strong reason to do otherwise.

**Comment by rcomer** [comment]
To run `pytest` in parallel, it's just a case of installing `pytest-xdist`, then simply 

```bash
pytest -n num_cpus [other args]
```

I had a quick search for how to parallelise with  `unittest` but didn't come up with anything.  Anyone know?

**Comment by pp-mo** [comment]
> how to parallelise with unittest 

I believe it basically can't. 
That's why we stuck with 'nose' so long, as it was the only way to avoid CI timeouts.

**Comment by trexfeathers** [comment]
Awesome job @lbdreyer !
