### ISSUE TITLE
Rationalise use of tech debt project and issues-label

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3888]
## 📰 Custom Issue
Just found additional issues that were [labelled "Tech Debt"](https://github.com/SciTools/iris/labels/Type%3A%20Technical%20Debt) and added them to the [Scitools/iris/TechDebt project](https://github.com/SciTools/iris/projects/27).

We don't seem to need both.
So, I'm labelling this issue as Tech Debt too...

But we probably need a discussion to see which is best.
**Note:** it may also be better to re-create the project as a Scitools (organisation) project, so it is not limited to issues on the Iris repo itself.  In which case, this would be a good time to do that too.

**Comment by bjlittle** [comment]
@pp-mo To be honest the label came first, then the project followed later once we had a glut of technical debt labelled tickets.

At this point, I now agree with you, in that I can't now really see the value of having the label; it's superfluous.

Filtering for peloton labelled issues assigned to a user can now easily be done via the `project` rather than `label` e.g.
```
is:issue is:open project:scitools/iris/29 assignee:bjlittle  
```
So let's roll with that, and see how we fair... as a strategy, it might help reduce the bloat in our use of labels :+1:

**Comment by bjlittle** [comment]
@pp-mo I've removed the `Type: Technical Debt` label for all tickets, and ensured that they are now assigned to the [Technical Debt](https://github.com/SciTools/iris/projects/27) project instead.

I've also deleted the label.

**Comment by pp-mo** [comment]
Nice @bjlittle !

Although you closed this, there was also the suggestion here :
`> re-create the project as a Scitools (organisation) project`

How do you personally feel about that, can you see an argument against it which I am missing ?
