### ISSUE TITLE
regridding with 2D data from a global grid to a non-global grid

### ISSUE THREAD

**Issue by w142236** [SciTools/iris#3983]
## 📰 Custom Issue

To start, I am trying to regrid my data which is on a global grid because I am getting the exact same error as the one which can be found [here](https://github.com/ajdawson/windspharm/issues/77) when I try to take my iris cubes representing zonal and meridional velocity and run them through windspharm's `VectorWind()` function. To summarize, in order to avoid this error, I have to regrid the data so that it is non-global, but whenever I try to regrid the data using the `iris.regrid()` function by running:

` u.regrid(u, iris.analysis.Linear())` (as was done by Corinne77 in the linked issue) I get the following error:

`ValueError: Cube 'U velocity' must contain a single 1D x coordinate.`

All I am trying to do regrid the data so that it is non-global because Windspharm cannot handle when data exists at the poles. Any other grid type should do.

The data file that I am using can be found in my dropbox [here](https://www.dropbox.com/s/0onnfp50du2gxzx/2020042300_plev_era5.nc?dl=0)

My full code is:
`import xarray as xr`
`import iris`
`from windspharm.iris import VectorWind`
`import numpy as np`

`file = '2020042412_plev_era5.nc'`
`da = xr.open_dataset(file)`
`u_0 = da['u'][0] #level = 100hPa`
`v_0 = da['v'][0] #level = 100hPa`
`u = u_0.to_iris() #convert to iris from xarray`
`v = v_0.to_iris()`

` u.regrid(u, iris.analysis.Linear()) #Fails here`

I realize that this is more of an inquiry than an issue, but I could not find any documentation that went over an issue similar to this one. Additionally, this is my first time using Iris for plotting purposes so I don't really know what I am doing to begin with. Am I possibly using the `regrid()` function incorrectly, or is there some other type of function that deals with regridding 2-D data? Any help would be appreciated.

**Comment by rcomer** [comment]
I took a look in your NetCDF file.  Your data only includes the northern hemisphere (the latitudes go from 0 to 90 degrees).  Windspharm requires the whole globe because it works by spherical harmonics.  Since this appears to be ERA5 data, you can just go back and download the full globe from ECMWF.

I also tried loading the u-data directly into iris v3.0.1, and cannot reproduce the regridding failure with
```python
u = iris.load_cube(file, 'U velocity')
u.regrid(u, iris.analysis.Linear())
```
For info, we also have a [Google Group](https://groups.google.com/g/scitools-iris) for asking questions about how to do things.  You would probably get an answer quicker there, as more other users are involved there than here.
