### ISSUE TITLE
iris.plot arguments

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4085]
## 📚 Documentation

Example: in the [contour](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/plot.html#iris.plot.contour) description we have the keyword "coords: list of Coord objects or".  Then "coordinate names" appears on the next line, outside the shading.  This doesn't look right and I've spotted several other examples just in that module 🙁

Possibly this will come out in the wash of #3840?

Edit: #1942 changed many of the docstrings in `iris.plot`, so it's possible that the problem is largely limited to this module.

**Comment by trexfeathers** [comment]
I certainly wouldn't have expected [the docstring format for this](https://github.com/SciTools/iris/blob/3fec756c6107ea71e64e0fe7a07882f8dbde3071/lib/iris/plot.py#L1017-L1022) to have successfully rendered in RTD.

It's not often we bother scouring the whole codebase and fix everything at once, instead preferring to incrementally fix lines that we're touching while doing other work. Unfortunately that would make it **very** difficult to tell when this issue could be closed. Maybe an exhaustive check-and-fix of this problem is therefore necessary; it would probably make a [good first issue](https://github.com/SciTools/iris/labels/Good%20first%20issue)?

**Comment by trexfeathers** [comment]
>Possibly this will come out in the wash of #3840?

I would definitely expect so, but that's an even bigger piece to finish.

**Comment by rcomer** [comment]
Hmmm, now I've looked closer, this particular example was also wrong in the [legacy docs](https://scitools.org.uk/iris/docs/v2.4.0/iris/iris/plot.html?highlight=contour#iris.plot.contour) so not a readthedocs issue.  Looks like these docstrings were all re-jigged at #1942, so perhaps it is just this module? 🤔

**Comment by rcomer** [comment]
@trexfeathers thanks for your thoughts.  I have reduced the scope of this issue to the `iris.plot` module, which should make it a lot easier to close 🙂
