### ISSUE TITLE
Antialiased contourf plot shows unexpected artifacts

### ISSUE THREAD

**Issue by jamesp** [SciTools/iris#4086]
## 🐛 Bug Report

When plotting an iris cube with `contourf` in some circumstances an additional contour is shown.  This appears to be related to the logic included by the `antialiased` option in `iris.plot.contouf`.

## How To Reproduce
Steps to reproduce the behaviour:

1. Contact @jamesp for data and reproduction script 

## Expected behaviour
Antialiased data should not show additional artifacts when plotting.

## Screenshots
![image](https://user-images.githubusercontent.com/22805/114049558-7110db80-9883-11eb-9d5c-d45bfe866c98.png)

## Environment 
 - OS & Version: Linux
 - Iris Version: 3.0.1.  Affects Iris >= 2.3

**Comment by bjlittle** [comment]
@jamesp What version of `mpl` are you using?

**Comment by jamesp** [comment]
The antialiased artifact (additional contour) is present on all stack versions since Iris 1.13. 

I've tested on matplotlib 2.2.3 and 3.3.4, both show the same additional contour.  Setting `antialiased=False` restores the same behaviour as 1.13, which is what the user was running on previously.

I've tried to create a standardised test that reproduces the issue, but haven't achieved it yet, there does appear to be something pathological about the input data

**Comment by rcomer** [comment]
Here is a minimal example:

```python
import iris
import iris.quickplot as qplt
import numpy as np
import matplotlib.pyplot as plt


lats = np.linspace(-10, 10, 20)
lons_2d, lats_2d = np.meshgrid(lats, lats)

data = np.cos(lons_2d * np.pi/10.) + np.cos(lats_2d * np.pi/10.)
np.place(data, data < 0., 0.)

cube = iris.cube.Cube(data)
for dim, name in enumerate(['longitude', 'latitude']):
    cube.add_dim_coord(iris.coords.DimCoord(lats, standard_name=name, units='degrees'), dim)

levels = [0.2, 2, 20, 200]
colors = ['b', 'r', 'y']

qplt.contourf(cube, levels=levels, colors=colors)
```
![contourf_antialias1](https://user-images.githubusercontent.com/10599679/117773219-f5160480-b22f-11eb-8458-97cbd4dbe649.png)
The problem seems to be triggered by a combination of
* having zeros everywhere other than our desired feature
* data values all being below the second level

If we pick level so that all the colours are used, all seems well

```python
levels = [0.2, 0.5, 1, 2]
qplt.contourf(cube, levels=levels, colors=colors)
```
![contourf_antialias2](https://user-images.githubusercontent.com/10599679/117773215-f47d6e00-b22f-11eb-95ee-814499e611c4.png)
Since `iris.plot.contourf` does some subsetting of levels and colors, the problem boils down to

```python
sub_levels = [2, 20]
sub_colors = ['b', 'r']

qplt.contour(cube, levels=sub_levels, colors=sub_colors)
```
![contourf_antialias3](https://user-images.githubusercontent.com/10599679/117773213-f47d6e00-b22f-11eb-9afe-0471afe622c0.png)
which we also see if we plot directly with `matplotlib`

```python
plt.contour(cube.data, levels=sub_levels, colors=sub_colors)
```

![contourf_antialias4](https://user-images.githubusercontent.com/10599679/117773212-f3e4d780-b22f-11eb-96ba-87418fa585ef.png)

**Comment by rcomer** [comment]
https://github.com/matplotlib/matplotlib/issues/20203
