### ISSUE TITLE
iris.load() and iris.load_raw() interact differently with iris.util.equalise_attributes() when merging a CubeList

### ISSUE THREAD

**Issue by kaedonkers** [SciTools/iris#4097]
## 🐛 Bug Report
When using `iris.util.equalise_attributes(cubes)` before merging a CubeList, I noticed different behaviour based on whether I used `iris.load()` or `iris.load_raw()` to generate the CubeList.
`load_raw()` seems to lead to a successful equalisation of the attributes in the CubeList and a successful merge.
`load()` seems to successfully equalisation of the attributes in the CubeList but the merge results in the same as the input CubeList i.e. no merge, despite the input CubeList containing compatible cubes.

## How To Reproduce
Successful merge
```python
cubes = iris.load_raw(fnames)
iris.util.equalise_attributes(cubes)
cubes.merge()
```

Unsuccessful merge
```python
cubes = iris.load_raw(fnames)
iris.util.equalise_attributes(cubes)
cubes.merge()
```

Data to recreate this issue can be found at:
https://metdatasa.blob.core.windows.net/covid19-response/index.html#metoffice_ukv_daily--rain_mean

Specifically:
- ukv_daily_rain_mean_20210327.nc
- ukv_daily_rain_mean_20210329.nc
- ukv_daily_rain_mean_20210330.nc

## Expected behaviour
That both cases of the example code return exactly the same merged CubeList.

## Screenshots
![image](https://user-images.githubusercontent.com/32906197/114618537-5da9aa00-9ca1-11eb-8ef7-99e0c047fabd.png)

## Environment 
 - OS & Version: REHL7.9
 - Iris Version: 3.0.1

**Comment by pp-mo** [comment]
Hi Kevin !

I just responded to this.
But, we are all very tight on support time due to NG-VAT work, so I doubt I’ll be working on this myself.
In a couple of weeks we should be having a bit of a breather from the NG-VAT project, so there might be a bit of space to push this through then.

Cheers !
Patrick

From: Kevin Donkers ***@***.***>
Sent: 13 April 2021 21:51
To: SciTools/iris ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SciTools/iris] iris.load() and iris.load_raw() interact differently with iris.util.equalise_cubes.equalise_attributes() when merging a CubeList (#4097)


This email was received from an external source.   Always check sender details, links & attachments.

🐛 Bug Report

When using iris.util.equalise_attributes(cubes) before merging a CubeList, I noticed different behaviour based on whether I used iris.load() or iris.load_raw() to generate the CubeList.
load_raw() seems to lead to a successful equalisation of the attributes in the CubeList and a successful merge.
load() seems to successfully equalisation of the attributes in the CubeList but the merge results in the same as the input CubeList i.e. no merge, despite the input CubeList containing compatible cubes.

How To Reproduce

Successful merge

cubes = iris.load_raw(fnames)

iris.util.equalise_attributes(cubes)

cubes.merge()

Unsuccessful merge

cubes = iris.load_raw(fnames)

iris.util.equalise_attributes(cubes)

cubes.merge()

Data to recreate this issue can be found at:
https://metdatasa.blob.core.windows.net/covid19-response/index.html#metoffice_ukv_daily--rain_mean

Specifically:

  *   ukv_daily_rain_mean_20210327.nc
  *   ukv_daily_rain_mean_20210329.nc
  *   ukv_daily_rain_mean_20210330.nc

Expected behaviour

That both cases of the example code return exactly the same merged CubeList.

Screenshots

[image]<https://user-images.githubusercontent.com/32906197/114618537-5da9aa00-9ca1-11eb-8ef7-99e0c047fabd.png>

Environment

  *   OS & Version: REHL7.9
  *   Iris Version: 3.0.1

**Comment by rcomer** [comment]
Presumably `load_raw` is returning 24 2D cubes, and `merge` then creates the new time dimension.  `load` returns a pre-merged list, so the time dimension already exists, so you need `concatenate` rather than `merge` to join the two cubes together.

So this could be another one to add to the list at #3234?

**Comment by kaedonkers** [comment]
Good idea @rcomer - Done :)
