### ISSUE TITLE
Allowed cell method names not complete

### ISSUE THREAD

**Issue by jonseddon** [SciTools/iris#4151]
## ✨ Feature Request
The list of allowed cell method names in https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/netcdf.py#L166 doesn't include all of the allowed names in the CF conventions document at https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#appendix-cell-methods

## Motivation
I was looking into what cell method names were allowed and spotted the missing names.

## Additional context
`_CM_KNOWN_METHODS` is defined at https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/netcdf.py#L166 and then used at https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/netcdf.py#L232.

However, the Pyke rules at https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/_pyke_rules/fc_rules_cf.krb#L2299 also use something called `CM_KNOWN_METHODS` but I'm not sure where `CM_KNOWN_METHODS` is defined. Does Pyke do something clever and is the `CM_KNOWN_METHODS` in the Pyke rules taken from `_CM_KNOWN_METHODS` in netcdf.py?

**Comment by pp-mo** [comment]
Hi @jonseddon thanks for asking !

The mystery of how the Pyke rules manage to access something called `CM_KNOWN_METHODS` is simply that that routine (_parse_cell_methods)  is no longer used by the rules, never called, and the code has got out of date !
As I discovered when replacing it in the forthcoming #4170 .
In fact, you'll see that the constant's name has changed anyway : It is now `_CM_KNOWN_METHODS`  (no longer public).

( Talk about technical debt !! 
We've been rather too scared of that obscure rules code for a while now : we've rather avoided enquiring too deeply into it, not least since we have also long intended to replace it with pure Python, as we are now doing. 
)

To the serious question of what CF versions or features we support, I can only say that Iris makes **_no_** definitive statement.  
Though we write '1.7' into the conventions on output, that doesn't mean we can correctly handle all of CF1.7 (i.e. on input)
 -- in fact there is a great deal of CF-1.6 that we still don't "do".  
By stating CF-1.7 on output, we just mean that we aren't using any features **_not_** included in CF1.7.
In other words, the output is 'CF-1.6 compliant', which I think **_is_** correclty in line with what is intended in [the conventions](https://cfconventions.org/Data/cf-documents/requirements-recommendations/requirements-recommendations-1.7.html) (section 2.6.1).

In the meantime, the constants defined in the `iris.fileformats.netcdf` module were originally drawn from CF1.6, I think.  
Some of it is just there for possible future use though :  we don't actually _support_ all those options.  
For instance (apart from cell-methods), we don't support all of the grid_mapping types, even though that is a fairly short list and we do most of them :  **Completeness has just never been a goal in itself.**

I guess in fact we will probably _never_ be in a position to claim that we encompass all of a CF release, so it is all on a case-by-case basis.
Sorry if that seems arbitrary.  
I suppose we could provide a separate document stating what we do and do not handle, but I'm really not clear if that would actually help anyone much.  
**What is your view ?**

**Comment by ehogan** [comment]
I would also like to see the full list of cell methods in Iris :)

**Comment by trexfeathers** [comment]
We've discussed this further and have concluded that explicitly supporting any given cell method is a specific piece of work that takes some resource - because Iris may need to understand what that cell method does. So we are unable to blanket support all cell methods as standard 😥

If there is a specific cell method you need supported, please raise a specific issue, or even a PR - we'd love your help implementing it!
