### ISSUE TITLE
Leniently Comparing Coordinates

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#4153]
## ✨ Feature Request

Could we have some functionality in the public API that allows users to compare coordinates leniently?

## Motivation

I wanted to check two cubes were ordered consistently, so put this in my script:
```python
assert cube1.coord('realization') == cube2.coord('realization')
```
the assertion failed because one of the cubes had been saved as NetCDF and the other had not, so the `var_name`s clashed.  Since Iris v3, we have functionality under the arithmetic hood to make a _lenient_ comparison of coordinates.  It would be great if user code could directly access this functionality, so I could make a more useful assertion.

**Comment by bjlittle** [comment]
@rcomer Oohhhh lovely use case.

Seems totally possible to me. We'd need to think very carefully about how we control such lenient behaviour. Also, this is a nudge for us to perhaps start to think about other areas of `iris` that would benefit from lenient behaviour e.g., merge and concatenate are obvious contenders.

But this use case touches on a space that is rather powerful (and possibly surprisingly dangerous), as lenient coordinate equivalence is a BIG deal, because it occurs in many different places within `iris`. We'd need to think about how best to control such behaviour 🤔

**Comment by rcomer** [comment]
I wanted this again today, so knocked this together:

```python
def coords_equal(coord1, coord2) -> bool:
    """
    Lenient comparison of coordinates.
    
    """
    if not np.array_equal(coord1.points, coord2.points):
        return False
    
    if (coord1.has_bounds() and coord2.has_bounds() and
            not np.array_equal(coord1.bounds, coord2.bounds)):
        return False
    
    return coord1.metadata.equal(coord2.metadata, lenient=True)
```

It seems to work for my current example at least.
