### ISSUE TITLE
Less rationalisation of metadata during arithmetic

### ISSUE THREAD

**Issue by jonseddon** [SciTools/iris#4183]
## ✨ Feature Request
Lenient cube arithmetic is great and is allowing us to do new things. However, it would sometime be useful to keep some metadata.

## Motivation
Please see the metadata always rationalised at https://scitools-iris.readthedocs.io/en/stable/further_topics/lenient_maths.html#finer-detail​. When using arithmetic to remove a bias, e.g. `cube1 - cube2`​, then the underlying property is still air_temperature and the previous cell_methods are still valid and would be useful to keep them somehow, e.g. perhaps:​

```subtract(cube1, cube2, standard_name='air_temperature')```

**Comment by jonseddon** [comment]
It was suggested that @bjlittle might be the local expert on this.

**Comment by Peter9192** [comment]
This might also be relevant for https://github.com/ESMValGroup/ESMValCore/issues/651
That specific use case is about calculating anomalies, which is very similar to the bias use case.

**Comment by bjlittle** [comment]
@jonseddon The final step in cube arithmetic is [iris.analysis.maths._sanitise_metadata](https://github.com/SciTools/iris/blob/2db52283610a94cbf3a40675a0552e5db09bcb88/lib/iris/analysis/maths.py#L874), which honours the previous cube arithmetic behaviour prior to `iris` v3.0 and the introduction of lenient operations.

Preserving the `standard_name`, `long_name` and `var_name` **only** when lenient addition (`+`) and (`-`) has been performed seems to make sense to me, rather than purging that metadata regardlessly.

No special treatment has ever been performed for maintaining `cell_methods`, but without thinking about this too deeply, the **lenient** concession here might be to preserve `cell_methods` iff they exactly match for each cube operand, or the case where one cube operand has `cell_methods` and the other not. However, for the **strict** case the `cell_methods` must match, otherwise they are cleared.

Would this fit your use case @jonseddon ?

**Comment by jonseddon** [comment]
@bjlittle Thanks for taking the time to think about this! My colleague who suggested this is away for a few weeks but I'll have a chat with them when they're back and get back to you.

**Comment by bjlittle** [comment]
@jonseddon Is this still an issue for you?

It would be good to come to some conclusion to move forwards...
