### ISSUE TITLE
iris.plot does not always plot cloud base/top extent correctly

### ISSUE THREAD

**Issue by mo-avdjturp** [SciTools/iris#4381]
## 🐛 Bug Report

iris.plot does not always plot cloud base/top extent correctly. The plotted region is sometimes less than it should be.

## How To Reproduce
Steps to reproduce the behaviour:

1.  cube=iris.load(cloud_base_file)
2. contour_levels = np.linspace(0.0, 8000.0, 9.)
3. cf = iplt.contourf(cube[0], contour_levels)
4. plt.show()

(Example cloud base file is in /scratch/fpdh/CB/20210819T0600Z/20210819T0000Z_T+06_CB_base_test1_as_height.pp;
example cloud top file is in /scratch/fpdh/CB/20210819T0600Z/20210819T0000Z_T+06_CB_top_test1_as_height.pp)

## Expected behaviour

Cloud base field extent should be the same as cloud top field extent. (Independent testing and plotting with matplotlib.pyplot confirms that this should be the case).

Actual behaviour
Cloud base field extent is less than cloud top field extent.
When plotted with matplotlib.pyplot, the extents are the same.
(See example plots; plt=plotted with matplotlib.pyplot,  iplt=plotted with iris.plot)

## Environment 
 - OS & Version: [e.g., Ubuntu 20.04 LTS]
 - Iris Version: [e.g., From the command line run `python -c "import iris; print(iris.__version__)"`]
RHEL7
python-3.4.10
iris-2.4.0 (from scientific software stack - default-current environment)

## Additional context

<details>
<summary>Click to expand <b>this section...</b></summary>

```
Please add additional verbose information in this section e.g., code, output, tracebacks, screenshots etc
```
</details>
![Figure_1](https://user-images.githubusercontent.com/89387305/137705611-2b6f3774-0838-4f20-a272-83ac2c43bfba.png)

**Comment by wjbenfold** [comment]
From a bit of investigation, I think that this is being caused mostly (if not completely) by the antialiasing in iris.plot.contourf. I'm not too surprised that this issue is present in iris-2.4.0 given significant improvements were made in iris-3.1 (see https://github.com/SciTools/iris/pull/4127, https://github.com/SciTools/iris/pull/4150, https://github.com/SciTools/iris/issues/4086 and https://github.com/SciTools/iris/pull/4263).

However, I'm able to reproduce this in iris 3.2.dev0, suggesting there's an edge case that this data is hitting. Note that the matplotlib and "fixed" iris plots are not identical - there are ~1 pixel differences in various places.

matplotlib.pyplot.contourf

![good](https://user-images.githubusercontent.com/69585101/137889735-e1a410d5-40e0-4514-84e5-afe916b8e925.png)

iris.plot.contourf

![before_iris](https://user-images.githubusercontent.com/69585101/137889784-12b689a9-b1c5-4d99-a9a7-9b3a695005e0.png)

iris.plot.contourf (with undocumented kwarg antialiased=False)

![fixed_iris](https://user-images.githubusercontent.com/69585101/137889911-d492ce74-eed2-4350-b3e6-f2f36c819cb4.png)

@rcomer, as the person who last fixed some antialiasing, any advice before I look further as to what might be the culprit?
