### ISSUE TITLE
`pandas` no longer an `iris` dependency?

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#4442]
hey guys, quick question: latest iris build from 3 odd days ago:
```
(esmvalcore-stock-conda) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list iris
# packages in environment at /home/valeriu/miniconda3/envs/esmvalcore-stock-conda:
#
# Name                    Version                   Build  Channel
iris                      3.1.0              pyhd8ed1ab_3    conda-forge
```
does not require `pandas` as a dependency anymore - is this intended or a build/conda-feedstock fluke? Cheers muchos :beer: 

**EDIT** Actually I snooped around your setup requirements and it looks like you still need `pandas` (so we'll get our pandas from you) so it means it's a build issue :grin:

**Comment by rcomer** [comment]
I guess this is because of https://github.com/conda-forge/iris-feedstock/pull/77.  Previously `pandas` would have been pulled in as a dependency of `dask`, but this has been trimmed down.  It is listed as an optional dependency in Iris’s [setup.cfg]( https://github.com/SciTools/iris/blob/91b01be11ebd439668c3f140f66350b9e65db59e/setup.cfg#L87), so I think some parts of Iris need it, but Iris can be built and used without it.

**Comment by valeriupredoi** [comment]
cheers @rcomer - so what's the verdict here - you will include `pandas` as a build dependency and re-build the package or should we buy, ahem, include as dependency our own pandas? :panda_face:
