### ISSUE TITLE
Proj version 6.3.1 is installed, but cartopy requires at least version 8.0.0

### ISSUE THREAD

**Issue by wgwz** [SciTools/iris#4468]
System (Key Piece = Ubuntu Focal release):
```
wgwz@lookfar3:~$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
```

Output from installing iris (This occurs after installing system dependencies from the docs):
```
wgwz@lookfar3:~$ pip3 install scitools-iris
Collecting scitools-iris
  Downloading scitools_iris-3.1.0-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 2.4 MB/s 
Collecting scipy
  Downloading scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
     |████████████████████████████████| 39.3 MB 26 kB/s 
Collecting dask[array]>=2
  Downloading dask-2021.12.0-py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 2.6 MB/s 
Collecting cartopy>=0.18
  Downloading Cartopy-0.20.1.tar.gz (10.8 MB)
     |████████████████████████████████| 10.8 MB 47 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpo1kwll3p get_requires_for_build_wheel /tmp/tmppj1fg2d3
       cwd: /tmp/pip-install-iec1zo7n/cartopy
  Complete output (1 lines):
  Proj version 6.3.1 is installed, but cartopy requires at least version 8.0.0.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpo1kwll3p get_requires_for_build_wheel /tmp/tmppj1fg2d3 Check the logs for full command output.
```

libproj-dev from ubuntu focal (clearly v6.3.1): https://packages.ubuntu.com/focal/libproj-dev

I believe that the iris project needs to pin cartopy to a version that supports libproj 6.3.1. Otherwise the installation instructions are broken and need updates.

**Comment by rcomer** [comment]
@MHBalsmeier wrote those installation instructions, so he might like to comment.  However it looks like they were last tested before Cartopy 0.20 was released.  You could try installing the previous Cartopy version before installing Iris:
```
pip install cartopy==0.19.0.post1
```

**Comment by MHBalsmeier** [comment]
> @MHBalsmeier wrote those installation instructions, so he might like to comment. However it looks like they were last tested before Cartopy 0.20 was released. You could try installing the previous Cartopy version before installing Iris:
> 
> ```
> pip install cartopy==0.19.0.post1
> ```

That is correct. In order to install the latest version of cartopy from source (by which I mean without conda), one will have to manually install `proj>=8.0.0`. Several issues have been raised at cartopy related to this problem (https://github.com/SciTools/cartopy/issues/1970, https://github.com/SciTools/cartopy/issues/1967, https://github.com/SciTools/cartopy/issues/1879).

For now you can either

* use `cartopy==0.19.0.post1` or
* install `proj>=8.0.0` manually from source, instructions [here](https://proj.org/install.html#cmake).

I have mentioned at cartopy that I find this very suboptimal but there seems to be no motivation to change this and since I think Ubuntu 21.10 comes with proj < 8 this problem is to stay with us for a long time ...

**Comment by wgwz** [comment]
I see, thank you clarifying. That is very unfortunate. I do not want to install from source but it looks like there is no other choice in the matter. I also do not like using conda. This is disappointing but I understand there is not much for you to do in this project.

**Comment by MHBalsmeier** [comment]
> I see, thank you clarifying. That is very unfortunate. I do not want to install from source but it looks like there is no other choice in the matter. I also do not like using conda. This is disappointing but I understand there is not much for you to do in this project.

I agree. One could dig into cartopy and see if one can make it work with `proj<8`. Currently I have other priorities however and there are people who know better about this problem than I do, but you could comment on one of those cartopy issues I linked to raise awareness of this problem.

**Comment by rcomer** [comment]
Some upcoming relevant developments:

* Iris 3.2 should be released in the next couple of months, and that will have Cartopy [pinned at >=0.20](https://github.com/SciTools/iris/blob/3638874a63e9bbee72b062fe02a8e500982eb796/setup.cfg#L49).
* Ubuntu Jammy LTS is [due for release in April](https://ubuntu.com/about/release-cycle), and that [will have proj 8.2](https://packages.ubuntu.com/jammy/libproj-dev).
* There is talk in the [Cartopy gitter](https://gitter.im/SciTools/cartopy) of dropping `proj` altogether in favour of `pyproj`.

@wgwz @MHBalsmeier are you happy to close this issue?  We have a note in the installation guide that the instructions may need to be adapted.  Any details on _how_ to adapt them would likely become out-of-date faster than the Iris release cycle can keep up with, so I think would perhaps be better placed in the support forums rather than the documentation.

**Comment by MHBalsmeier** [comment]
I am okay with closing. The problem will most likely be solved by the updates in `proj` and `Ubuntu` within the next few months and then the manual installation instruction should be valid again.

**Comment by wgwz** [comment]
Yes, please feel free. Thanks for your feedback and added info!
