### ISSUE TITLE
Warn or error rather than returning None from name check in netcdf

### ISSUE THREAD

**Issue by wjbenfold** [SciTools/iris#4495]
## 📰 Custom Issue

Based on my understanding of situations where the following code can end up returning None, I think that it's unlikely that the user doesn't want to know that this is happening.

https://github.com/SciTools/iris/blob/main/lib/iris/fileformats/netcdf.py#L344-L362

From conversation with @pp-mo, we think this means we're not saving valid CF because the aux_factory gets saved with a None formula term. That seems worth telling the user about.

**Comment by pp-mo** [comment]
IIRC I did introduce this 'return None if not present' _intentionally_, because it made some code much simpler
 -- e.g. https://github.com/SciTools/iris/blob/main/lib/iris/fileformats/netcdf.py#L1531-L1537
 .. which previously looked like this : https://github.com/SciTools/iris/blob/cc574cba840dab13246008e567dfeb1dadb1adc4/lib/iris/fileformats/netcdf.py#L1385-L1391
 
Unfortunately, I think I must have missed the fact that in some other usages, we purposely _wanted_ this routine to fail in an invalid case.
