### ISSUE TITLE
iris.cube.Cube.intersection behaviour with minimum > maximum

### ISSUE THREAD

**Issue by wjbenfold** [SciTools/iris#4519]
## Current behaviour (as I understand it, though maybe there's something simple I've missed that helps)
* If the values provided to Cube.intersection include a minimum that is greater than the maximum then it returns a ValueError.
* To take an intersection that covers the edge of circular coordinates (e.g. the longitudes that enclose the Pacific), it's possible to refer to values outside of the range of your current coordinates (e.g. -220° to -70° even though your longitude coordinate ranges from -180° to 180°). This isn't necessarily an intuitive leap, and is poorly documented. This ability is used by some users to sort-of-regrid their data (moving the longitude range from 0°-360° to -180°-180°).

## Suggestions
* Can Cube.intersection be changed to allow a minimum greater than the maximum to be used to indicate the "back of the globe" in an intuitive way?
  * Users might do this accidentally - is that ok?
  * Does this behaviour apply intuitively to other coordinate units with a modulus too?
  * Does the discontinuity in the middle of the resulting longitude coordinate cause issues?
* If not, can we improve how this is communicated?
  * Can the error be more informative? e.g. prompting users towards the intended solution?
  * Can the documentation cover this (probably in the API docs)? Is it a common enough use to feature in the userguide? Or a future how-to section?

Raised after having the issue highlighted to me by @WilliamIngramAtmosphericPhysics

**Comment by WilliamIngramAtmosphericPhysics** [comment]
Thanks for opening this!

At first it seemed obvious to me:
1) Users should be able to use the code easily for any range of the coordinate, regardless of where the "join" happens to be, so they should not have to check where it is in every cube (e.g. "-90. to -60." should work for any cube, whether its coordinate happens to run from 0. to 360. or -180 to 180. or whatever.)
2) The test that the range increases makes no sense for a circular coordinate (though it does for a non-circular one).
3) The user should not be hit by any oddities in the output.

On that basis what should happen is making the test conditional on non-circularity, & making the code always work for a circular coordinate from the 1st value given towards increasing values till it reaches a value modulo-equal to the 2nd, & setting the coordinate in the output to a monotonically increasing sequence.

So my answers to Will's 1st set of questions are:
- Yes
  - Yes of course it's OK - users can do all sorts of things accidentally & this is no different
  - Yes of course
  - If there were a discontinuity it would - even if all iris code was fine with it it could confuse users.  So there shouldn't be one.  There isn't currently (in the case Will describes they would run continuously from -220. to -70.) & I suspect that this would come naturally, but if not it should be engineered.

But however obvious it seemed to me that all users would agree, maybe not, so I wanted to ask other users to confirm or correct!

Only then I did think "But do iris coordinates have to be increasing?", as the code concerned, Will & I had assumed.  And of course they don't.  Latitude & longitude always seem to in my experience, mostly with UM fields (which may account for the test having survived so far), but if, say, a cube has both height & pressure as coordinates one must be decreasing.  (It would be possible to start deprecating decreasing dim coords but that would make switching between e.g. height & pressure painful, might mess up any number of use cases, & is not consistent with the netcdf convention, so total overkill for this issue.)  On that basis the test makes no sense.  Yet with circular coordinates there are 2 possible ways from any value to any other & the convention "the range wanted is given by the coordinate increasing locally from the 1st value to the 2nd" seems simple & natural to me - but presumably not to anyone who is used to a decreasing circular coordinate.  Maybe they're rare enough nobody would mind?  (I have no doubt that to most people increasing series are more intuitive in general.)  Or maybe a 3rd argument is needed (which could default to "increasing")?

So I now think there should be no test even for non-circular coordinates.  Somebody might think that the input range should be consistent in direction with the coordinate it applies to (so the test would reverse if the coordinate decreased), but I don't think the user should not have to know details like that, or have to write code that checks for it.  If they ask for a range from a larger value to a smaller they should get what they ask for, given this is a perfectly valid cube.  (This is consistent with specifying an axis range to an iris plot - swapping the values flips the direction of the plot.)  Possibly there should be a warning message if the direction doesn't match the existing direction, but that could be very painful when reading in large amounts, so there should be a "quiet" switch.  Whatever's done needs to be well documented!

But what do other people think?

**Comment by wjbenfold** [comment]
> & setting the coordinate in the output to a monotonically increasing sequence.

How would you envisage this choice being made? I'm not concerned about increasing/decreasing - as you point out a coordinate can do either - but for it to be monotonic we'll have to relabel the values on one side of the coordinate boundary. We do this currently, but based on the explicit intent of the user, whereas here that choice may surprise them.

> So I now think there should be no test even for non-circular coordinates.

This function only currently works for circular coordinates, so we don't need to worry about this here - it would come under another issue I think.

**Comment by WilliamIngramAtmosphericPhysics** [comment]
> How would you envisage this choice being made?

However's easiest given the algorithm used, but I imagine it will be most convenient to start from the 1st value & increase to one modulo-equal the 2nd.  (The other almost-equally-natural option IMO would be to end at the 2nd having started from something modulo-equal the 1st.)  So if I specified 170. to -170. with the original coordinates running 180. to 180., I'd expect the easiest code to give 170. to 190., rather than -190. to -170.  But since there is no right answer either would be fine.  

> that choice may surprise them.

True, but I think the consequences of a non-monotonic coordinate will surprise them worse overall, & they shouldn't be too surprised as they should be used to the starting point of circular coordinates varying.  Yes, I think it would be best for the code to print a warning like "To ensure a monotonic "+coordinate name>+" coordinate in output that covers the 'wrap-around' in the input, values on one side of the 'wrap-around' differ by 360' from those specified to intersection" - as long again as it's easily switched off to stop one getting too many.  If they really want they can always add or subtract a modulus (OK, not *trivial* with .point & .bounds - is there a function to do that?  I can't see one).

But again, what do other users feel?

> This function only currently works for circular coordinates

Oh yes!  That is in the documentation, but hidden at the end, presumably because it is/was intended to generalize it.  In that case IMO the test should never have been there.

**Comment by bsherratt** [comment]
> If they really want they can always add or subtract a modulus (OK, not trivial with .point & .bounds - is there a function to do that? I can't see one).

I've always seen `Cube.intersection` as *being* that function (feel free to disagree though!). Want to work with coordinates in the range 0-360 but not sure whether what you loaded satisfies that? `cube.intersection(longitude=[0, 360])` will guarantee that every point, or at least one bound for coords with bounds, falls in the requested range. It also does not change whether the coord was increasing or decreasing.

From there, the obvious (to me) extension of its current behaviour would be to drop the direction-preserving part, so that an intersection with `[a, b]` still always returns points within the requested interval, but ensures increasing if `a < b` or decreasing if `b < a`. Continuing with the example of `[170, -170]`, this is actually the exact opposite of the suggestion to run from 170 to 190 (or -190 to -170, or -180 to -170 then 170 to 180), but I think makes more sense, precisely because it doesn't have those extra options of how exactly to label the selected points.

Also, while the method *is* currently restricted to circular coords, there is actually very little reason for that in the code. It just uses the modulus to wrap the points into the range `[a, a+modulus]`, so that it can subsequently intersect with `[a, b]` as if there is no modulus. The only change would be to skip that wrapping step if it doesn't make sense. Note that the above suggestion is not doing anything special based on the modulus either, which I'd say is a further advantage of it.

**Comment by WilliamIngramAtmosphericPhysics** [comment]
> I've always seen Cube.intersection as being that function

Oh!  Yes, now you've pointed that out I see it could be used that way (though the documentation doesn't mention the possibility, so I guess it hadn't occurred to its authors either!)  Maybe it is widely used like that?
(I'd assumed the system should work so the user doesn't normally need to bother with detail like that.)

> From there, the obvious (to me) extension of its current behaviour would be to drop the direction-preserving part

So you get literally what you ask for... this would mess up anyone who asks for 170 to -170 wanting 20' in the mid-Pacific, but if the documentation clearly said that's what happens, it would be quite simple, with the output coordinate values just matching the specification.

Yes, maybe that would be best.

**Comment by rcomer** [comment]
> the obvious (to me) extension of its current behaviour would be to drop the direction-preserving part, so that an intersection with [a, b] still always returns points within the requested interval, but ensures increasing if a < b or decreasing if b < a

This would assume that `a == first` and `b == last` but the current documentation states that `a == min` and `b == max`.  I have a NCEP/NCAR reanalysis file on disk where the latitude coordinate is decreasing.  If I do `cube.intersection([0, 10])` on these cubes I currently get a latitude coordinate that runs from 10 to 0.  So I think this proposal would be a breaking change (of course that doesn't mean we could never do it!)  Note that you can instead pass a `CoordExtent` object, though I never have and I do not know what the implications of that are.

I think all the suggestions in this thread seem entirely reasonable and do-able, but the discussion feels a bit abstract to me.  Do we know of specific use-cases that are being hampered by the strictness of the current functionality?

**Comment by WilliamIngramAtmosphericPhysics** [comment]
> I do cube.intersection(latitude=[0, 10])

You shouldn't be able to - as @wjbenfold pointed out, the code is supposed to work only on circular coordinates!

But yes, of course you're right that we should be wary of changing output where code currently does something usable & maybe used & relied on by some users.
Maybe a new name should be used & .intersection deprecated or discouraged.

> Do we know of specific use-cases that are being hampered by the strictness of the current functionality?

Well, this came up because I wanted to plot quantities over near-equatorial oceans over the range where these exist, i.e. from the E coast of Africa at about 41'E right round Eastwards to the W coast of Africa at about 13'E, & the current code & documentation were not user-friendly.
I do now think (but may change my mind again!) that @bsherratt's suggestion is how such code should work & should always have worked (probably with a check that the range is no greater than the modulus), but I don't feel this improved interface needs to be a breaking change to the current name (which has always been uninituitive to me, actually, though I expect that's just me - it was presumably been intuitive to whoever named it!)

**Comment by rcomer** [comment]
> > I do cube.intersection(latitude=[0, 10])
> 
> You shouldn't be able to - as @wjbenfold pointed out, the code is supposed to work only on circular coordinates!

Unfortunately there is some ambiguity here: the `intersection` documentation defines circular coordinates as "those where the units attribute has a modulus defined".  But there is also a boolean `circular` attribute on the `Coord` object that should only be `True` if the whole modulus range is spanned (i.e. it can't be `True` for latitude as you say).

**Comment by wjbenfold** [comment]
To summarise where this conversation seems to have reached:

- Cube.intersection could accept "backwards" coordinate values, and treat them as an instruction to reverse the axis as it took that intersection.

- The documentation (be it docstring, error message or any potential additions to the userguide) should be clearer what the behaviour is - including William's initial concern about how to take a section of coordinate that crosses the boundary, and Barnaby's use case (which I believe to be widespread) of getting the range of a circular coordinate to be where you want it.

- Support for non-circular coordinates doesn't seem too tricky and might be useful.

Is that a fair summary?

**Comment by wjbenfold** [comment]
> Note that you can instead pass a `CoordExtent` object, though I never have and I do not know what the implications of that are.

I think, from my last visit to this code, that these are basically just wrappers on a tuple @rcomer

**Comment by WilliamIngramAtmosphericPhysics** [comment]
> Unfortunately there is some ambiguity here: the intersection documentation defines circular coordinates as "those where the units attribute has a modulus defined". But there is also a boolean circular attribute on the Coord object that should only be True if the whole modulus range is spanned (i.e. it can't be True for latitude as you say).

***OUCH!***  I had seen the definition in the intersection documentation & read it as meaning that any value is valid but there is effectively a finite range as values separated by an integral multiple of the modulus are equivalent.  You're saying that it has a 2nd meaning that only some values are valid, & also values separated by an integral multiple of the modulus are equivalent?  So latitudes could be expressed as -90 to 90 or 270 to 540 or...?
That seems a *very* bad idea to me.  I can't imagine any good reason for it.  It certainly doesn't fit the natural meaning of "circular" where you can go on for ever & never come to anywhere "outside" the circle.

But maybe it was deliberately created for some reason I'm missing?  If so, it should have a different name, surely?  (Though I suppose we are getting beyond the scope of this issue, assuming @rcomer's comment applies more widely than just intersection.)

**Comment by WilliamIngramAtmosphericPhysics** [comment]
>  Cube.intersection could accept "backwards" coordinate values, and treat them as an instruction to reverse the axis as it took that intersection.

What do you mean by "backwards"?
The 1st half of that sentence implies to me "1st value larger than 2nd" as that's what's not currently allowed, but the 2nd half implies to me "opposite direction to the existing axis" as that'd be when you'd reverse it on @bsherratt's suggestion (which is basically that it would return what you asked for).

**Comment by wjbenfold** [comment]
> What do you mean by "backwards"?

Such that for a coordinate that starts with integer value 0-9 and modulus 10 you get the following results:

(supplied values) -> [final coordinate values]
(4.5, 7.5) -> [5, 6, 7]
(7.5, 4.5) -> [7, 6, 5]
(14.5, 17.5) -> [15, 16, 17]

**Comment by rcomer** [comment]
I just remembered there is also a proposal to make `intersection` work with 2D coordinates - #4197.  I’m not sure that the two proposals would be compatible, as 2D coordinates don’t really have a direction.

**Comment by WilliamIngramAtmosphericPhysics** [comment]
Wow, you do know iris well, @rcomer!

> 2D coordinates don’t really have a direction.

Don't they?
The example in [#4197](https://github.com/SciTools/iris/issues/4197#4197) seems to me to have a direction in both coordinates.

But maybe not always, which may be more evidence that rather than altering intersection, there should be a new name?

**Comment by trexfeathers** [comment]
This could do with a review to see whether it's going to be actioned or not.
