### ISSUE TITLE
Distorted iplt.points with circular coordinate

### ISSUE THREAD

**Issue by isedwards** [SciTools/iris#466]
`iplt.points()` distorts the output when longitude coordinate is circular.  The second plot below shows the correct behaviour by setting circular to false: `cube.coord('longitude').circular = False`

Also, the current API documentation suggests that `points()` requires a list of coords as arguments, but the current implementation expects a cube.

![figure_1](https://f.cloud.github.com/assets/2097922/396856/847e94f6-a830-11e2-9bda-4061c0f1cd56.png)

```
import iris.tests as tests
import iris
import iris.plot as iplt
import matplotlib.pyplot as plt

plt.switch_backend('tkagg')
pp_file = tests.get_data_path(('PP', 'globClim1', 'u_wind.pp'))
cube = iris.load(pp_file)[0][0]

plt.subplot(211)    
iplt.pcolormesh(cube, vmax=50)
iplt.points(cube, s=cube.data)
plt.gca().coastlines()
ax1 = plt.gca()

plt.subplot(212)
cube.coord('longitude').circular = False
iplt.pcolormesh(cube, vmax=50)
iplt.points(cube, s=cube.data)
plt.gca().coastlines()
ax2 = plt.gca()

plt.show()
```

**Comment by wjbenfold** [comment]
Hi @isedwards, is this still something that affects you / can be replicated? I realise things have moved on a long way since you first raised this

**Comment by rcomer** [comment]
I just tried the example from the OP with a recent environment (Iris 3.1.0, Matplotlib 3.4.2) and got an exception

```
ValueError: s must be a scalar, or float array-like with the same size as x and y
```
which seems to match @pelson's diagnosis

> The problem is that cube.data is the wrong shape for the points being plotted when you have a circular coordinate

I think [here](https://github.com/SciTools/iris/blob/0852e1ebe7481f0e2a8bcf7665d5179d3496dce7/lib/iris/plot.py#L974-L988) we add an extra column to the cube.data to be plotted.  I guess to make it work we would need to do the same for `s`.

**Comment by wjbenfold** [comment]
I think we could check every kwarg for being an array with the right length for dimension 1 and extending any that that's the case for - does that seem reasonable @rcomer? I've not done much in plotting code so don't know if we'd want to do that, or maybe just extend any dimension that's the right length regardless of which one it is?

**Comment by rcomer** [comment]
> I think we could check every kwarg for being an array with the right length for dimension 1 and extending any that that's the case for - does that seem reasonable @rcomer?

I was thinking similarly, though I'm not particularly familiar with this module either.  Maybe it's enough to check whether `val.shape == cube.shape`, though I note that `cube.data` will be [transposed if necessary](https://github.com/SciTools/iris/blob/0852e1ebe7481f0e2a8bcf7665d5179d3496dce7/lib/iris/plot.py#L969-L972) to enforce that "X" is dimension 1.  I also just noticed that `c` does get auto-transposed to match, but only for the non-map case, which seems odd to me.
https://github.com/SciTools/iris/blob/0852e1ebe7481f0e2a8bcf7665d5179d3496dce7/lib/iris/plot.py#L511-L516

If you do `cube.transpose()` before plotting the second (working) example from the OP, you get a mess!  I think this is because `scatter` doesn't check the shape of the `s` array, only its size.

**Comment by wjbenfold** [comment]
I think it seems reasonable to generally assume that the user provided bonus data in the same shape as the original data and to expect that debugging to be on them if they haven't (not sure if we can spot it and warn politely, though possibly it's best to pass it to matplotlib to deal with regardless). Based on the comment in your example lines, I'd guess that the automatic transposition of `c` was implemented to hide that matplotlib had stopped being so helpful.
