### ISSUE TITLE
Lockfile action failed to resolve environment

### ISSUE THREAD

**Issue by rcomer** [SciTools/iris#5139]
## 📰 Custom Issue

👀 https://github.com/SciTools/iris/actions/runs/3972226328/jobs/6809909691#step:3:1104

**Comment by trexfeathers** [comment]
Might be worth running in a few more days in case a fix is on its way.

**Comment by trexfeathers** [comment]
Another possible thing to try would be to use a vanilla Mamba install instead of [our current workflow](https://github.com/SciTools/workflows/blob/e379d6d6d870679a52d91a2b71af4642c81571f5/.github/workflows/refresh-lockfiles.yml#L50-L58) (which was necessary at the time, but don't think that's still true).

```python
        run: |
          source $CONDA/bin/activate base
          conda install -y -c conda-forge conda-libmamba-solver conda-lock libarchive=3.5.2=h5de8990_0
      - name: generate lockfile
        env:
          CONDA_EXPERIMENTAL_SOLVER: libmamba
        run: |
          $CONDA/bin/conda-lock lock -k explicit -p linux-64 -f requirements/ci/${{matrix.python}}.yml
          mv conda-linux-64.lock ${{matrix.python}}-linux-64.lock

```

**Comment by rcomer** [comment]
#5163 👀

**Comment by trexfeathers** [comment]
The failure was previously during updating the `base` environment in the workflow - resolution failed - so I assume that a new package release has made enabled environment resolution where it wasn't possible before.
