### ISSUE TITLE
saving cubes with masked cell measures

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris#5147]
Hey guys, how's it going? We're hitting an issue with saving cubes that have masked cell measures attached to the main variable, see https://github.com/ESMValGroup/ESMValCore/issues/1917 - I don't really understand the issue with this, so long as one supplies the saver with a valid `fill_value` (like we do, the infamous 1e20) - is this something that's a bit legacy or you're still afraid of it? Cheers muchly :beer:

**Comment by trexfeathers** [comment]
@valeriupredoi this originally stemmed from a desire to align as-close-as-possible to CF. But from discussion today we can't see a practical reason why cell measures shouldn't be masked.

So we'll leave this open as a future development task. If this is a priority for you please let us know.

**Comment by pp-mo** [comment]
> we can't see a practical reason why cell measures shouldn't be masked.

Oh dear, I think it was me said that.
Now I looked at the code, where this is [specifically dis-allowed for cell-measures only](https://github.com/SciTools/iris/blob/v3.4.0/lib/iris/fileformats/netcdf/saver.py#L1930-L1938)

This test was added as a specific exclusion in [this PR](https://github.com/SciTools/iris/pull/2513)
 -- though the code has since been refactored somewhat, so it's not that obvious.

The argument given is "We can't save masked points properly, as we don't maintain a fill_value"
I guess the danger envisaged is that we might have masked data with a specific fill-value set on the array, and we don't support any way of making _that_ the fill-value actually recorded in the netcdf file, so it could generate missing-point collisions.  
We can avoid it for _cube_ data (only), by specifying fill_value(s) in the save operation.

Altogether It's a pretty theoretical idea of a potential problem : points masked in the array will be saved as default-missing-value, but there _might_ also be unmasked points with that value :  Highly improbable, except for integer data.
And [this code](https://github.com/SciTools/iris/blob/v3.4.0/lib/iris/fileformats/netcdf/saver.py#L2485-L2510) is supposed to detect and (at least) warn about that occurrence.

So, I really don't _agree_ with this argument -- and especially as it should apply equally to aux-coords, and ancillary variables (added much more recently), and those we _don't_ disallow.

So I think if all agree we could quickly make a change to just remove this check 
**Any contrary opinions ?**  speak now !

**Comment by valeriupredoi** [comment]
cheers gents! Not a priority nor anything stringent for us, just thought I'd raise a flag or two - if you guys decide to keep it we'd be finding a workaround, and in fact, one of @bouweandela 's current PRs (in ESMValCore) is inadvertently fixing this :+1:

**Comment by valeriupredoi** [comment]
> cheers gents! Not a priority nor anything stringent for us, just thought I'd raise a flag or two - if you guys decide to keep it we'd be finding a workaround, and in fact, one of @bouweandela 's current PRs (in ESMValCore) is inadvertently fixing this +1

Nevermind the second part of my statement - that was a bug, that is now fixed, so we're back at hitting this. It'd be cool if you guys removed the raise as @pp-mo mentions, or both the check and raise :grin:

**Comment by trexfeathers** [comment]
> hey guys - we're still hitting this with `iris=3.4.1` - not sure why you folks closed the issue 😕

Hi @valeriupredoi, this feature was first available in `v3.5.0rc0`. See 897a7cbb9547d76aedb5b60deef7fbc8a61f9240:

![image](https://github.com/SciTools/iris/assets/40734014/8119fbb1-437b-457f-abed-cef1386efdcc)

**Comment by valeriupredoi** [comment]
ahaa cheers @trexfeathers - let me update then, thanks for the heads up, I jumped the (version) gun

**Comment by valeriupredoi** [comment]
with iris=3.5 all goes smoother than a Ferrari's paint work, many thanks @trexfeathers and the iris gang :beer:
