### ISSUE TITLE
iris.save regridding dataset with extra auxiliary dimensions

### ISSUE THREAD

**Issue by dannymcculloch** [SciTools/iris#5151]
## 🐛 Bug Report

I've created a copy of an AMIP suite I'm running to test some localised heating. The base suite has no changes while the copy of the suite has some minor change to the radiation code. Both models are then run for a couple of months and the output between them is compared. Both suites have the same STASH requests and output streams, but - when running the original suite, I added orography to check where 0° longitude was. This caused all other STASH outputs within the same `pp` file to have the `surface_altitude` auxiliary coordinate and `altitude` derived coordinate _in addition_ to the standard `level_height` and `sigma` auxiliary coordinates. This isn't a problem by itself, but when saving the cube to a new `.nc` file, the new `.nc` file has the `level_height` coordinate _replaced_ with `atmosphere_hybrid_height_coordinate` and starts at a different level to `level_height` (added a plot to show this). 

## How To Reproduce
Steps to reproduce the behaviour:

1. Have identical datasets (a copy from the suite will do) but add orography (`m00s00i033`) to one of the `pp` output streams
2. Load in both datasets individually, extract the cube of your choice **that has a vertical coordinate using `model_level_height`** (I'm using `m01s00i211`, but the issues occurs with all cubes that have that vertical coordinate system).
3. Append the extracted cube to a new cubelist
4. Save the new cubelist
5. Load in the new cube and the `level_height` vertical coordinate _should_ be changed to `atmosphere_hybrid_height_coordinate`

## Expected behaviour

The new cube saved should **not** have the `level_height` coordinate changed, but should just keep the original auxillary coordinates. Unless this is an intended "feature" I'm unaware of (have looked in the docs, can't find anything that suggests this)

## Screenshots

Original cube from data that that **does** contain the orography field with the output file
![image](https://user-images.githubusercontent.com/74662033/217527693-2b93d419-aa04-480b-927b-d947f1ef7c61.png)

Original cube from data that that **does not** contain the orography field with the output file
![image](https://user-images.githubusercontent.com/74662033/217527562-4f66bbd8-585f-4c35-bdca-55f86e24ddad.png)

Saved cube from data that that **does** contain the orography field with the output file
![image](https://user-images.githubusercontent.com/74662033/217527808-e475d8ff-e546-4b90-8713-9a85d2347a83.png)

Saved cube from data that that **does not** contain the orography field with the output file
![image](https://user-images.githubusercontent.com/74662033/217527828-d1c9133f-ff55-4d5b-b0dc-30697307fc36.png)

Plotting both cubes against each other using `atmosphere_hybrid_height_coordinate` (black) and `` `level_height` (blue). You can see how the data points are transformed in the cube that originally featured the orography STASH request.
![image](https://user-images.githubusercontent.com/74662033/217531115-3e54e7b6-33da-46b8-a031-053a3dfe54db.png)

## Environment 
 - OS & Version:   Date: Wed Feb 08 11:07:34 2023 GMT

                  OS : Linux
              CPU(s) : 72
             Machine : x86_64
        Architecture : 64bit
                 RAM : 157.3 GiB
         Environment : Jupyter
         File system : ext4
         GPU Details : error
 - Iris Version: 3.1.0

## Additional context
Happy to provice more info on request. Since saving the `pp` output files is the crux of the issue - I'm not sure how to upload the dataset that doesn't amount to excessive data usage. Happy for suggestions to help error replication though!

cc @dennissergeev who helped with the issue but also thought it might be a bug

**Comment by trexfeathers** [comment]
Hi @dannymcculloch,

This is expected behaviour when saving a hybrid height coordinate - it takes the place of its primary coordinate ([see these lines](https://github.com/SciTools/iris/blob/ba77f5d08f33524bd38ea6a55df3efc50bbdd53f/lib/iris/fileformats/netcdf.py#L1528-L1530)).

So we're perplexed on how you produced the plot above. Could you provide the code for this? Thanks

**Comment by dannymcculloch** [comment]
Hi @trexfeathers, thanks for the response. 
If supposed to regrid the cube and replace the `level_height` coordinate with `atmosphere_hybrid_height_coordinate` then I'm not sure it's doing so correctly. It seems that it's shifting the vertical coordinate upwards, but the data is staying the same and **not** just being reflected in the regridded cube. In other words, if you look at Y winds (picked this one because there's a nice oscillation near the surface, where other variables tend to just increase/decrease gradually with height, so it's harder to see.. but it's still there in other variables) below, both datasets feature the same oscillation, but in the regridded version, it's compressed and starts higher.

![image](https://user-images.githubusercontent.com/74662033/223084857-66c1d517-f520-4416-bec3-1f0bdf661b98.png)

The way I created the dataset with the blue line is by outputting data into a stream `.pp` file **without** orography being outputted into that file. Inversely, the way I created the dataset was by outputting the data used into a stream where I also output the orography field (`m00s00i033`, no matter the time profile - it adds the auxiliary coordinate). I then load the cube in with `iris` and save it. I did this for both datasets and in the scenario **with** the orography field (aka: the _base_ scenario), it adds cubes to the `.nc` file with surface altitude fields in between the cubes which I add 


The save function I have, which goes through the output stream for each scenario, year and month, then saves them to a `.nc` file is as follows
To specify the dates and datasets to extract:
```
scenarios = [f"u-co764", f"u-co764_heating"]
years = ["2000"]
months = ["oct"]
```
Then to save, it extracts the correct variable with the correct time profile (I'm using monthly meaned output):
```
diag = True # Good for keeping track of progress, set to False if you want to avoid lots of Print statements
for i in range(0,len(scenarios)):
    for j in range(0,len(months)):
        for k in range(0,len(years)):
            cubelist = iris.cube.CubeList()

            if diag == True:
                print('\033[1m' + 'Starting clouds' + '\033[0m')
            # Clouds

            cloud_area = iris.load(files[i], "cloud_area_fraction_in_atmosphere_layer")
            cloud_area = cloud_area[0] # This is lazy loading, but will do for now. Loading with a time profile constraint would be cleaner
            cubelist.append(cloud_area)
            if diag == True:
                print("Cloud area done")
            # break
            conv_cld = iris.load(files[i], "Convective cloud amount with anvil")
            conv_cld = conv_cld[0]
            cubelist.append(conv_cld)
            if diag == True:
                print("Convective cloud amount with anvil done")

            cloud_vol = iris.load(files[i], "cloud_volume_fraction_in_atmosphere_layer")
            cloud_vol = cloud_vol[0]
            cubelist.append(cloud_vol)
            if diag == True:
                print("Cloud volume done")

            cloud_ice = iris.load(files[i], "mass_fraction_of_cloud_ice_in_air")
            cloud_ice = cloud_ice[0]
            cubelist.append(cloud_ice)
            if diag == True:
                print("Cloud ice done")

            cloud_liq = iris.load(files[i], "mass_fraction_of_cloud_liquid_water_in_air")
            cloud_liq = cloud_liq[0]
            cubelist.append(cloud_liq)
            if diag == True:
                print("Cloud liquid done")



            if diag == True:
                print('\033[1m' + 'Clouds done' + '\033[0m')

            up_lw_cld = iris.load(files[i], "upwelling_longwave_flux_in_air")
            up_lw_cld = up_lw_cld[0]
            cubelist.append(up_lw_cld)
            if diag == True:
                print("Up-LW-cloudy done")

            up_lw_clear = iris.load(files[i], "upwelling_longwave_flux_in_air_assuming_clear_sky")
            up_lw_clear = up_lw_clear[0]
            cubelist.append(up_lw_clear)
            if diag == True:
                print("Up-LW-clear done")

            up_sw_cld = iris.load(files[i], "upwelling_shortwave_flux_in_air")
            up_sw_cld = up_sw_cld[0]
            cubelist.append(up_sw_cld)
            if diag == True:
                print("Up-SW-cloudy done")

            up_sw_clear = iris.load(files[i], "upwelling_shortwave_flux_in_air_assuming_clear_sky")
            up_sw_clear = up_sw_clear[0]
            cubelist.append(up_sw_clear)
            if diag == True:
                print("Up-SW-clear done")

            down_lw_cld = iris.load(files[i], "downwelling_longwave_flux_in_air")
            down_lw_cld = down_lw_cld[0]
            cubelist.append(down_lw_cld)
            if diag == True:
                print("Down-LW-cloudy done")

            down_lw_clear = iris.load(files[i], "downwelling_longwave_flux_in_air_assuming_clear_sky")
            down_lw_clear = down_lw_clear[0]
            cubelist.append(down_lw_clear)
            if diag == True:
                print("Down-LW-clear done")

            down_sw_cld = iris.load(files[i], "downwelling_shortwave_flux_in_air")
            down_sw_cld = down_sw_cld[0]
            cubelist.append(down_sw_cld)
            if diag == True:
                print("Down-SW-cloudy done")

            down_sw_clear = iris.load(files[i], "downwelling_shortwave_flux_in_air_assuming_clear_sky")
            down_sw_clear = down_sw_clear[0]
            cubelist.append(down_sw_clear)
            if diag == True:
                print("Down-SW-clear done")

            if diag == True:
                print('\033[1m' + 'Radiation variables done' + '\033[0m')
            # Air
            air_temp = iris.load(files[i], "air_temperature")
            air_temp = air_temp[4]
            cubelist.append(air_temp)
            if diag == True:
                print("Air temperature done")

            air_pres = iris.load(files[i], "air_pressure")
            air_pres = air_pres[0]
            cubelist.append(air_pres)
            if diag == True:
                print("Air pressure done")

            pot_temp = iris.load(files[i], "air_potential_temperature")
            pot_temp = pot_temp[0]
            cubelist.append(pot_temp)
            if diag == True:
                print("Potential temperature done")

            spec_humid = iris.load(files[i], "specific_humidity")
            spec_humid = spec_humid[2]
            cubelist.append(spec_humid)
            if diag == True:
                print("Specific humidity done")

            if diag == True:
                print('\033[1m' + 'Air variables done' + '\033[0m')

            # Winds
            x_wind = iris.load(files[i], "x_wind")
            x_wind = x_wind[3]
            cubelist.append(x_wind)
            y_wind = iris.load(files[i], "y_wind")
            y_wind = y_wind[3]
            cubelist.append(y_wind)
            z_wind = iris.load(files[i], "upward_air_velocity")
            z_wind = z_wind[1]
            cubelist.append(z_wind)
            if diag == True:
                print("Winds done")
            fname = f"{save_dir}{scenarios[i]}/"

            iris.save(cubelist, str(fname+"combined-" + months[j] + years[k] + ".nc"))
            print('\033[1m' + f" Scenario {scenarios[i]} - month {months[j]} - year {years[k]} done" + '\033[0m')
```

This creates the following cubes
The base combined cube (_base_comb_):
![image](https://user-images.githubusercontent.com/74662033/223088695-7cf688d8-af9b-456a-9dd4-4d3fb6e8b7f8.png)
The cube without orography in the output stream (_scen_comb_):
![image](https://user-images.githubusercontent.com/74662033/223088851-5c2ca98e-d8fd-4bc1-ab6f-9b2fd65adebc.png)

I've since rerun the suites with/without orography outputted into the output stream file%, and can confirm that adding/removing the orography STASH request creates/doesn't create the `altitude` auxiliary coordinate for all other variables in the `.pp` file. 

This can be replicated by running any suite and adding/removing orography from the STASH output from a given `.pp` file, then loading in that output and saving with `iris`. As I said at the start of this, it wouldn't be much of an issue if it's just regridding the dataset, but it seems to be shifting the whole dataset upwards (keeping the original values).

If you'd like me to clarify anything/give any extra info, just ask... TYI! 😄 

% the _scen_ suite was just a copy of the _base_ suite with a change to the radiation code, so they should be the same, but just wanted to make sure by changing both so they're identical.

**Comment by stephenworsley** [comment]
Hi @dannymcculloch, thanks for the information. I'm afraid I'm still having some difficulty interpreting this. As far as I can tell, the main difference between `base_test` and `scen_test` demonstrated by this code is that they are deriving from different files. I also don't know what the functions `m_m` and `z_m` are doing. I don't have access to these files so I can't tell you if the changes you're seeing are due to the way these files have been generated or due to a problem with the way iris is handling them.

I think in order to progress this we will need a minimal reproducible example. There are currently quite a few steps in your process and quite a few variables you are handling. If possible could you trim this down to as few steps and variables as possible to demonstrate the point at which you believe iris is behaving unexpectedly? Ideally, this would be using a file which we both have access to, but if that's not possible, then it would be usefull to print out the cube list and all its contents at each step of the process. It would be good to know if there is a noticable difference between the cubes after saving and loading as a PP file without having to save and load with NetCDF, or if it is possible to demonstrate this problem without having to save as a PP file.

I've looked a little through the code myself and it looks like something like this logic might be causing this https://github.com/SciTools/iris/blob/e7a8f312816508b08418ea476a151eacbfa999cf/lib/iris/fileformats/pp_save_rules.py#L786-L802
If this is the case, a minimal script could look something like this:
```python
cube_no_orog = ...  # Add code for generating this cube
cube_with_orog = ...  # Add code for generating this cube
print(cube_no_orog)
print(cube_with_orog)

iris.save(cube_no_orog, "no_orog.pp")
iris.save(cube_with_orog, "with_orog.pp")

cube_no_orog_loaded = iris.load_cube("no_orog.pp")
cube_with_orog_loaded = iris.load_cube("with_orog.pp")
print(cube_no_orog_loaded)
print(cube_with_orog_loaded)
```

**Comment by dannymcculloch** [comment]
Also, just to add:
The issue can be bypassed by running both scenario simulations with the exact same stash requests (i.e. either **both** with or without `orography`).
The motivation for keeping this open and understanding more about why `iris.save` is changing the dimensions is because it looks like its compressing the data near the surface - and I don't think that should be happening

**Comment by trexfeathers** [comment]
Hi again @dannymcculloch. We appreciate all the detail, and we appreciate your difficulty in sharing the large original files. Unfortunately we do not have the means/skill to run models ourselves, but what you have said has helped fill the gaps.

Below is a cut down 'replication' of your plots, which anyone that has Iris and [iris-sample-data](https://github.com/SciTools/iris-sample-data) can run.

Since the 1990's, height in PP files from the UM (the standard use case) has been represented as 'hybrid height' - height above surface, rather than above sea level. As such there is a lot of dedicated handling for this within Iris. Height-above-surface is automatically used when plotting - the black lines - and also handled in a specific way when saving (https://github.com/SciTools/iris/issues/5151#issuecomment-1452073921). @pdearnshaw was kind enough to confirm for me that this is the intended behaviour.

Your desired behaviour - demonstrated by the blue lines on the plot - will only be observed when the surface altitude is unavailable and Iris must fall back on interpreting as height-above-sea-level. If this is truly the correct behaviour in your case then you need to do one of the following:

- Correctly set the LBVC value in the file - **definitely the preferred option**.
  - [Official documentation](https://artefacts.ceda.ac.uk/badc_datadocs/um/umdp_F3-UMDPF3.pdf) - see section `4.2.26`
  - [Iris documentation](https://scitools-iris.readthedocs.io/en/stable/techpapers/um_files_loading.html#vertical-coordinates)
- Manually remove the `altitude` derived coordinate from loaded Iris `Cube`s.
- Be careful not to include `surface_altitude` in any files you are processing.


<details><summary>Expand for plotting demonstration</summary>

```python
"""
Script to demonstrate the effect of a hybrid height coordinate on default
plotting in Iris.
"""

import iris
import iris.analysis
import iris.cube
import iris.quickplot as qplt
import matplotlib.pyplot as plt


# Load Iris' basic hybrid height demonstrator.
file_path = iris.sample_data_path("hybrid_height.nc")
air_pot_temp = iris.load_cube(file_path, "air_potential_temperature")
# Mean across the horizontal dimensions, leaving just the height dimension.
air_pot_temp_mean = air_pot_temp.collapsed(
    ["grid_latitude", "grid_longitude"],
    iris.analysis.MEAN
)
print(air_pot_temp_mean)

# Remove the derived `altitude` coordinate, which makes 
#  `atmosphere_hybrid_height_coordinate` behave like a non-hybrid coordinate.
no_hybrid_height = air_pot_temp_mean.copy()
no_hybrid_height.remove_coord("altitude")
print(no_hybrid_height)

# Plot the two Cubes together...


def plot_cube(cube: iris.cube.Cube, color: str, label: str):
    """Reusable plotting code."""
    qplt.plot(
        cube,
        color=color,
        label=label,
        linestyle="-",
        marker="+",
        markersize="10"
    )


plot_cube(air_pot_temp_mean, color="black", label="with hybrid height")
plot_cube(no_hybrid_height, color="blue", label="without hybrid height")
plt.legend(loc="lower right")
plt.ylabel("Height (m)")

plt.savefig("hybrid_height_demo.png")

```

![hybrid_height_demo](https://user-images.githubusercontent.com/40734014/232818107-86fdc4c5-b3f9-43c5-95e4-0aa2063854ec.png)


</details>

**Comment by dannymcculloch** [comment]
Hi @trexfeathers, sorry for the delay in response. Thanks for your detailed reply, that clears it up.

In your example, can I ask why the data looks **identical** but with the black points just starting ~370m higher? Rather than some kind of depression at the start from regridding - or some other contortion, just not identical just shifted upwards?
