### ISSUE TITLE
Iris incorrectly merging variables with the same STASH code from pp file

### ISSUE THREAD

**Issue by andrewpauling** [SciTools/iris#5304]
## 🐛 Bug Report
I have pp files that have two temperature variables with the same STASH code, but two different pressure domain profiles. One has 19 pressure levels and the other has 27 pressure levels. When viewing the file using xconv I can see the two variables listed separately. 

Some of the values of the pressure coordinate are the same between the two profiles. When loading with `iris.load()`, these two variables are incorrectly merged with iris taking only the unique values in the pressure profile, and giving two duplicate variables with 34 pressure levels each (34 is the number of unique pressure values), instead of one with 19 and one with 27.

## How To Reproduce
Steps to reproduce the behaviour:

1. load pp file with `iris.load()`:

```
constraint = iris.AttributeConstraint(STASH="m01s30i294")
cubelist = iris.load(ppfile, constraints=constraint)
```

2. Output shown below:
![Screenshot 2023-05-04 at 10 43 18 AM](https://user-images.githubusercontent.com/22488770/236066707-c9c59541-d08c-46d6-b7e3-1b56adbb7d1e.png)
The second cube in the cubelist is a duplicate of the first. The 34 pressure levels are the unique values out of the total 46 (19+27) across the two variables.

3. If I load with the following method instead:
```
with iris.fileformats.um.structured_um_loading():
    cubelist = iris.load(ppfile, constraints=constraint)
````
I get the following output:
![Screenshot 2023-05-04 at 10 36 45 AM](https://user-images.githubusercontent.com/22488770/236065778-9e6d035d-7eae-4e93-b68b-30e39a7cb888.png)
where pressure is now an auxiliary coordinate with 46 (19+27) pressure levels. So, using the structured_loading context the pressure levels are not merged. The variable I want is the one with 19 levels, so as a workaround for now I can just select the first 19 pressure levels and reassign pressure as a normal coordinate. This seems like a nasty bug that could catch people out, however. 

## Expected behaviour
Expected `iris.load()` to produce a cubelist with two cubes, one with 19 pressure levels and one with 27.

## Environment 
 - OS & Version: CentOS Linux 7 (Core)
 - Iris Version: 3.4.1

**Comment by pp-mo** [comment]
@SciTools/peloton looking at this, the result is not what we would expect so this looks like a bug in merge.
( N.B. merging is always applied to loaded data in `iris.load`, for example this is what groups your data from one STASH into a single cube )

What we'd expect to get is, probably, 
  * one cube combining all 2D fields on levels from the 1st set *plus* those which only occur in the 2nd set
  * ..and.. another cube with all the levels from the 2nd set that overlap with ones in the 1st.

So, we should fix the merge, because we really don't think it should be _duplicating_ any input fields across multiple loaded cubes.

However, even when fixed, that isn't actually very useful behaviour, and certainly isn't what you are asking for (!)

It's not really practical to deliver what you ask for, since order of appearance in input files is rather definitely **_not_** available as a relevant factor when doing merge/concatenate operations -- that is pretty much by design, and we wouldn't really want to change it.

Regardless of such a "merge fix", you can get what you want with a workaround.
An easy way might be to distinguish the two sets using a [load callback](https://scitools-iris.readthedocs.io/en/stable/userguide/navigating_a_cube.html?highlight=callback#adding-and-removing-metadata-to-the-cube-at-load-time) to attach an extra attribute to "label" them : So we could add an attribute "set=1" to the first 19 counted, and "set=2" to the remaining ones.

Another approach is to use `load_raw`, which will return a 2D cube for each pp field, when you can group + merge them yourself.  But obviously, it's not as automatic

This assumes that the fields in the 2 sets can only be distinguished by their order of appearance in the file.
**Is that so?**
and if so, **would the above workaround be acceptable** @andrewpauling  ?

**Comment by andrewpauling** [comment]
Thanks for looking into this @pp-mo. I was able to get the data I wanted by loading with the `iris.fileformats.um.structured_um_loading()` context manager, which loads the 19 + 27 vertical levels without merging them, and then subsetting the first 19 manually. 

I guess my concern is that this was a very hard bug to catch, as the only way I learned that there were supposed to be two instances of the variable in the pp file with different numbers of vertical levels was by looking at the file with the xconv tool. This must mean that there is some metadata somewhere in the pp file that allows xconv to distinguish the two variables that iris is not using, since xconv does not know, a priori, what order the variables will be in. I was hoping it would be possible to somehow find and use this metadata.

It seems like this bug would definitely catch people out, it certainly did for me for a couple of weeks before I figured out what was going on.

**Comment by ESadek-MO** [comment]
@SciTools/peloton have discussed this.
Merge is a difficult concept to understand, and we appreciate the need for better documentation. 
Perhaps a future page of common "gotchas" might be in order, when resource allows.

**Comment by andrewpauling** [comment]
@ESadek-MO thank you for looking into this, but I don't think this is an issue of documentation. This seems like a bug in merge. There must be some piece of metadata that allows xconv to distinguish the two variables that iris does not have access to, or is not using. Then, rather than taking a conservative approach of returning all of the data, merge is combining the two variables in a way that results in data being lost, with no way for the user to know this without knowing beforehand what should be there.

**Comment by rcomer** [comment]
I do not know, but I suspect that xconv relies on the order of the fields in the file rather than metadata.  Happy to be corrected though - do you see any differences in the pp-headers of the fields?

> An easy way might be to distinguish the two sets using a [load callback](https://scitools-iris.readthedocs.io/en/stable/userguide/navigating_a_cube.html?highlight=callback#adding-and-removing-metadata-to-the-cube-at-load-time) to attach an extra attribute to "label" them : So we could add an attribute "set=1" to the first 19 counted, and "set=2" to the remaining ones.

I am curious about this because I can't off the top of my head think how you would count within a callback.

**Comment by pp-mo** [comment]
> I do not know, but I suspect that xconv relies on the order of the fields in the file rather than metadata. 

FWIW that is my suspicion too.
Iris load and merge are definitely supposed to be independent of file and field ordering.
Unless there is some other metadata not captured ?

As [described in the user guide](https://scitools-iris.readthedocs.io/en/stable/userguide/navigating_a_cube.html#adding-and-removing-metadata-to-the-cube-at-load-time), it's a very common use of callbacks to add metadata which is based on filepaths or field ordering in files.
Your investigation of structured loading might support that @andrewpauling , as structured loading most definitely does rely on file order.

**Comment by andrewpauling** [comment]
Thanks all for looking into this, but I do not understand how xconv could be distinguishing the variables only from the order. If we ignore metadata, the only difference between the variables is the pressure domain. xconv does not know what the pressure domains of the variables will be a priori, so I can't see how it could separate them based only on that information.

Similarly, structured loading does not distinguish the two variables based on order, it just loads all the data (both that with 19 levels and that with 27) into one cube without attempting to merge them. It is then dependent on me to know what the pressure levels should be to separate them into two variables after the fact.

**Comment by trexfeathers** [comment]
From @SciTools/peloton: we would really need to know how xconv is working this out, and that's not something we have the tools/resource to investigate. Will happily re-open this issue if there is more information to go on in future.
