### ISSUE TITLE
Installation issue - no modules (Python 3.11.4 Linux)

### ISSUE THREAD

**Issue by rebeccamayvarney** [SciTools/iris#5447]
## 📰 Custom Issue

Following the Installing instructions on 'https://scitools-iris.readthedocs.io/en/v3.7.0rc0/installing.html', my installed version of Iris says installation compete, however it has no associated modules. I have tried Conda and pip on my linux machine, and different versions of python (currently on 3.11.4). Any suggestions please?

**Comment by rebeccamayvarney** [comment]
Hi thank you for your help.

I created a new conda environment and activated it, then used 'conda install -c conda-forge iris'. This was successful and the installation was complete, however when I try to run my python scripts I get errors 'ModelNotFoundError'. For example, no module named 'iris.cube'.

I tried using pip outside my conda environment (pip install scitools-iris), however the same thing happened (iris installed but I have no modules).

I had iris working on an old computer so have existing scripts which have run in the past, however I cannot get it to work running python from the terminal with iris.

I hope this makes sense!

**Comment by rcomer** [comment]
Does `import iris.cube` work?

**Comment by rebeccamayvarney** [comment]
Thank you for your suggestion.

It did like that, but then it gets stuck at 'from iris.experimental.equalise_cubes import equalise_attributes'.

'ModelNotFoundError: No module named 'iris.experimental.equalise_cubes''.

Is this no longer a module?

**Comment by pp-mo** [comment]
Hi @rebeccamayvarney thanks for explaining.

I think from what you say...
> I had iris working on an old computer so have existing scripts which have run in the past
> example, no module named 'iris.cube'

This is probably because of a change we made a while back in Iris 3.1, to have [less sub-modules imported automatically](https://scitools-iris.readthedocs.io/en/v3.7.0rc0/whatsnew/3.1.html#minimised-imports).

So for instance, if you want to run "cube = iris.cube.Cube([1])", then _before_ you could just say "import iris", but now you must say "import iris.cube", as Cube is in a sub-module which is no longer "automatically" imported by the parent one.

Technically, importing all sub-modules **_explicitly_** like that is just "good practice" in Python generally.
But practically it's a bit awkward when it breaks legacy code.  
If it seems practical, then it's probably easiest to iteratively add missing imports "until it works".
But of course that can leave hidden problems in rarely-used parts of the code, so a code search might be wise too.

Anyway, hope that helps.
**Was this the actual problem ?**

**Comment by rebeccamayvarney** [comment]
That is great, thank you!!

**Comment by ESadek-MO** [comment]
@SciTools/peloton This looks done, feel free to reopen if you find further problems!
