### ISSUE TITLE
Concatenation of LFRic output along the time dimension

### ISSUE THREAD

**Issue by dennissergeev** [SciTools/iris#5576]
## 🐛 Bug Report

I was trying to process LFRic output by loading several files into one `CubeList`. However, in the resulting dataset the cubes are not concatenated along the `time` coordinate, and are instead listed separately.

The time dimension is also not recognised as dimensional, which might be a related issue. Promoting it to the `DimCoord` class sometimes helps and sometimes does not, so it seems to be a bug (?).

I have tried comparing the cubes' metadata and the metadata of their coordinates - they are all identical. `ncdump` also shows no differences in the coordinate metadata.

When I force concatenation by using the `concatenate_cube()` method, I get this error:

```
ConcatenateError: failed to concatenate into a single cube.
  An unexpected problem prevented concatenation.
```

Note that this problem seems to occur for _some_ LFRic runs but not others, and so far I cannot pinpoint the pattern. Could it be due to the number of files I try to load at once? (E.g. is 100 too many?)

## How To Reproduce
Steps to reproduce the behaviour:

I have attached 2 files as an example [concat_issue_lfric_diag.zip](https://github.com/SciTools/iris/files/13334688/concat_issue_lfric_diag.zip)

For these two files, using `concatenate(check_aux_coords=False)` actually helps, but the issue with the time coordinate remains. I am happy to provide more LFRic data if needed.

## Environment 
 - OS & Version: Ubuntu 22.04 LTS
 - Iris Version: 3.7.0

**Comment by trexfeathers** [comment]
Hi @dennissergeev, thanks for reporting this, and sorry for the delay. I have investigated the files you provided.

## Time not a dimension coordinate

The files do not describe the time coordinate as a dimension coordinate - the dimension is called `time_counter`, but the coordinate variable is called `time_instant`; dimension coordinates are defined by the variable and dimension names being identical. If I rename `time_instant` before loading (and all references to it), the time coordinate DOES become a dimension coordinate.

## Not merging to a single cube

As you say, the metadata and values of all other coordinates are identical. But this is the misleading nature of [`MeshCoord`s](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris.experimental.ugrid.html#iris.experimental.ugrid.MeshCoord), which are just a representation of how the data relates to the underlying [`Mesh`](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris.experimental.ugrid.html#iris.experimental.ugrid.Mesh). When you want to combine two cubes, the `Mesh`es themselves need to be identical, and they are not identical for the example files. This is not clear from the error message so that needs to be improved; I will write up an issue for that.

**Comment by trexfeathers** [comment]
I've raised #5683. Going to close this one since it has much wider scope. Please re-open if you think there is more to discuss.

**Comment by dennissergeev** [comment]
Thanks very much @trexfeathers! For now I am coping with cube concatenation using some workarounds but I will keep my eye on #5683.

**Comment by trexfeathers** [comment]
Just to be clear: #5683 will not make it possible to merge these 2 cubes. That will always be impossible so long as they have different meshes. If they are supposed to be the same mesh then there is an issue with the production of the data.

If there are technically the same meshes but just with stuff in different orders then I'm sure you understand this would be difficult for Iris to solve, since confirming this would be a very expensive operation. We have communicated this concept to those developing LFRic in the past.

**Comment by dennissergeev** [comment]
Thanks for the clarification! Perhaps there could be an iris utility that can "equalise" meshes somehow? I guess I can just replace the mesh of one cube with that of another.

In any case, I don't understand why the meshes in this example would be different - they are from the same LFRic run...

**Comment by trexfeathers** [comment]
See #5992
