### ISSUE TITLE
lazy points and bounds in `Coord.cell`

### ISSUE THREAD

**Issue by fnattino** [SciTools/iris#5723]
Currently, calling the `.cell` method on a coordinate with lazy data will trigger loading/realisation of the coordinate data to compute the cell point/bound.

Here is a minimum reproducible example:

```python
import dask.array as da
from iris.coords import AuxCoord

aux_coord = AuxCoord(da.arange(0, 100, 10))

# the following triggers realisation of the coordinate
aux_coord.cell(0)
# Cell(point=0, bound=None)
```

Would it make sense to make it such that the cell points and bounds are computed lazily if the underlying data is also lazy? This would avoid e.g. triggering data loading when the cube is read from disk. 

Happy to contribute with a PR, if you think it makes sense to make the `Coord.cell` method fully lazy.

**Comment by bjlittle** [comment]
@fnattino Thanks for raising this issue.

Given your example above, I get the following ...

![image](https://github.com/SciTools/iris/assets/2051656/67776c22-a323-45b9-89c7-77ee5dff51a7)

Just to clarify, are you proposing that the returned `Cell` instance should have lazy members?

**Comment by HGWright** [comment]
@SciTools/peloton We believe this is really a debate about what happens when you `print(cube)`. We can see that changing this behaviour would fix your workflow, but we are aware of many other workflows that need to see the values of scalar coords when printing cubes. We have a couple of workarounds for your situation:

1. Before first printing force realisation of the scalar coordinate using `cube.coord(*cell_name*).points` and `cube.coord(*cell_name*).bounds`.
2. Don't print the cube, rather access `print(cube.summary(shorten=True))`.

It is true that there is an inconsistency between cell and cube/coords, but cells are special for the internal workings of Iris and anyway making them consistent wouldn't fix the problem of printing a cube.

**Comment by fnattino** [comment]
Thanks @HGWright , I understand that making Cell components lazy will affect other workflows, so it is not an option. 

I am still wondering how to best tackle my specific issue. Your second suggestion does not seem to work, because the full content of the cube summary table (thus including the scalar coordinate) is computed even if the only table header is printed out. Maybe one could modify the CubePrinter and CubeSummary so that they only set up the header (and not the rest of the summary) if `shorten=True` ?   

This way I could avoid forcing the realization of the scalar coordinates when this information is not even printed out.

Apologies for drifting from the original topic of the issue - we can close this and  continue discussion in a new issue if you think it's more appropriate.

**Comment by stephenworsley** [comment]
@SciTools/peloton  Yes, I think opening a new issue about fixing the way print works is the right way to tackle this. We'll raise an issue soon about how we think print ought to be fixed.

**Comment by pp-mo** [comment]
> @SciTools/peloton Yes, I think opening a new issue about fixing the way print works is the right way to tackle this. We'll raise an issue soon about how we think print ought to be fixed.

My suggestion : #5743
