### ISSUE TITLE
Post merge promote aux coord to dim

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#6021]
## ✨ Feature Request
Suggestion: After merge, if the result has multiple aux coords representing the same dimension, and all but one contain a single repeating point, then that one coord should be promoted to a dim coord, and the others demoted to scalars.

## Motivation
When loading certain model output, the pressure coord for geopotential height is not a dim coord, it's an aux coord. There is a forecast period and a time coord, for the same dimension, which contain a single reapeating value. This doesn't happen for other cubes in the same file, which get normal pressure dim coords. This causes the saved netcdf output to contain two separate pressure coordinates, causing problems downstream - mainly in Met and ncview, I think. Ncview also doesn't seem to realise it's pressure at all, it's just called dim0 and shows up as indices instead of pressure levels.

## Additional context
We can work around this using loading callbacks.

**Comment by pp-mo** [comment]
First, I should warn that many attempts to 'incrementally improve' merging (and especially merge-on-load) have already fallen due to the 'too much breaking change' problem !
For instance : #3344 #3603

All the same, we can look into this, because the behaviour seems odd to me..

Given that you are loading "model output" I guess this is PP or FF format data ?
In which case, all dimensions except the horizontal are split across multiple input fields, and hence must be re-constructed by the merge operation (within the load function).

What puzzles me about this, is not so much having coords on a common auxiliary dimension, but rather why merge is creating those coords with repeating values instead of making them scalars.
The examples I have tried result in scalar coords.

It's not, by any chance, because your load specifies some **additional constraint** which is post-indexing the results ?

To debug this, I think you should print out what the "raw cubes" are before the merge -- i.e. results from ``iris.load_raw``.
If you could show what that looks like, we can work out what is going on here.

**Comment by bblay** [comment]
Hi @pp-mo , I pasted a link to the input file in the internal avd forum. I was advised not to include that in this public area.

I can stop the problem happening by loading raw slices and extracting `forecast_period=6`. They then merge correctly. Without the fp extraction, a couple of pressure levels get extra slices, for other forecast periods, and that seems to stop the merge for working. Is that helpful info?

**Comment by pp-mo** [comment]
@SciTools/peloton there may be something odd going on here, but we probably don't have time to investigate.
From offline discussion, a workaround is available for the original problem, anyway.
So closing :-(
Unless it's a real problem for someone ?  -- in which case please re-open.
