### ISSUE TITLE
pypi submission

### ISSUE THREAD

**Issue by schwehr** [SciTools/iris#606]
It appears the scitools iris has not been submitted to pypi.  Could you please submit point releases to pypi?

**Comment by cbarrick** [comment]
Bumping this three years later?

**Comment by pelson** [comment]
The 2.0.0rc1 is available under scitools-iris on pypi. Plenty of room for improvement (like a description), but the source dist is available there at least. Help (in the form of PRs) very much welcomed to improve the **non-binary** ``pip install scitools-iris`` experience.

**Comment by schwehr** [comment]
Awesome!  Thanks!

**Comment by pelson** [comment]
It is certainly not perfect - but happy to tweak if you come up with any issues.

Thanks!

**Comment by rdkr** [comment]
Hi, `pip install scitools-iris` fails for me, due to [setup.py#L252](https://github.com/SciTools/iris/blob/master/setup.py#L252) as `requirements/all.txt` isn't packaged.

**Comment by rdkr** [comment]
Some further details, running Python 3.6.2 in a clean virtual environment:
* I pip downloaded the package, removed the above mentioned `extras_require` entries from `setup.py` and tried to install from within the local directory with `pip install .` which failed due to missing `pyke`.
* I downloaded Pyke from SourceForge and installed it with `pip install local/path/to/pyke3-1.1.1.zip`. After this, I was able to install Iris succesfully.
* Finally, to be able to `import iris` without error, I had to `pip install toolz scipy`.

**Comment by pelson** [comment]
> Hi, pip install scitools-iris fails for me, due to setup.py#L252 as requirements/all.txt isn't packaged.

Fixed in versions greater than v2.0.0rc1. See https://github.com/SciTools/iris/blame/v2.0.x/MANIFEST.in#L11.

> which failed due to missing six (consequently pip installed), then pyke.

I don't think there is anything we can do for pyke (it isn't pip installable from pypi), though maybe we should just upload the sdist to pypi ourselves... (https://sourceforge.net/projects/pyke/files/pyke/1.1.1/pyke3-1.1.1.zip/download)

As for six, I think we've overlooked the ``setup_requires`` functionality. Looks like we should have the ``setup`` requirements in *both* ``setup_requires`` and ``install_requires``.  Ref: http://setuptools.readthedocs.io/en/latest/setuptools.html. I'll open a PR for that.

> Finally, to be able to import iris without error, I had to pip install toolz scipy

``toolz`` isn't a dependency of iris, though maybe we are using some of the functionality in dask that does require it, and we aren't being specific enough with our pip requirements. Would you be interested in digging into that?

``scipy`` is a core dependency and is completely missing from the requirements. I'll open a PR for that.

**Comment by pelson** [comment]
@dangyogi - sorry for bothering you, but would you be willing to upload a pyke3 to pypi to go along with https://pypi.python.org/pypi/pyke?

**Comment by pelson** [comment]
@rdkr - I've just tagged v2.0.0 and uploaded it to pypi. Have another go and feel free to raise any issues you encounter (including adding a description to pypi!). 
https://pypi.python.org/pypi/scitools-iris

**Comment by shoyer** [comment]
> toolz isn't a dependency of iris, though maybe we are using some of the functionality in dask that does require it, and we aren't being specific enough with our pip requirements. Would you be interested in digging into that?

`toolz` is a dependency of `dask.array`.

You might want to switch your dependency to `dask[array]`. I know that works with pip (e.g., `pip install dask[array]`) but I'm not entirely sure it works as a dependency with `setuptools.setup`.
