### ISSUE TITLE
PP pressure vs LFRic

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#6189]
Hi, Iris doesn't load PP pressure coords with the CF standard name **air_pressure**. Instead, it loads with no standard name and a long name of **pressure**. In contrast, recent LFRic data loads with the CF standard name.

Therefore, the following constraint no longer works and existing comparison code fails.
```python
iris.Constraint(pressure=lblev)
```

Considering what to do about this, of course we can manipulate the coord names but, ideally, Iris _could_ load the coord with the proper CF name. I assume there's a good reason not to do this by default, like PP ambiguity and/or backwards compatibility.

Can I ask: What's the explanation for this? Are there any ongoing discussions about this, or plans to make it use the CF standard name? Is it worth asking for a flag or something, so people can have PP loaded "correctly"? Thanks for any insight!

Here's some code to highlight the difference:
```python
cube = Cube(
    standard_name='air_temperature', units='K',
    data=np.zeros((10, 10, 10)),
    dim_coords_and_dims=[
        (DimCoord(standard_name='air_pressure', points=range(10), units='hPa'), 0),
        (DimCoord(standard_name='latitude', points=range(10), units='degrees'), 1),
        (DimCoord(standard_name='longitude', points=range(10), units='degrees'), 2),
    ])

iris.save(cube, 'cube.nc')
iris.save(cube, 'cube.pp')

print(iris.load('cube.nc')[0].coord(axis='z'))
print(iris.load('cube.pp')[0].coord(axis='z'))
```
Output:
```
DimCoord :  air_pressure / (hPa)
    points: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    shape: (10,)
    dtype: int64
    standard_name: 'air_pressure'
    var_name: 'air_pressure'
DimCoord :  pressure / (hPa)
    points: [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]
    shape: (10,)
    dtype: float32
    long_name: 'pressure'
```

**Comment by trexfeathers** [comment]
>What's the explanation for this?

It's PP ambiguity, as you suggested. We rely on others' expertise to advise us of correct mapping with CF standard names, and in the absence of that we avoid making our own decisions. Below is the code, which is based on Section 4.2, Word 26 (LBVC) of **Unified Model Documentation Paper F03**, which simply states `Pressure` as the name. Since this is not a CF standard name, we enter it as a long name.

https://github.com/SciTools/iris/blob/dd2901710a3dd1e6ee294b5668d41b6981eefdb9/lib/iris/fileformats/pp_load_rules.py#L204-L209

With the demise of metarelate, there is official way to record the correct mapping of CF standard names, we simply rely on people telling us.

>Are there any ongoing discussions about this, or plans to make it use the CF standard name?

No.

>Is it worth asking for a flag or something, so people can have PP loaded "correctly"?

I'd be against this. If there is a correct way Iris should be loading the coordinate, then we should implement that (e.g. we could include a `standard_name` in the above code, in addition to the existing `long_name`, if you or someone else could confirm the correct `standard_name` to use).

If we can't make a categorical statement about the right thing to do (there are a lot of CF standard names for pressure!), then switchable behaviour typically belongs in downstream code, otherwise Iris gradually accumulates switches and flags that we don't have the resource to maintain. In this case you could detect what kind of file you are loading and conditionally apply the appropriate constraint.

**Comment by bblay** [comment]
Thanks @trexfeathers, and I agree therefore a switch wouldn't be desirable. The callback is easy to implement, too.
