### ISSUE TITLE
grib save bug

### ISSUE THREAD

**Issue by bblay** [SciTools/iris#677]
Crashes when ellipsoid is None.
[if ellipsoid.inverse_flattening == 0.0:](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/grib/grib_save_rules.py#L78)

**Comment by dkillick** [comment]
I think this is now fixed... in `iris_grib`, as there's [code to catch a missing ellipsoid](https://github.com/SciTools/iris-grib/blob/master/iris_grib/_save_rules.py#L200-L207). Given that this bug is also very old and the pertinent code is no longer in the Iris codebase, I'm going to close this issue.
