### ISSUE TITLE
Erroneous guessing of unit names

### ISSUE THREAD

**Issue by niallrobinson** [SciTools/iris#699]
Iris guesses the name of a cubes unit for use in quickplotting (and possibly) elsewhere. However, this is sometimes incorrect e.g. units of m2 s-2 can be Grays, but equally can be Energy Transfer. There should be a way of manually overwriting the unit name in a cube if the default is wrong.

**Comment by rcomer** [comment]
... 6 years later...

This has just come up for me.  I was also not expecting Grays when I squared my wind speeds!  I can replace my unit on the cube with `'m**2 / s**2'`, but it will still come up as 'Gy' on a quickplot.  I note that the [Unit string method](https://github.com/SciTools/cf-units/blob/master/cf_units/__init__.py#L1466) uses `self.origin or self.symbol`.  Perhaps quickplot should defer to `str(cube.units)`.  Then users would see something consistent when they print and plot the cube, and be able to "fix" the unit with a string of their choice, i.e:

`cube.units = 'units wot I wanted'`

**Comment by bjlittle** [comment]
@rcomer Do you have a code except that highlights this issue? It would be nice to point to a concrete example... you never know, we might then actually fix it :blush:

**Comment by rcomer** [comment]
OK, suppose I have a cube of wind speeds:

```python
import iris
import iris.quickplot as qplt
import matplotlib.pyplot as plt
import cf_units

for module in [iris, cf_units]:
    print(module.__name__, module.__version__)

cube = iris.cube.Cube(range(5), standard_name='wind_speed', units='m/s')
coord = iris.coords.DimCoord(range(5), standard_name='time',
                             units='days since 2019-07-07')

cube.add_dim_coord(coord, 0)

print(cube)
qplt.plot(cube)
```
Everything looks sensible:
```
iris 2.2.0
cf_units 2.0.1
wind_speed / (m/s)                  (time: 5)
     Dimension coordinates:
          time                           x

```
![windy](https://user-images.githubusercontent.com/10599679/60871471-bf1a2a80-a22a-11e9-9542-7d089b76779f.png)

Let's look at the square:
```python
new_cube = cube ** 2

print(new_cube)
qplt.plot(new_cube)
```

Now we get:
```
unknown / (Gy)                      (time: 5)
     Dimension coordinates:
          time   
```
![wind_squared](https://user-images.githubusercontent.com/10599679/60872475-9f840180-a22c-11e9-803c-e6c157b92534.png)


Metadata looks wrong, but we can fix that, right?
```python
new_cube.rename('wind_speed_squared')
new_cube.convert_units('m2/s2')

print(new_cube)
qplt.plot(new_cube)
```
Now the print out of my cube looks how I expect, but the plot still shows Grays on the y-axis:
```
wind_speed_squared / (m2/s2)        (time: 5)
     Dimension coordinates:
          time                           x
```
![wind_squared2](https://user-images.githubusercontent.com/10599679/60872489-a6127900-a22c-11e9-9301-3e34de465b16.png)

My "real" example involves eddy diagnostics `u'**2 + v'**2` and `u'**2 - v'**2`, where `'` indicates band pass filtering.  I don't think we want to go there...

Admittedly this isn't a high priority issue, as I can always change the plot labels myself rather than relying on quickplot.

**Comment by jamesp** [comment]
Is this still an issue in iris 3.0.1? For now, I'm closing this and we should reopen a new one if it's still a problem.

**Comment by rcomer** [comment]
I can still reproduce the issue under Iris 3.0.1 but neither @niallrobinson nor myself ever felt strongly enough about it to open a PR, so it's probably not important.  I'm happy to leave it closed.

**Comment by jamesp** [comment]
Thanks for the feedback @rcomer, it's pretty straightforward to reopen this issue again if we find we have a strong reason to!
